type Band = "support" | "core" | "stretch";
type Variant = { tag: string; widget: any; answer: any };
type VariantGen = { tag: string; label: string; forms?: readonly never[]; gen: (rand:()=>number, band?:Band, form?:string)=>Variant };
type Rand=()=>number;
const pick=(r:Rand,a:number,b:number)=>a+Math.floor(r()*(b-a+1));
const choose=<T>(r:Rand,xs:readonly T[])=>xs[pick(r,0,xs.length-1)];
const cap=(b:Band,s:number,c:number,t:number)=>b==='support'?s:b==='stretch'?t:c;
const round=(n:number,d=6)=>Number(n.toFixed(d));
const gcd=(a:number,b:number):number=>b===0?Math.abs(a):gcd(b,a%b);
const feedback=(s:string)=>s.length>=25?s:`${s} Recheck the displayed mathematical relationship.`;
const shuffle=<T>(r:Rand,xs:readonly T[])=>{const a=[...xs];for(let i=a.length-1;i>0;i--){const j=pick(r,0,i);[a[i],a[j]]=[a[j],a[i]]}return a};
const fmt=(n:number)=>Number.isInteger(n)?String(n):String(round(n,6));
/** A ratio printed as mathematics — "2/3", "-1/2", "4" — never as a truncated decimal. */
const fracStr=(n:number,d:number)=>{if(d<0){n=-n;d=-d}const g=gcd(n,d)||1,nn=n/g,dd=d/g;return dd===1?String(nn):`${nn}/${dd}`};
/** Root named the way it is read aloud: square, cube, fourth — never "3th". */
const rootWord=(q:number)=>q===2?'square':q===3?'cube':q===4?'fourth':`${q}th`;
const sign=(n:number)=>n<0?`− ${Math.abs(n)}`:`+ ${n}`;
const xterm=(a:number,p=1)=>{const x=p===1?'x':`x^${p}`;return a===1?x:a===-1?`−${x}`:`${a}${x}`};
const linear=(a:number,b:number)=>`${xterm(a)} ${sign(b)}`;
const signedX=(a:number,p=1)=>a<0?`− ${xterm(-a,p)}`:`+ ${xterm(a,p)}`;
const binomial=(variable:string,c:number)=>c===0?variable:`${variable}${c<0?'−':'+'}${Math.abs(c)}`;
const complexText=(re:number,im:number)=>{const imag=Math.abs(im)===1?'i':`${Math.abs(im)}i`;if(re===0)return im<0?`−${imag}`:imag;return `${re} ${im<0?'−':'+'} ${imag}`};
function uniqueNums(ans:number,vals:Array<[number,string]>) {const seen=new Set([round(ans,10)]),out:Array<[number,string]>=[];for(const [v,f] of vals){const q=round(v,10);if(Number.isFinite(q)&&!seen.has(q)){seen.add(q);out.push([q,feedback(f)])}}for(let d=1;out.length<2;d++)for(const q of [round(ans+d,10),round(ans-d,10)])if(!seen.has(q)){seen.add(q);out.push([q,feedback('This value comes from changing one operation or sign instead of preserving the stated relationship.')]);if(out.length>=2)break}return out.slice(0,3)}
const num=(tag:string,prompt:string,answer:number,errs:Array<[number,string]>,success:string,tolerance=0,params?:Readonly<Record<string,number|string>>):Variant=>({tag,answer:round(answer,10),...(params?{params}:{}),widget:{type:'numeric',prompt,answer:round(answer,10),tolerance,unit:'',commonErrors:uniqueNums(answer,errs).map(([value,fb])=>({value,feedback:fb})),fallbackFeedback:feedback('Reconstruct the relationship from the visible quantities and verify each operation.'),successFeedback:feedback(success)}});
const mcq=(r:Rand,tag:string,prompt:string,correct:[string,string],wrong:Array<[string,string]>):Variant=>{const seen=new Set<string>();const all=[correct,...wrong].filter(([l])=>!seen.has(l)&&seen.add(l));while(all.length<4)all.push([`Alternative ${all.length+1}`,'This alternative does not preserve the displayed mathematical structure.']);const options=shuffle(r,all.slice(0,4).map(([label,fb],i)=>({id:`o${i}`,label,feedback:feedback(fb),correct:i===0}))).map((o,i)=>({...o,id:`o${i}`}));return{tag,answer:options.find(o=>o.correct)!.id,widget:{type:'mcq',prompt,options}}};
function build(tag:string,prompt:string,correctLabels:string[],distractors:string[],success:string):Variant{const labels=[...new Set([...correctLabels,...distractors])];while(labels.length<2)labels.push('not used');const tokens=labels.map((label,i)=>({id:`t${i}`,label}));const idFor=(label:string)=>tokens.find(t=>t.label===label)!.id;const correct=correctLabels.map(idFor);let wrong=[...correct].reverse();if(wrong.join('|')===correct.join('|'))wrong=[idFor(labels.find(x=>!correctLabels.includes(x))||labels[0])];return{tag,answer:correct,widget:{type:'buildExpression',prompt,tokens,correct,acceptAlso:[],commonBuilds:[{sequence:wrong,feedback:feedback('This arrangement reverses or replaces a required algebraic relationship.')}],reusable:false,missFeedback:feedback('Use every required mathematical part in an order that makes the statement true.'),successFeedback:feedback(success)}}}
function order(r:Rand,tag:string,prompt:string,correctLabels:string[],success:string):Variant{let items=shuffle(r,correctLabels.map((label,i)=>({id:`i${i}`,label})));if(items.map(x=>x.label).join('|')===correctLabels.join('|'))items=[...items.slice(1),items[0]];const byLabel=Object.fromEntries(items.map(x=>[x.label,x.id]));const correctOrder=correctLabels.map(x=>byLabel[x]);return{tag,answer:correctOrder,widget:{type:'dragOrder',prompt,items,correctOrder,misorderFeedback:[{first:correctOrder[1],second:correctOrder[0],feedback:feedback('The first two operations are reversed; follow the function or procedure from the input outward.')}],missFeedback:feedback('Trace the operation or inference sequence from its starting condition to its conclusion.'),successFeedback:feedback(success)}}}
function bucket(r:Rand,tag:string,prompt:string,bucketsIn:Array<[string,string[]]>,success:string):Variant{const buckets=bucketsIn.map(([label],i)=>({id:`b${i}`,label}));const items=shuffle(r,bucketsIn.flatMap(([_,labels],bi)=>labels.map((label,j)=>({id:`i${bi}_${j}`,label,bucketId:`b${bi}`,feedback:feedback(`This example belongs with ${bucketsIn[bi][0]} because of its defining structure.`)}))));const answer=Object.fromEntries(items.map(i=>[i.id,i.bucketId]));return{tag,answer,widget:{type:'dragBucket',prompt,buckets,items,missFeedback:feedback('Classify each item by the mathematical feature named on the buckets.'),successFeedback:feedback(success)}}}
function pairs(r:Rand,tag:string,prompt:string,entries:Array<[string,string]>,success:string):Variant{const left=entries.map(([l],i)=>({id:`l${i}`,label:l}));let right=shuffle(r,entries.map(([_,label],i)=>({id:`r${i}`,label})));const mapping=Object.fromEntries(entries.map((_,i)=>[`l${i}`,`r${i}`]));const aligned=(rs:typeof right)=>left.every((l,i)=>mapping[l.id]===rs[i]?.id);for(let t=0;t<right.length&&aligned(right);t+=1)right=[...right.slice(1),right[0]!];return{tag,answer:mapping,widget:{type:'matchPairs',prompt,left,right,pairs:mapping,pairErrors:entries.length>1?[{left:'l0',right:'r1',feedback:feedback('This link confuses two quantities or representations with different meanings.')}]:[],missFeedback:feedback('Match each statement to the representation or interpretation that follows from its definition.'),successFeedback:feedback(success)}}}
function point(tag:string,prompt:string,answer:number[],success:string):Variant{const swapped=[answer[1],answer[0]],wrong=swapped[0]===answer[0]&&swapped[1]===answer[1]?[answer[0]+1,answer[1]]:swapped;return{tag,answer,widget:{type:'pointEntry',prompt,answer,delimiter:'paren',slotLabels:['x-coordinate','y-coordinate'],commonEntries:[{values:wrong,feedback:feedback(swapped[0]===answer[0]&&swapped[1]===answer[1]?'This changes one coordinate even though the inverse point is fixed on y=x.':'The coordinates are reversed; an inverse swaps input and output in the other direction.')}],fallbackFeedback:feedback('Enter the ordered pair in x-then-y order.'),successFeedback:feedback(success)}}}
function plot(tag:string,prompt:string,re:number,im:number):Variant{const labels=['−3','−2','−1','0','1','2','3'];const target={x:re+4,y:im+4};const swapped={x:im+4,y:re+4};const wrong=swapped.x===target.x&&swapped.y===target.y?{x:Math.max(1,Math.min(7,target.x+(target.x<7?1:-1))),y:target.y}:{...swapped};return{tag,answer:[target],widget:{type:'plotPoint',prompt,cols:7,rows:7,xLabels:labels,yLabels:labels,targets:[target],connectTargets:false,pointErrors:[{...wrong,feedback:feedback(swapped.x===target.x&&swapped.y===target.y?'This point changes the real coordinate instead of preserving the stated complex number.':'The real and imaginary coordinates are swapped.')}],missFeedback:feedback('Use the real part horizontally and the imaginary coefficient vertically.'),successFeedback:feedback(`${complexText(re,im)} is represented by the point (${re}, ${im}).`)}}}

const CN='a2-complex';
function complex(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 if(c==='cn-add-sub')return mcq(r,CN,'Why do real and imaginary parts combine separately in a complex sum?',['They are coefficients of different basis directions, 1 and i.','Real and imaginary components represent independent directions, so like parts combine with like parts.'],[['Because i always equals 1','The imaginary unit satisfies i² = −1, not i = 1.'],['Because every complex number is purely real','A nonzero imaginary coefficient prevents the number from being purely real.'],['Because addition changes i into −1','Only a product containing i² changes into −1.']]);
 if(c==='cn-build-quad'){const h=pick(r,-3,4),k=pick(r,1,cap(b,3,5,7)),B=-2*h,C=h*h+k*k,eq=`x² ${B<0?'−':'+'} ${Math.abs(B)}x + ${C} = 0`;
  if(s==='buildExpression')return build(CN,`Build the monic quadratic whose roots are ${h} + ${k}i and ${h} − ${k}i.`,['x²',B<0?`− ${Math.abs(B)}x`:`+ ${B}x`,`+ ${C}`,'= 0'],[`− ${C}`],`Conjugate roots give sum ${2*h} and product ${C}, producing ${eq}.`);
  return mcq(r,CN,`Which monic quadratic has roots ${h} ± ${k}i?`,[eq,'The conjugate roots have sum 2h and product h² + k².'],[[`x² ${B<0?'+':'−'} ${Math.abs(B)}x + ${C} = 0`,'This reverses the sign of the root sum.'],[`x² ${B<0?'−':'+'} ${Math.abs(B)}x − ${C} = 0`,'The conjugate product is h² + k², which is positive.'],[`x² + ${C} = 0`,'This omits the nonzero real part of the roots.']]);}
 if(c==='cn-complex-plane'){const re=pick(r,-3,3),im=pick(r,-3,3)||2;if(s==='plotPoint')return plot(CN,`Plot z = ${re} ${im<0?'−':'+'} ${Math.abs(im)}i.`,re,im);return mcq(r,CN,`For z = ${re} ${im<0?'−':'+'} ${Math.abs(im)}i, what is the imaginary part?`,[String(im),'The imaginary part is the real coefficient multiplying i.'],[[String(re),'That is the real part.'],[`${im}i`,'The imaginary part is the coefficient, not the entire imaginary term.'],[String(Math.abs(im)),'The sign of the imaginary coefficient matters.']]);}
 if(c==='cn-cts-solve')return mcq(r,CN,'Why is the same square added to both sides when completing the square?',['It preserves equality while creating a perfect-square trinomial.','Equal changes preserve the equation, and the chosen square completes the binomial pattern.'],[['It changes the solutions to easier numbers','A valid transformation must preserve, not replace, the solution set.'],['Only the left side needs the added term','Adding to one side alone would destroy equality.'],['It makes the leading coefficient zero','Completing the square does not remove the quadratic term.']]);
 if(c==='cn-formula-complex'){let h=pick(r,-3,4);while(h===0)h=pick(r,-3,4);const k=pick(r,1,5),B=-2*h,C=h*h+k*k;return build(CN,`Build both solutions of x² ${B<0?'−':'+'} ${Math.abs(B)}x + ${C} = 0.`,[`x = ${h} + ${k}i`,'or',`x = ${h} − ${k}i`],[`x = ${-h} + ${k}i`],`The negative discriminant produces the conjugate pair ${h} ± ${k}i.`)}
 if(c==='cn-method-choice')return mcq(r,CN,'Which method is guaranteed to solve every quadratic equation?',['The quadratic formula','It applies to any coefficients with a nonzero quadratic term.'],[['Factoring over integers','Many quadratics do not factor over integers.'],['Taking a square root immediately','That works only after isolating a perfect square.'],['Reading integer zeros from a graph','Some roots are irrational or complex and may not be visible as intercepts.']]);
 if(c==='cn-multiply'){const a=pick(r,2,7),d=pick(r,2,7);return mcq(r,CN,`What is (${a}i)(${d}i)?`,[String(-a*d),'Multiplying gives ad·i², and i² = −1.'],[[String(a*d),'This forgets that i² = −1.'],[`${a*d}i`,'The two imaginary factors combine to i², not i.'],[String(-(a+d)),'The coefficients multiply rather than add.']]);}
 if(c==='cn-neg-eq'){const h=pick(r,-3,4),k=pick(r,2,6);if(s==='buildExpression')return build(CN,`Build the solutions of (x ${h<0?'+':'−'} ${Math.abs(h)})² = −${k*k}.`,[`x = ${h} + ${k}i`,'or',`x = ${h} − ${k}i`],[`x = ${h+k}`],`Taking complex square roots gives x − ${h} = ±${k}i.`);return mcq(r,CN,`Does x = ${k}i satisfy x² + ${k*k} = 0?`,['Yes',`(${k}i)² = −${k*k}, so the equation becomes zero.`],[['No','Squaring i introduces a negative sign.'],['Only if i = 1','The imaginary unit is defined by i² = −1.'],['Only the negative root works','Both ±ki square to the same negative real number.']]);}
 throw new Error(`unsupported ${CN} ${form}`)}

const FT='a2-transformations';
function transformations(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 if(c==='ft-arith'){const x=pick(r,1,5),a=pick(r,2,5),d=pick(r,-4,4),f=x*x,g=a*x+d,ans=f-g;if(s==='numeric')return num(FT,`Let f(x)=x² and g(x)=${a}x ${sign(d)}. Find (f−g)(${x}).`,ans,[[f+g,'This adds the function values instead of subtracting them.'],[g-f,'This reverses the subtraction order.']],`Evaluate both functions first, then compute ${f} − ${g} = ${ans}.`);return mcq(r,FT,'What does (f − g)(x) mean?',['f(x) − g(x)','Function subtraction subtracts the outputs at the same input.'],[['f(x − g)','This changes the input instead of subtracting outputs.'],['f(g(x))','That is function composition.'],['f(x)/g(x)','That is the quotient of functions.']]);}
 if(c==='ft-compose-rule'){const k=pick(r,1,6),x=pick(r,1,6),ans=(x+k)**2;if(s==='numeric')return num(FT,`Let f(u)=u² and g(x)=x+${k}. Find f(g(${x})).`,ans,[[(x*x)+k,'This squares before applying the inner shift.'],[x*x+k*k,'This omits the middle term created by squaring a sum.']],`The inner output is ${x+k}; squaring it gives ${ans}.`);return mcq(r,FT,`Which pair gives f(g(x))=(x+${k})²?`,[`f(u)=u² and g(x)=x+${k}`,'The inner function creates x+k, and the outer function squares it.'],[[`f(u)=u+${k} and g(x)=x²`,'This composition gives x²+k instead.'],[`f(u)=u²+${k} and g(x)=x`,'This gives x²+k rather than a shifted input square.'],[`f(u)=u+${k}² and g(x)=x`,'This adds a constant instead of squaring the shifted input.']]);}
 if(c==='ft-compose'){const x=pick(r,1,5),a=pick(r,2,4),d=pick(r,-3,3),f=x*x,g=a*f+d;return num(FT,`Let f(x)=x² and g(x)=${a}x ${sign(d)}. Find g(f(${x})).`,g,[[a*x+d,'This applies g directly to x and skips f.'],[(a*x+d)**2,'This computes f(g(x)) instead of g(f(x)).']],`First f(${x})=${f}; then g(${f})=${g}.`)}
 if(c==='ft-full-rule'){const h=pick(r,-3,4),a=choose(r,[-3,-2,2,3] as const),k=pick(r,-5,5);if(s==='dragOrder')return order(r,FT,`Order the operations that map x to y=${a}(x ${h<0?'+':'−'} ${Math.abs(h)})² ${sign(k)}.`,[`Shift the input by ${-h}`,'Square the result',`Multiply by ${a}`,`Add ${k}`],'The transformation is applied from inside the parentheses outward.');return num(FT,`What is the x-coordinate of the vertex of y=${a}(x ${h<0?'+':'−'} ${Math.abs(h)})² ${sign(k)}?`,h,[[-h,'This uses the sign printed inside the parentheses without reversing it.'],[k,'That is the vertical coordinate of the vertex.']],`Vertex form y=a(x−h)²+k has x-coordinate h=${h}.`)}
 if(c==='ft-inverse-graph'){const x=pick(r,-3,4),y=pick(r,-4,6);if(s==='pointEntry')return point(FT,`The graph of f contains (${x}, ${y}). Enter the point on f⁻¹.`,[y,x],'Inverse functions swap each input-output pair.');if(s==='numeric'){const m=choose(r,[2,3,-2] as const);let d=pick(r,-6,6);while(m===-2&&d%3!==0)d=pick(r,-6,6);const fixed=d/(1-m);return num(FT,`For f(x)=${m}x ${sign(d)}, f and f⁻¹ meet on y=x. What is the shared x-value?`,fixed,[[d,'The intercept alone is not the fixed point.'],[-fixed,'This reverses the fixed point sign.']],`A shared point satisfies f(x)=x, giving x=${fmt(fixed)}.`,0.000001)}return mcq(r,FT,'A function and its inverse are mirror images across which line?',['y = x','Swapping coordinates reflects every point across y=x.'],[['the x-axis','That changes output signs rather than swapping coordinates.'],['the y-axis','That changes input signs rather than swapping coordinates.'],['y = −x','That combines a swap with sign changes.']]);}
 if(c==='ft-inverse-rule'){const a=choose(r,[2,3,4] as const),d=choose(r,[-6,-5,-4,-3,-2,-1,1,2,3,4,5,6] as const);return mcq(r,FT,`What is the inverse of f(x)=${a}x ${sign(d)}?`,[`f⁻¹(x)=(x ${d<0?'+':'−'} ${Math.abs(d)})/${a}`,'Undo the addition first, then divide by the coefficient.'],[[`f⁻¹(x)=${a}x ${sign(-d)}`,'This changes the intercept but does not undo multiplication.'],[`f⁻¹(x)=(x ${d<0?'−':'+'} ${Math.abs(d)})/${a}`,'The sign used to undo the translation is reversed.'],[`f⁻¹(x)=x/${a} ${sign(d)}`,'The translation must be undone before division.']]);}
 if(c==='ft-inverse-undo'){const a=choose(r,[2,3,4] as const),d=pick(r,-5,5),x=pick(r,-4,6),y=a*x+d;if(s==='numeric')return num(FT,`Let g(x)=${a}x ${sign(d)}. Find g⁻¹(${y}).`,x,[[a*y+d,'This applies g again instead of undoing it.'],[(y+d)/a,'This uses the wrong sign when undoing the translation.']],`Undoing the operations returns the original input ${x}.`);return mcq(r,FT,`If f(${x})=${y}, what is f⁻¹(${y})?`,[String(x),'An inverse reverses the input-output pair.'],[[String(y),'That repeats the output rather than returning the input.'],[String(-x),'Inversion swaps coordinates; it does not negate them.'],[String(x+1),'The inverse returns the exact original input.']]);}
 throw new Error(`unsupported ${FT} ${form}`)}

const LG='a2-logarithms';
function logarithms(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 if(c==='lg-cob'){const base=choose(r,[2,3,5,7] as const),p=pick(r,2,5),n=base**p;if(s==='numeric')return num(LG,`Use change of base to evaluate log_${base}(${n}).`,p,[[round(Math.log10(n),6),'This computes only the numerator logarithm.'],[round(Math.log10(base),6),'This computes only the denominator logarithm.']],`log(${n})/log(${base})=${p}.`,0.000001,{kind:'logarithm-evaluate',logBase:base,logArgument:n});return mcq(r,LG,`Rewrite log_${base}(${n}) using common logarithms.`,[`log(${n}) / log(${base})`,'Change of base divides the logarithm of the argument by the logarithm of the base.'],[[`log(${base}) / log(${n})`,'The numerator and denominator are reversed.'],[`log(${n}/${base})`,'A quotient inside one logarithm is not the change-of-base formula.'],[`log(${n}) − log(${base})`,'This is a quotient property, not change of base.']]);}
 if(c==='lg-define'){const base=choose(r,[2,3,5] as const),p=pick(r,2,5),n=base**p;if(s==='numeric')return num(LG,`Evaluate log_${base}(${n}).`,p,[[base*p,'This treats the logarithm as multiplication.'],[n/base,'This divides once rather than counting repeated factors.']],`${base}^${p}=${n}, so the logarithm is ${p}.`,0,{kind:'logarithm-evaluate',logBase:base,logArgument:n});return mcq(r,LG,`Rewrite log_${base}(${n})=${p} in exponential form.`,[`${base}^${p} = ${n}`,'A logarithm names the exponent on the base.'],[[`${p}^${base} = ${n}`,'The base and exponent are reversed.'],[`${base}^${n} = ${p}`,'The argument is the exponential output, not the exponent.'],[`${n}^${p} = ${base}`,'This reverses all three roles.']]);}
 if(c==='lg-e-solve'){const k=pick(r,2,5),q=choose(r,[2,3,5] as const);if(s==='numeric')return num(LG,`Solve ${k}e^x=${k*q}. Give x to three decimals.`,Math.log(q),[[q,'This reports the exponential output instead of its logarithm.'],[Math.log(k*q),'This forgets to divide by the coefficient first.']],`Divide by ${k}, then take ln: x=ln(${q}).`,0.001);return mcq(r,LG,`Solve ${k} ln(x)=${k*q} exactly.`,[`x = e^${q}`,'Divide by the coefficient and exponentiate both sides.'],[[`x = ln(${q})`,'Taking another logarithm does not undo ln.'],[`x = ${q}e`,'Exponentiation is not multiplication by e.'],[`x = e^${k*q}`,'The coefficient must be divided out first.']]);}
 if(c==='lg-e'){const p=pick(r,2,8);if(s==='numeric')return num(LG,`Evaluate e^${p} to three decimals.`,Math.exp(p),[[Math.E*p,'This multiplies by the exponent instead of repeated exponential growth.'],[Math.pow(2,p),'This substitutes base 2 for e.']],`Using e≈2.718 gives e^${p}≈${round(Math.exp(p),3)}.`,0.001);return mcq(r,LG,'For large positive x, where does e^x grow relative to 2^x and 3^x?',['Faster than 2^x but slower than 3^x','The base e lies between 2 and 3, so its exponential growth does too.'],[['Slower than both','A larger base produces faster growth for positive x.'],['Faster than both','The base e is less than 3.'],['Exactly halfway in output','Exponential outputs are not linearly spaced by their bases.']]);}
 if(c==='lg-evaluate'){const base=choose(r,[2,3,4,5] as const),p=choose(r,[-4,-3,-2,2,3,4] as const),n=p<0?`1/${base**(-p)}`:String(base**p);if(s==='numeric')return num(LG,`Evaluate log_${base}(${n}).`,p,[[Math.abs(p),'This loses the sign required for a reciprocal power.'],[base*p,'This treats the logarithm as multiplication.']],`${base}^${p}=${n}, so the logarithm is ${p}.`,0,{kind:'logarithm-evaluate',logBase:base,logArgument:Math.pow(base,p)});return mcq(r,LG,`Evaluate log_${base}(${n}).`,[String(p),'The logarithm is the exponent that creates the argument.'],[[String(-p),'That uses the reciprocal exponent.'],[String(base),'That reports the base rather than the exponent.'],[String(base**Math.abs(p)),'That reports a power value rather than an exponent.']]);}
 if(c==='lg-exp-solve'){const base=choose(r,[2,3,4,5] as const),p=pick(r,2,4),coef=pick(r,2,5),rhs=coef*base**p;if(s==='numeric')return num(LG,`Solve ${coef}·${base}^x=${rhs}.`,p,[[rhs/coef,'That is the power value, not its exponent.'],[Math.log(rhs)/Math.log(base),'The coefficient must be divided out before taking logarithms.']],`Divide by ${coef} to get ${base}^x=${base**p}, so x=${p}.`,0,{kind:'logarithm-evaluate',logBase:base,logArgument:rhs/coef});return mcq(r,LG,`What is the exact solution of ${base}^x=${rhs}?`,[`x = log_${base}(${rhs})`,'Taking a logarithm base b undoes b raised to x.'],[[`x = ${rhs}/${base}`,'One division does not recover an exponent.'],[`x = ln(${base})/ln(${rhs})`,'The change-of-base fraction is reversed.'],[`x = ${base}^${rhs}`,'This applies another exponential instead of the inverse.']]);}
 if(c==='lg-expand-condense'){const base=choose(r,[2,3,5] as const),p=pick(r,2,5);if(s==='numeric')return num(LG,`Evaluate ${p}log_${base}(${base}) + log_${base}(${base**2}).`,p+2,[[p*base+base**2,'This evaluates logarithms as their arguments.'],[p+base**2,'The second logarithm equals its exponent, not its argument.']],`log_b(b)=1 and log_b(b²)=2, so the total is ${p+2}.`,0,{kind:'logarithm-evaluate',logBase:base,logArgument:Math.pow(base,p+2)});return mcq(r,LG,`Condense ${p}log_${base}(x) − log_${base}(y).`,[`log_${base}(x^${p}/y)`,'The power rule moves the coefficient to an exponent, and subtraction becomes division.'],[[`log_${base}(${p}x/y)`,'A coefficient outside a logarithm becomes an exponent, not a multiplier inside.'],[`log_${base}(x^${p}−y)`,'Logarithm subtraction corresponds to a quotient, not a difference.'],[`log_${base}(x/${p}y)`,'This places the coefficient in the wrong part of the quotient.']]);}
 if(c==='lg-graph')return mcq(r,LG,'Which statement is true for y=log_b(x), where b>1?',['Its domain is x>0 and it has vertical asymptote x=0.','A logarithm accepts only positive arguments and approaches the y-axis without crossing it.'],[['Its domain is all real numbers','Nonpositive logarithm arguments are not real.'],['Its horizontal asymptote is y=0','The inverse exponential has a vertical, not horizontal, asymptote.'],['It crosses the y-axis at 1','The function is not defined at x=0.']]);
 if(c==='lg-halflife'){const h=choose(r,[4,6,8,10,12] as const),n=pick(r,2,5);if(s==='numeric')return num(LG,`A quantity has half-life ${h} days. After how many days will 1/${2**n} remain?`,h*n,[[h+n,'Half-lives add in time but multiply the remaining fraction.'],[h*2**n,'The denominator is not the number of half-life intervals.']],`${n} half-lives leave 1/${2**n}, so the time is ${h*n} days.`);return mcq(r,LG,`For N=${pick(r,200,900)}(1/2)^(t/${h}), what does ${h} represent?`,['The half-life','Increasing t by this amount multiplies the quantity by one half.'],[['The starting amount','The leading coefficient is the starting amount.'],['The continuous decay rate','This model uses a half-life denominator, not an e-rate.'],['The final amount','The final amount depends on the chosen time.']]);}
 if(c==='lg-ln'){if(s==='numeric'){const n=pick(r,2,9);return num(LG,`Evaluate e^(ln ${n}).`,n,[[Math.log(n),'This stops after applying ln rather than allowing e and ln to undo each other.'],[Math.E*n,'Exponentiation by e is not multiplication by e.']],`The exponential and natural logarithm are inverse functions, so the value is ${n}.`,0,{kind:"ln-identity",n})}return mcq(r,LG,'Expand ln(5x/y).',['ln 5 + ln x − ln y','Products become sums and quotients become differences.'],[['ln 5x − ln y','The product 5x must also be separated when fully expanded.'],['ln 5 + ln x + ln y','The denominator contributes subtraction.'],['ln(5+x−y)','Logarithms do not distribute over addition and subtraction this way.']]);}
 if(c==='lg-log-solve'){const base=choose(r,[2,3,5] as const),a=pick(r,1,4),x=pick(r,3,8),left=base**a;if(s==='numeric'){const d=pick(r,2,5),q=pick(r,1,4),rhs=x+q;const A=pick(r,2,4),B=rhs-A*x;return num(LG,`Solve log_${base}(${A}x ${sign(B)}) = log_${base}(x + ${q}).`,x,[[q,'This reports the constant shift rather than solving equal arguments.'],[-x,'This reverses the solution sign.']],`Equal logs with the same valid base have equal arguments, giving x=${x}.`,0,{kind:'log-eq-linear',coefA:A,constB:B,constQ:rhs-x})}const m=pick(r,1,4),solution=2+m,product=base**3;return mcq(r,LG,`Solve log_${base}(x) + log_${base}(x−${m}) = 3. Which equation should be solved after condensing?`,[`x(x−${m}) = ${product}`,'The product rule combines the logarithms, and exponential form removes the log.'],[[`x+(x−${m}) = ${product}`,'Logarithm addition corresponds to multiplication, not addition of arguments.'],[`x(x−${m}) = 3`,'The logarithmic output 3 corresponds to base³.'],[`x/(x−${m}) = ${product}`,'A quotient would come from subtracting logarithms.']]);}
 if(c==='lg-models'){const A=pick(r,200,800),rate=choose(r,[0.02,0.03,0.05,-0.1,-0.2] as const),t=pick(r,2,5),ans=A*Math.exp(rate*t);if(s==='numeric')return num(LG,`Evaluate A(t)=${A}e^(${rate}t) at t=${t}. Round to the nearest whole number.`,Math.round(ans),[[Math.round(A*(1+rate*t)),'This uses a linear approximation instead of continuous compounding.'],[Math.round(A*Math.exp(rate)),'This applies the rate for only one time unit.']],`Substituting t=${t} gives approximately ${Math.round(ans)}.`);return mcq(r,LG,`In A(t)=${A}e^(${rate}t), what do ${A} and ${rate} represent?`,[`${A} is the initial amount and ${rate} is the continuous rate`,'At t=0 the exponential factor is 1, and the coefficient of t is the continuous rate.'],[[`${rate} is the initial amount and ${A} is the rate`,'The coefficient outside the exponential is the starting value.'],[`${A} is the final amount and ${rate} is the half-life`,'The formula gives a time-varying amount and uses a continuous rate.'],[`${A} is the base and ${rate} is the output`,'The exponential base is e.']]);}
 if(c==='lg-power'){const base=choose(r,[2,3,5] as const),p=pick(r,3,8);if(s==='numeric')return num(LG,`Evaluate log_${base}((${base**2})^${p}).`,2*p,[[p,'This ignores that the argument base is itself b².'],[base*p,'This multiplies by the logarithm base rather than the exponent 2.']],`(${base**2})^${p}=${base}^${2*p}, so the logarithm is ${2*p}.`,0,{kind:'logarithm-evaluate',logBase:base,logArgument:Math.pow(base,2*p)});return build(LG,`Expand log_${base}(x^${p}).`,[String(p),`log_${base}(x)`],[`log_${base}(${p}x)`],'The power rule moves the exponent in front of the logarithm.');}
 if(c==='lg-product'){const base=choose(r,[2,3,5] as const),p=pick(r,2,4);if(s==='numeric')return num(LG,`Evaluate log_${base}(${base}) + log_${base}(${base**p}).`,1+p,[[base+base**p,'This adds arguments rather than logarithmic exponents.'],[p,'This omits the first logarithm.']],`The values are 1 and ${p}, so the sum is ${1+p}.`,0,{kind:'logarithm-evaluate',logBase:base,logArgument:Math.pow(base,1+p)});return mcq(r,LG,`Expand log_${base}(${base**2}y).`,[`2 + log_${base}(y)`,'The product rule separates the factors, and log_b(b²)=2.'],[[`${base**2} + log_${base}(y)`,'The logarithm of b² is 2, not b².'],[`2log_${base}(y)`,'The exponent 2 belongs only to the base factor.'],[`log_${base}(${base**2}+y)`,'A product inside a log becomes a sum of logs, not a sum inside one log.']]);}
 if(c==='lg-scales'){const diff=pick(r,2,9);if(s==='numeric')return num(LG,`A pH ${diff} units lower represents how many times greater hydrogen-ion concentration?`,10**diff,[[10*diff,'Each pH unit multiplies concentration by 10, so changes compound exponentially.'],[diff,'This treats the logarithmic scale as linear.']],`${diff} logarithmic units correspond to a factor of 10^${diff}.`);return mcq(r,LG,`An earthquake magnitude increases by ${diff}. Approximately how does shaking intensity change on a base-10 logarithmic scale?`,[`It is about ${10**diff} times as large`,'Each magnitude unit corresponds to a factor of ten.'],[[`It is ${diff} times as large`,'A logarithmic scale is multiplicative, not additive.'],[`It is ${10*diff} times as large`,'Successive factors of ten multiply rather than add.'],['It does not change','A magnitude increase represents a substantial multiplicative change.']]);}
 throw new Error(`unsupported ${LG} ${form}`)}

const PF='a2-polynomials';
function polynomials(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 if(c==='pf-anatomy'){const n=pick(r,3,cap(b,5,9,11));if(s==='numeric')return num(PF,`What is the maximum possible number of turning points of a degree-${n} polynomial?`,n-1,[[n,'The maximum is one less than the degree.'],[n+1,'A polynomial cannot turn more times than degree minus one.']],`A degree-${n} polynomial has at most ${n-1} turning points.`,0,{kind:'pf-anatomy',n});return mcq(r,PF,'Which expression is not a polynomial function?',['f(x)=3/x + 2','A variable in a denominator creates a negative exponent.'],[['f(x)=2x³−5x+1','All exponents are nonnegative integers.'],['f(x)=7','A constant is a degree-zero polynomial.'],['f(x)=x⁴+√2x','Irrational coefficients are allowed in polynomials.']]);}
 if(c==='pf-build'){const a=pick(r,-4,-1),d=pick(r,1,5);if(s==='numeric'){const L=pick(r,8,14),W=pick(r,6,L-1),x=pick(r,1,Math.floor(W/2)-1),ans=x*(L-2*x)*(W-2*x);return num(PF,`An open box has volume V(x)=x(${L}−2x)(${W}−2x). Find V(${x}).`,ans,[[x*L*W,'This does not subtract the corner cuts from the base dimensions.'],[(L-2*x)*(W-2*x),'This omits the box height x.']],`The dimensions are ${x}, ${L-2*x}, and ${W-2*x}, so the volume is ${ans}.`,0,{kind:'pf-volume-eval',L,W,x})}return mcq(r,PF,`A monic polynomial crosses at x=${a} and bounces at x=${d}. Which has the smallest possible degree?`,[`(x ${a<0?'+':'−'} ${Math.abs(a)})(x−${d})²`,'Crossing needs odd multiplicity and bouncing needs even multiplicity.'],[[`(x ${a<0?'+':'−'} ${Math.abs(a)})(x−${d})`,'A simple zero crosses instead of bouncing.'],[`(x ${a<0?'+':'−'} ${Math.abs(a)})²(x−${d})`,'This assigns the bounce and crossing to the wrong zeros.'],[`(x ${a<0?'+':'−'} ${Math.abs(a)})²(x−${d})²`,'This bounces at both zeros and has unnecessarily high degree.']]);}
 if(c==='pf-cubes'){const a=pick(r,2,9),cube=a**3;if(s==='buildExpression')return build(PF,`Factor x³ + ${cube}.`,[`(x + ${a})`,`(x² − ${a}x + ${a*a})`],[`(x + ${a})³`],'The sum-of-cubes identity is a³+b³=(a+b)(a²−ab+b²).');if(s==='numeric')return num(PF,`Find the only real zero of x³ + ${cube}=0.`,-a,[[a,'This misses the negative sign required to cancel a positive cube.'],[-cube,'This reports the constant rather than its cube root.']],`x³=−${cube}, so x=−${a}.`);return mcq(r,PF,`How many real zeros does x³ + ${cube} have?`,['1','A strictly increasing cubic crosses the x-axis once.'],[['0','Odd-degree real polynomials have at least one real zero.'],['2','The remaining quadratic factor has negative discriminant.'],['3','This particular sum of cubes has only one real factor.']]);}
 if(c==='pf-div-theorems'){const roots=[pick(r,-5,-2),pick(r,-1,2),pick(r,3,6)];while(roots[1]===0)roots[1]=pick(r,-1,2);if(s==='buildExpression')return build(PF,`Build all zeros of f(x)=(x ${roots[0]<0?'+':'−'} ${Math.abs(roots[0])})(x ${roots[1]<0?'+':'−'} ${Math.abs(roots[1])})(x−${roots[2]}).`,roots.map(x=>`x = ${x}`),['x = 0'],'Each linear factor equals zero at its corresponding root.');if(s==='numeric'){const root=choose(r,roots);return num(PF,`A polynomial has factor (x ${root<0?'+':'−'} ${Math.abs(root)}). What remainder results when dividing by that factor?`,0,[[root,'A verified factor produces zero remainder, not the root itself.'],[1,'The remainder theorem gives f(root)=0.']],`The factor theorem guarantees remainder 0.`)}return mcq(r,PF,'If f(5)=0, what must be true when f(x) is divided by x−5?',['The remainder is 0','The remainder theorem says the remainder equals f(5).'],[['The quotient is 0','The quotient generally has lower degree and need not vanish.'],['The remainder is 5','The input is not the remainder.'],['The degree increases by 1','Polynomial division lowers the degree.']]);}
 if(c==='pf-end-behavior'){const even=r()<0.5,neg=r()<0.5,n=even?choose(r,[2,4,6] as const):choose(r,[3,5,7] as const);const behavior=even?(neg?'falls left and falls right':'rises left and rises right'):(neg?'rises left and falls right':'falls left and rises right');if(s==='buildExpression')return build(PF,`Build the end behavior of f(x)=${neg?'−':''}x^${n}+lower-degree terms.`,[behavior],[even?'opposite ends':'same ends'],'Degree parity and leading sign determine the two end directions.');return mcq(r,PF,`Which end behavior matches a ${neg?'negative':'positive'} leading coefficient and ${even?'even':'odd'} degree?`,[behavior,'The leading term controls the far-left and far-right behavior.'],[['rises left and rises right','Check both degree parity and leading sign.'],['falls left and falls right','Check both degree parity and leading sign.'],['rises left and falls right','Check whether the ends should match or oppose.']]);}
 if(c==='pf-factor-thm'){const a=pick(r,-4,5)||2,p=pick(r,2,4),f=a**3+p*a,constant=-f;if(s==='numeric')return num(PF,`Find the remainder when f(x)=x³+${p}x${sign(constant)} is divided by x−${a}.`,0,[[a,'The divisor zero is the input, not the remainder.'],[f,'This omits the constant term from evaluation.']],`Substituting x=${a} gives zero, so x−${a} is a factor.`);return mcq(r,PF,`If f(${a})=0, which factor is guaranteed?`,[`x ${a<0?'+':'−'} ${Math.abs(a)}`,'A zero at a corresponds to factor x−a.'],[[`x ${a<0?'−':'+'} ${Math.abs(a)}`,'This uses the opposite root.'],[`x−f(${a})`,'The function value is zero and does not name the root.'],[`x²−${a}`,'The factor theorem guarantees a linear factor.']]);}
 if(c==='pf-grouping'){const a=pick(r,2,5),b1=pick(r,1,4),q=pick(r,1,5);if(s==='buildExpression')return build(PF,`Factor x³+${a}x²+${xterm(b1)}+${a*b1} by grouping.`,[`(x + ${a})`,`(x² + ${b1})`],[`(x + ${b1})(x² + ${a})`],'Factoring each pair reveals the shared binomial factor.');return mcq(r,PF,`After grouping, the two groups become x²(x+${a}) + ${b1}(x+${q}). What conclusion is justified?`,['No common binomial factor has appeared yet','The parenthetical factors differ, so another step or a different grouping is needed.'],[[`Factor out x+${a}`,'Only the first group contains that binomial.'],[`Factor out x+${q}`,'Only the second group contains that binomial.'],['The polynomial is fully factored','A sum remains and the groups do not share a factor.']]);}
 if(c==='pf-leading-term'){const n=pick(r,3,6),coef=choose(r,[-5,-3,2,4] as const),x=pick(r,5,10),low=pick(r,1,5);if(s==='numeric')return num(PF,`Evaluate f(${x}) for f(x)=${xterm(coef,n)} ${signedX(low)}.`,coef*x**n+low*x,[[coef*x**n,'This omits the lower-degree term.'],[coef*x*n+low*x,'This treats the exponent as multiplication.']],`Substitute ${x} into every term and add the results.`);return mcq(r,PF,`Which term controls the end behavior of f(x)=${xterm(coef,n)} + 100x² − 7?`,[xterm(coef,n),'The highest-degree nonzero term dominates for large |x|.'],[['100x²','Its coefficient is large, but its degree is lower.'],['−7','A constant does not control far-end growth.'],['All terms contribute equally','Lower-degree terms become negligible relative to the leading term.']]);}
 if(c==='pf-long-div'){const a=pick(r,1,5),b1=pick(r,1,6),sum=a+b1,prod=a*b1;if(s==='buildExpression')return build(PF,`Divide x²+${sum}x+${prod} by x+${a}.`,[`x + ${b1}`],[`x + ${a}`],'The numerator factors as (x+a)(x+b).');if(s==='numeric')return num(PF,`Find the remainder when x²+${sum}x+${prod+1} is divided by x+${a}.`,1,[[0,'That would be the remainder only if x+a were an exact factor.'],[a,'The divisor constant is not the remainder.']],`Evaluate at x=−${a}; the value is 1.`,0,{kind:'pf-long-div',a,sum,prodPlus1:prod+1});return mcq(r,PF,'What is the fastest complete check of a polynomial division result?',['Verify dividend = divisor·quotient + remainder','This identity checks every coefficient and the remainder at once.'],[['Check only the leading terms','Matching leading terms does not verify lower coefficients.'],['Substitute x=0 only','One input cannot prove two polynomials are identical.'],['Differentiate both sides','Differentiation can lose constant information.']]);}
 if(c==='pf-multiplicity'){const m1=choose(r,[2,3,4] as const),m2=choose(r,[1,2,3] as const);if(s==='numeric')return num(PF,`What is the degree of f(x)=(x+1)^${m1}(x−2)^${m2}?`,m1+m2,[[Math.max(m1,m2),'Degrees of multiplied factors add.'],[m1*m2,'Multiplicities add rather than multiply.']],`The total degree is ${m1}+${m2}=${m1+m2}.`);return mcq(r,PF,`At a zero of multiplicity ${m1}, what does a polynomial graph do?`,[m1%2?'It crosses the x-axis':'It touches and turns','Odd multiplicity changes sign; even multiplicity preserves sign.'],[[m1%2?'It touches and turns':'It crosses the x-axis','This reverses the parity rule.'],['It has a vertical asymptote','Polynomial graphs have no vertical asymptotes.'],['It disappears from the graph','Every real zero appears as an x-intercept.']]);}
 if(c==='pf-quad-form'){const a=pick(r,1,4),b1=pick(r,a+1,6);const roots=[-Math.sqrt(a),Math.sqrt(a),-Math.sqrt(b1),Math.sqrt(b1)];if(s==='numeric')return num(PF,`How many distinct real zeros does x⁴−${a+b1}x²+${a*b1} have?`,4,[[2,'This counts the y=x² solutions but not both square roots of each.'],[0,'Both quadratic-in-form roots are positive.']],`Let u=x²; u=${a} or ${b1}, giving four real x-values.`);return build(PF,`Build all zeros of x⁴−${a+b1}x²+${a*b1}=0.`,roots.map(v=>`x = ${fmt(v)}`),['x = 0'],'Substitute u=x², solve the quadratic in u, then take both square roots.');}
 if(c==='pf-sketch'){const a=pick(r,-4,-1),d=pick(r,1,5);if(s==='buildExpression')return build(PF,`Describe f(x)=(x ${a<0?'+':'−'} ${Math.abs(a)})(x−${d})² at its zeros.`,[`cross at x=${a}`,`bounce at x=${d}`],[`bounce at x=${a}`],'Odd multiplicity crosses and even multiplicity bounces.');return mcq(r,PF,`For g(x)=(x−${d})(x+${Math.abs(a)})x², what happens at x=0?`,['The graph touches the axis and turns','The zero at 0 has even multiplicity 2.'],[['The graph crosses the axis','Crossing requires odd multiplicity.'],['There is a vertical asymptote','A polynomial is defined at zero.'],['The graph has no intercept there','The factor x² makes zero a root.']]);}
 if(c==='pf-synthetic'){const root=pick(r,-4,5)||2,a=pick(r,1,5),b1=pick(r,-6,6),rem=pick(r,-5,5);if(s==='buildExpression')return build(PF,`Synthetic division by x−${root} gives bottom row 1, ${a}, ${b1}, | ${rem}. Build the quotient.`,['x²',signedX(a),`${b1<0?'−':'+'} ${Math.abs(b1)}`],[`remainder ${rem}`],'All entries before the bar are quotient coefficients.');if(s==='numeric')return num(PF,`A synthetic-division bottom row is 1, ${a}, | ${rem}. What is the remainder?`,rem,[[a,'That is the last quotient coefficient before the bar.'],[root,'That is the synthetic input, not the remainder.']],`The value after the bar is the remainder ${rem}.`,0,{kind:'pf-synthetic-echo',rem});return mcq(r,PF,`What number goes in the synthetic-division box for divisor x ${root<0?'+':'−'} ${Math.abs(root)}?`,[String(root),'Synthetic division uses the zero of the divisor.'],[[String(-root),'This is the printed constant, not the divisor zero.'],['0','Zero is used only for divisor x.'],['1','The leading coefficient of the divisor is not the box value.']]);}
 if(c==='pf-turning'){const turns=pick(r,2,9);if(s==='numeric')return num(PF,`A polynomial graph has exactly ${turns} turning points. What is the smallest possible degree?`,turns+1,[[turns,'A degree-n polynomial has at most n−1 turns.'],[turns+2,'This degree is possible but not the smallest.']],`At least degree ${turns+1} is required for ${turns} turns.`,0,{kind:'pf-turning',turns});return mcq(r,PF,'Which number of turning points is possible for a degree-5 polynomial?',['4','A degree-5 polynomial can have at most 4 turning points.'],[['5','That exceeds degree minus one.'],['6','That exceeds degree minus one.'],['8','That exceeds degree minus one.']]);}
 if(c==='pf-zeros'){const roots=[pick(r,-5,-2),pick(r,-1,2),pick(r,3,6)];while(roots[1]===0)roots[1]=pick(r,-1,2);if(s==='numeric')return num(PF,`How many x-intercepts does f(x)=(x−${roots[0]})(x−${roots[1]})(x−${roots[2]}) have?`,3,[[2,'Each distinct real linear factor contributes an intercept.'],[1,'The three factors have distinct roots.']],`The three distinct real roots produce three x-intercepts.`);return build(PF,`Build the zeros of f(x)=(x−${roots[0]})(x−${roots[1]})(x−${roots[2]}).`,roots.map(v=>`x = ${v}`),['x = 0'],'Set each linear factor equal to zero.');}
 throw new Error(`unsupported ${PF} ${form}`)}

const RE='a2-radicals';
function radicals(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 if(c==='re-both-sides'){const x=pick(r,2,8),a=pick(r,1,4),rhs=Math.sqrt(x*x-a);if(s==='numeric'){const k=pick(r,2,5),root=pick(r,2,6),C=root**3-k*x;return num(RE,`Solve ∛(${k}x ${sign(C)})=${root}.`,x,[[root,'This reports the cube-root output rather than solving for x.'],[(root**3+C)/k,'This uses the wrong sign when isolating the variable term.']],`Cube both sides and solve the resulting linear equation to get x=${x}.`,0,{kind:'radical-equation',rootIndex:3,insideCoef:k,insideConst:C,rhs:root})}return mcq(r,RE,`Solve √(x²−${a})=${fmt(rhs)}. Which solution description is correct?`,[`x = ±${x}`,'Squaring gives x², so both signs must be checked.'],[[`x = ${x}`,'This omits the negative solution.'],[`x = −${x}`,'This omits the positive solution.'],['No real solution','The chosen right side produces a positive x² value.']]);}
 if(c==='re-conjugates'){const a=pick(r,2,7),d=pick(r,2,6);if(s==='numeric')return num(RE,`Evaluate (√${a} + √${d})(√${a} − √${d}).`,a-d,[[a+d,'The middle terms cancel, leaving a difference rather than a sum.'],[Math.sqrt(a-d),'The product is already a difference of squares.']],`Conjugates multiply to ${a}−${d}=${a-d}.`,0,{kind:'conjugate-product',left:a,right:d});return build(RE,`Rationalize 1/(√${a}+√${d}).`,[`(√${a} − √${d})`,`/ (${a-d})`],[`(√${a} + √${d}) / (${a+d})`],'Multiply by the conjugate so the denominator becomes a difference of squares.');}
 if(c==='re-convert'){const m=pick(r,2,5),n=choose(r,[3,5,7] as const);if(s==='numeric'){const base=pick(r,2,4)**n;return num(RE,`Evaluate ${base}^(${m}/${n}).`,Math.round(base**(m/n)),[[Math.round(base**(n/m)),'The numerator and denominator of the exponent are reversed.'],[Math.round(base*m/n),'A rational exponent is not ordinary multiplication.']],`Take the ${rootWord(n)} root, then raise to power ${m}.`,0,{kind:'rational-exponent',base,exponent:m,rootIndex:n})}if(s==='buildExpression')return build(RE,`Write x^(${m}/${n}) as a radical.`,[`ⁿ√(x^${m})`],[`ᵐ√(x^${n})`],'The denominator names the root and the numerator names the power.');return mcq(r,RE,`Which exponent form equals the ${rootWord(n)} root of x^${m}?`,[`x^(${m}/${n})`,'The root index becomes the denominator of the exponent.'],[[`x^(${n}/${m})`,'The power and root index are reversed.'],[`x^(${m*n})`,'A root divides an exponent rather than multiplying it.'],[`x^(${m}-${n})`,'Roots do not subtract exponents.']]);}
 if(c==='re-domains'){const a=pick(r,2,6),h=pick(r,-5,5),C=-a*h;if(s==='numeric')return num(RE,`The domain of f(x)=√(${a}x ${sign(C)}) is x≥q. Find q.`,h,[[-h,'This reverses the inequality boundary sign.'],[C,'That is the radicand constant, not the input boundary.']],`Require ${a}x ${sign(C)}≥0, giving x≥${h}.`,0,{kind:'radical-equation',rootIndex:2,insideCoef:a,insideConst:C,rhs:0});if(s==='buildExpression')return build(RE,`Build the domain of f(x)=√(${a}x ${sign(C)}).`,[`x ≥ ${h}`],[`x ≤ ${h}`],'An even-root radicand must be nonnegative.');return mcq(r,RE,`Where does y=√(x ${h<0?'+':'−'} ${Math.abs(h)}) begin?`,[`(${h}, 0)`,'The graph starts where the radicand first equals zero.'],[[`(${-h}, 0)`,'The horizontal shift sign is reversed inside the radicand.'],[`(0, ${h})`,'This swaps the horizontal and vertical roles.'],['It has no endpoint','A square-root graph has a domain boundary.']]);}
 if(c==='re-extraneous'){const sol=pick(r,3,10),k=sol*sol-sol;const other=1-sol;if(s==='numeric')return num(RE,`Solve √(x+${k})=x. Give the valid solution.`,sol,[[other,'This algebraic candidate fails the original equation or sign condition.'],[k,'That is the radicand shift, not the solution.']],`Squaring gives two candidates, and substitution keeps only x=${sol}.`,0,{kind:'radical-extraneous',insideConst:k,rhsShift:0});if(s==='buildExpression')return build(RE,`Squaring √(x+${k})=x gives candidates ${sol} and ${other}. Build the checked solution set.`,[`x = ${sol}`],[`x = ${other}`],'Only the candidate that satisfies the original radical equation survives.');return mcq(r,RE,'Why can squaring a radical equation create an extraneous solution?',['Squaring loses sign information and is not reversible without checking.','Different signed expressions can have the same square.'],[['Squaring changes every coefficient randomly','The change is systematic, not random.'],['Radicals can never be squared','Squaring is valid, but the resulting implication may not be reversible.'],['Every quadratic has a false root','Extraneous roots arise from the transformation and domain conditions, not every quadratic.']]);}
 if(c==='re-models'){const h=choose(r,[16,36,64,100,144,196,256,324,400,484,576] as const);if(s==='numeric')return num(RE,`A model gives t=√h/4. Find t when h=${h}.`,Math.sqrt(h)/4,[[Math.sqrt(h/4),'The division occurs after taking the square root.'],[h/4,'This omits the square root.']],`√${h}=${Math.sqrt(h)}, then divide by 4.`,0,{kind:'scaled-root',radicand:h,divisor:4});return mcq(r,RE,'In a model s=√(24d), what happens when d is multiplied by 4?',['s is multiplied by 2','The square root turns a factor of 4 into a factor of 2.'],[['s is multiplied by 4','That would be a linear relationship.'],['s is multiplied by 16','The square-root model grows more slowly, not faster.'],['s does not change','The radicand changes with d.']]);}
 if(c==='re-plusminus'){const a=pick(r,2,5),n=choose(r,[3,5] as const),rhs=a*a;if(s==='numeric')return num(RE,`Solve x^(2/${n})=${rhs}. Give the positive solution.`,a**n,[[a*a,'This reports the right side rather than undoing the exponent.'],[a,'This takes only a square root and ignores the denominator exponent.']],`Raise both sides to ${n}/2; the positive magnitude is ${a**n}.`,0,{kind:'rational-exponent-solve',p:2,q:n,rhs});if(s==='buildExpression')return build(RE,`Build the real solutions of x^(2/${n})=${rhs}.`,[`x = ${a**n}`,'or',`x = −${a**n}`],[`x = ${a}`],'An even numerator gives two real signs after undoing the power.');return mcq(r,RE,`How many real solutions does x^(2/${n})=${rhs} have?`,['2','Both positive and negative inputs have the same even-power value.'],[['1','This omits the negative solution.'],['0','The positive right side is attainable.'],['4','Only the two opposite real values work.']]);}
 if(c==='re-power-solve'){const root=pick(r,2,6),p=choose(r,[3,5] as const),q=choose(r,[2,3] as const),rhs=root**p;return num(RE,`Solve x^(${p}/${q})=${rhs}. Give the positive real solution.`,root**q,[[root**p,'This repeats the right side instead of applying the reciprocal exponent.'],[root,'This extracts only one root step.']],`Raise both sides to ${q}/${p}, giving x=${root**q}.`,0,{kind:'rational-exponent-solve',p,q,rhs})}
 if(c==='re-products'){const a=pick(r,2,12);if(s==='numeric')return num(RE,`Evaluate (√${a})².`,a,[[Math.sqrt(a),'This stops before squaring undoes the square root.'],[a*a,'The original radicand is not squared again.']],`Squaring and square root undo each other for a nonnegative radicand.`,0,{kind:'radical-square',radicand:a});return build(RE,`Expand (1+√${a})².`,['1',`+ 2√${a}`,`+ ${a}`],[`+ √${a}`],'Use (u+v)²=u²+2uv+v².');}
 if(c==='re-rationalize'){const a=choose(r,[2,3,5,6,7] as const),k=pick(r,2,8);return build(RE,`Rationalize ${k}/√${a}.`,[`${k}√${a}`,`/ ${a}`],[`${k}/${a}`],'Multiply numerator and denominator by √a.');}
 if(c==='re-rules'){const p=pick(r,2,6),q=choose(r,[3,5] as const);if(s==='numeric'){const base=pick(r,2,5);return num(RE,`Evaluate (${base}^(${p}/${q}))^(${q}/${p}).`,base,[[base**(p/q*q/p+1),'The exponents multiply to 1, not to 2.'],[1,'A nonzero base raised to the first power remains the base.']],`Multiplying reciprocal exponents gives exponent 1.`,0,{kind:'plain-constant',value:base,label:'the base'})}return mcq(r,RE,`Simplify (x^(${p}/${q}))^(${q}/${p}).`,['x','The power-of-a-power rule multiplies the reciprocal exponents to 1.'],[['x²','The reciprocal exponents do not add.'],['1','x to the first power is x, not 1.'],[`x^(${p+q}/${p*q})`,'Exponents multiply in a power of a power.']]);}
 if(c==='re-solve'){const sol=pick(r,3,8),a=pick(r,1,Math.min(4,sol-2)),C=(sol-a)**2-sol;if(s==='numeric')return num(RE,`Solve √(${binomial('x',C)})=x−${a}.`,sol,[[a,'That is the horizontal shift, not the solution.'],[a-sol,'This reverses the valid sign.']],`Square both sides, solve, and check to keep x=${sol}.`,0,{kind:'radical-extraneous',insideConst:C,rhsShift:a});return mcq(r,RE,'What final step is mandatory after solving a radical equation by squaring?',['Check every candidate in the original equation','Squaring may introduce candidates that violate the original sign or domain conditions.'],[['Accept every quadratic root','Some candidates can be extraneous.'],['Square the answers again','Further squaring does not verify the original equation.'],['Discard all negative values automatically','A negative value may be valid depending on the original equation.']]);}
 if(c==='re-sqrt-fn'){const h=pick(r,-4,5),k=pick(r,-5,5);if(s==='numeric')return num(RE,`What is the y-coordinate of the starting point of y=√(x ${h<0?'+':'−'} ${Math.abs(h)}) ${sign(k)}?`,k,[[-k,'This reverses the vertical shift sign.'],[h,'That is the horizontal coordinate.']],`The parent endpoint (0,0) shifts to (${h},${k}).`,0,{kind:'plain-constant',value:k,label:'the vertical shift'});return mcq(r,RE,`What is the starting point of y=√(x ${h<0?'+':'−'} ${Math.abs(h)}) ${sign(k)}?`,[`(${h}, ${k})`,'The graph begins where the radicand is zero, then applies the vertical shift.'],[[`(${-h}, ${k})`,'The inside shift sign must be reversed.'],[`(${h}, ${-k})`,'The outside shift keeps its printed sign.'],['(0,0)','The transformations move the parent endpoint.']]);}
 if(c==='re-transform'){const h=pick(r,-4,5),k=pick(r,-5,5),a=choose(r,[-2,-1,2] as const);if(s==='numeric')return num(RE,`For y=${a}√(x ${h<0?'+':'−'} ${Math.abs(h)}) ${sign(k)}, what is the x-coordinate of the endpoint?`,h,[[-h,'This uses the sign printed inside without reversing it.'],[k,'That is the vertical coordinate.']],`Set the radicand to zero; the endpoint begins at x=${h}.`,0,{kind:'plain-constant',value:h,label:'the horizontal endpoint'});return build(RE,`Build the endpoint of y=${a}√(x ${h<0?'+':'−'} ${Math.abs(h)}) ${sign(k)}.`,[`(${h}, ${k})`],[`(${-h}, ${k})`],'Horizontal and vertical shifts move the parent endpoint to (h,k).');}
 if(c==='re-var-radicals'){const a=pick(r,2,12),b1=pick(r,1,6);return build(RE,`Simplify √(${a*a}x²y) for x≥0.`,[`${a}x√y`],[`${a*a}x√y`],'Perfect-square factors leave the radical as their positive square roots.');}
 throw new Error(`unsupported ${RE} ${form}`)}

const RF='a2-rationals';
function rationals(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 if(c==='rf-divide'){const a=pick(r,2,6),d=pick(r,1,5);if(s==='buildExpression')return build(RF,`Divide (x/${a}) ÷ ((x+${d})/${a}).`,['x',`/ (x + ${d})`],[`(x + ${d}) / x`],'Multiply by the reciprocal of the divisor and cancel the common constant.');return mcq(r,RF,'What is the first algebraic move when dividing rational expressions?',['Multiply by the reciprocal of the divisor','Division by a nonzero expression is multiplication by its reciprocal.'],[['Add the denominators','Division does not use the common-denominator rule.'],['Cancel across the division sign immediately','The quotient must first be rewritten as multiplication.'],['Square both expressions','Squaring changes the value.']]);}
 if(c==='rf-equations'){const x=pick(r,4,9),a=pick(r,1,3),k=x-a; if(s==='numeric')return num(RF,`Solve 1/(x−${a}) = 1/${k}.`,x,[[a,'This is excluded because it makes the denominator zero.'],[k,'This reports x−a rather than x.']],`Equal nonzero reciprocals have equal denominators, so x−${a}=${k} and x=${x}.`);if(s==='buildExpression')return build(RF,`Build the restriction for 1/(x−${a}) = 1/${k}.`,[`x ≠ ${a}`],[`x = ${a}`],'A denominator cannot equal zero.');return mcq(r,RF,'Why must solutions of rational equations be checked in the original equation?',['Clearing denominators can produce excluded or extraneous values','Multiplication by expressions involving the variable requires checking denominator restrictions.'],[['Every rational equation has two answers','The number of solutions varies.'],['Fractions cannot be simplified safely','Valid factor cancellation is allowed with restrictions.'],['Only negative answers can fail','Any excluded denominator value can fail.']]);}
 if(c==='rf-excluded'){const a=pick(r,-5,-1),d=pick(r,1,6),coef=pick(r,2,5);if(s==='numeric')return num(RF,`What value is excluded from (x²+1)/(${coef}x−${coef*d})?`,d,[[0,'The denominator is not zero at x=0 unless the constant vanishes.'],[-d,'This reverses the sign when solving the denominator equation.']],`Set the denominator equal to zero to obtain x=${d}.`);return mcq(r,RF,`What values are excluded from (x+1)/((x−${a})(x−${d}))?`,[`${a} and ${d}`,'Each denominator factor must stay nonzero.'],[[`${-a} and ${-d}`,'The factor zeros use the opposite sign from the printed constants.'],[`${a} only`,'Both denominator factors create restrictions.'],['No values','A rational expression is not defined where its denominator is zero.']]);}
 if(c==='rf-ha'){const a=pick(r,2,8),d=pick(r,2,7);if(s==='numeric')return num(RF,`Find the horizontal asymptote value of f(x)=(${a}x+1)/(${d}x−3).`,a/d,[[a,'This uses only the numerator leading coefficient.'],[d,'This uses only the denominator leading coefficient.']],`Equal degrees give the ratio of leading coefficients, ${a}/${d}.`,0.000001,{kind:'rf-ha',a,d});return mcq(r,RF,`What is the horizontal asymptote of f(x)=(${a}x²−x)/(${d}x²+8)?`,[`y = ${fracStr(a,d)}`,'Equal polynomial degrees use the leading-coefficient ratio.'],[[`x = ${fracStr(a,d)}`,'A horizontal asymptote is written as y equals a constant.'],['y = 0','That applies when the numerator degree is lower.'],['There is no horizontal asymptote','Equal degrees always give a finite leading-coefficient ratio.']]);}
 if(c==='rf-holes'){const h=pick(r,-5,5)||2,a=choose(r,[-4,-3,-2,-1,1,2,3,4].filter(v=>v!==h));return mcq(r,RF,`Where is the hole of g(x)=(x−${h})/((x−${h})(x−${a}))?`,[`(${h}, ${fracStr(1,h-a)})`,'Cancel the common factor for the simplified rule, then evaluate that rule at the excluded input.'],[[`(${a}, 0)`,'This uses the remaining vertical asymptote rather than the canceled factor.'],[`(${h}, 0)`,'The hole y-coordinate comes from the simplified function, not the canceled numerator alone.'],[`x = ${h}`,'A hole is a missing point with both coordinates.']]);}
 if(c==='rf-lcd'){const a=pick(r,2,6),d=pick(r,1,5);return build(RF,`Build the LCD of 1/((x−${a})(x+${d})) and 1/(x+${d}).`,[`(x − ${a})`,`(x + ${d})`],[`(x + ${d})²`],'The LCD contains each distinct denominator factor to its greatest required power.');}
 if(c==='rf-like-denoms'){const a=pick(r,2,7),d=pick(r,1,6),k=pick(r,1,a-1);if(s==='numeric')return num(RF,`Simplify (${a}x)/(x−${d}) − (${xterm(a-k)}+${k*d})/(x−${d}). What constant remains?`,k,[[0,'The numerators do not cancel completely.'],[a,'This uses the first coefficient rather than factoring the numerator difference.']],`The numerator difference is ${k}(x−${d}), so the quotient is ${k}.`,0,{kind:'rf-like-denoms',coef1:a,coef2:a-k});return build(RF,`Subtract (${a}x)/(x+${d}) − (${xterm(k)}−3)/(x+${d}).`,[`${xterm(a-k)} + 3`,`/ (x + ${d})`],[`${xterm(a-k)} − 3 / (x + ${d})`],'With equal denominators, subtract the entire second numerator.');}
 if(c==='rf-mixed'){const a=pick(r,1,9);if(s==='buildExpression')return build(RF,`Simplify (x²−${a*a})/x · x/(x+${a}) ÷ (x−${a})/2.`,['2'],[`2(x−${a})`],'Factor, multiply by the reciprocal, and cancel only factors.');return mcq(r,RF,`For (x²−${a*a})/x · x/(x+${a}) ÷ (x−${a})/2, which values are excluded?`,[`x ≠ 0, ${-a}, ${a}`,'Original denominators and the divisor numerator must all remain nonzero.'],[[`x ≠ 0, ${-a}`,'Division also excludes a zero value of x−a.'],[`x ≠ ${a}`,'The original x and x+a denominators also restrict the domain.'],['No exclusions after simplification','Canceled factors still create holes or forbidden inputs.']]);}
 if(c==='rf-multiply'){const a=pick(r,2,6),d=pick(r,1,5);if(s==='buildExpression')return build(RF,`Multiply (x²−${a*a})/(x+${d}) · (x+${d})/(x−${a}).`,[`x + ${a}`],[`x − ${a}`],'Factor the difference of squares and cancel common factors.');return mcq(r,RF,`In 2x/(x+${d}) · (x+${d})/6 = x/3, which restriction remains?`,[`x ≠ ${-d}`,'The original denominator x+d cannot be zero even after cancellation.'],[[`x ≠ ${d}`,'The factor x+d is zero at −d.'],['x ≠ 0','The variable is in a numerator, not an original denominator.'],['There is no restriction','Cancellation does not restore excluded inputs.']]);}
 if(c==='rf-opposite'){const a=pick(r,2,9);if(s==='buildExpression')return build(RF,`Simplify (${a*a}−x²)/(x−${a}).`,[`−(x + ${a})`],[`x + ${a}`],'Reverse the difference-of-squares factor to expose a factor of −(x−a).');return mcq(r,RF,`Simplify (${a}−x)/(x−${a}).`,['−1','The numerator is the opposite of the denominator.'],[['1','The factors differ by a negative sign.'],['0','The numerator is not identically zero.'],['x','The quotient of opposite equal factors is constant.']]);}
 if(c==='rf-reciprocal')return mcq(r,RF,'Why can f(x)=1/x never equal 0?',['A nonzero numerator divided by a finite nonzero denominator cannot produce zero.','A rational quotient is zero only when its numerator is zero.'],[['Because x can never be negative','Negative inputs are allowed.'],['Because the graph has no y-intercept','That is true but does not explain why the output cannot be zero.'],['Because every quotient is positive','The reciprocal is negative for negative x.']]);
 if(c==='rf-simplify'){const a=pick(r,2,6),d=pick(r,1,5);if(s==='numeric')return num(RF,`Simplify (${a}x+${a*d})/(x+${d}). What constant remains?`,a,[[a*d,'This is the numerator constant, not the factored quotient.'],[d,'This is the canceled shift, not the scale factor.']],`Factor ${a}(x+${d}) and cancel to obtain ${a}.`);if(s==='buildExpression')return build(RF,`Simplify (x²${a-d===0?'':` ${signedX(a-d)}`} − ${a*d})/((x−${d})(x+${a})).`,['1'],[`x + ${a}`],'The numerator factors into the same two denominator factors.');return mcq(r,RF,`Can (x+${a})/(x+${d}) be simplified by canceling x?`,['No; x is part of sums, not a common factor','Cancellation applies to multiplicative factors, not terms within addition.'],[['Yes; the result is a/d','Terms may not be canceled across addition.'],['Yes; the result is 1','The numerator and denominator are not identical.'],['Only when x is positive','Sign does not turn terms into common factors.']]);}
 if(c==='rf-unlike'){const a=pick(r,2,6),d=pick(r,1,5);return build(RF,`Subtract ${a}/(x+${d}) − 2/x.`,[`${a-2===0?`−${2*d}`:`${xterm(a-2)} − ${2*d}`}`,`/ (x(x + ${d}))`],[`${a-2}/(x+${d})`],'Use the common denominator x(x+d) and subtract the complete numerators.');}
 if(c==='rf-variation'){const x1=pick(r,2,6),y1=pick(r,4,12),x2=pick(r,2,8);const k=x1*y1,ans=k/x2;if(s==='numeric')return num(RF,`y varies inversely with x. If y=${y1} when x=${x1}, find y when x=${x2}.`,ans,[[y1*x2/x1,'This uses direct variation instead of inverse variation.'],[k,'This reports the variation constant rather than the new output.']],`The constant is k=xy=${k}; then y=${k}/${x2}.`,0.000001,{kind:'rf-variation-inverse',x1,y1,x2});return mcq(r,RF,'Which pair naturally varies inversely?',['Speed and travel time for a fixed distance','For fixed distance, increasing speed decreases time so their product stays constant.'],[['Hours worked and total pay at fixed rate','These vary directly.'],['Side length and perimeter of a square','These vary directly.'],['Number of items and total mass per item fixed','These vary directly.']]);}
 if(c==='rf-work'){const a=pick(r,3,8),b1=pick(r,a+1,12),rate=1/a+1/b1,ans=1/rate;if(s==='numeric')return num(RF,`One machine finishes a job in ${a} hours and another in ${b1} hours. How long together?`,ans,[[a+b1,'Work times do not add; rates add.'],[(a+b1)/2,'The arithmetic mean ignores different rates.']],`Add rates 1/${a}+1/${b1}, then invert the combined rate.`,0.000001,{kind:'rf-work',a,b1});return mcq(r,RF,`A pump fills a tank in ${a} hours. What fraction does it fill per hour?`,[`1/${a}`,'A complete job divided evenly across a hours gives rate 1/a job per hour.'],[[String(a),'That is the time, not the hourly fraction.'],[`1/${a*a}`,'The time is not squared.'],[`${a}/1`,'This reverses the rate.']]);}
 throw new Error(`unsupported ${RF} ${form}`)}

const SR='a2-series';
function series(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 if(c==='sr-arith-apply'){const a=pick(r,2,10),d=pick(r,1,6),n=pick(r,5,10),last=a+(n-1)*d,sum=n*(a+last)/2;if(s==='numeric')return num(SR,`An arithmetic sequence begins ${a}, ${a+d}, … and has ${n} terms. Find its sum.`,sum,[[n*(a+last),'This forgets to divide the endpoint-pair total by 2.'],[last,'This reports the final term rather than the sum.']],`Use S=n(a₁+a_n)/2=${sum}.`);return order(r,SR,`Order the steps to sum ${n} terms of an arithmetic sequence with first term ${a} and difference ${d}.`,['Find the last term','Add the first and last terms','Multiply by the number of terms','Divide by 2'],'Endpoint pairing produces the arithmetic-series formula.');}
 if(c==='sr-convert'){const a=pick(r,1,8),d=pick(r,1,6),n=pick(r,8,15),ans=a+(n-1)*d;if(s==='numeric')return num(SR,`a₁=${a}, a_n=a_(n−1)+${d}. Find a_${n}.`,ans,[[a+n*d,'This uses n increments instead of n−1.'],[a+(n-2)*d,'This uses one too few increments.']],`The explicit rule is a_n=${a}+(n−1)${d}, giving ${ans}.`);return mcq(r,SR,`Convert a₁=${a}, a_n=${d}a_(n−1) to explicit form.`,[`a_n=${a}·${d}^(n−1)`,'A geometric recursion multiplies by the common ratio once per step.'],[[`a_n=${a}+${d}(n−1)`,'That is arithmetic rather than geometric.'],[`a_n=${d}·${a}^(n−1)`,'The first term and ratio are reversed.'],[`a_n=${a}·${d}^n`,'The first term occurs at exponent zero.']]);}
 if(c==='sr-geo-apply'){const a=pick(r,1,5),q=choose(r,[2,3] as const),n=pick(r,4,8),sum=a*(q**n-1)/(q-1);if(s==='numeric')return num(SR,`A geometric payout starts at ${a} and multiplies by ${q} each week for ${n} weeks. Find the total.`,sum,[[a*q**(n-1),'This is only the final term.'],[a*(q**n)/(q-1),'The finite-sum numerator must subtract 1.']],`Use S=a(r^n−1)/(r−1)=${sum}.`);return bucket(r,SR,'Sort each question by whether it asks for one term or an accumulated total.',[['One term',['How much is paid in week 8?','What is the 12th term?']],['Series total',['How much is paid through week 8?','What is the sum of the first 12 terms?']]],'A sequence question asks for one position; a series question asks for accumulated terms.');}
 if(c==='sr-geo-derive'){const a=pick(r,1,5),q=choose(r,[2,3] as const),n=pick(r,3,6),sum=a*(q**n-1)/(q-1);return num(SR,`Evaluate ${a}+${a*q}+…+${a*q**(n-1)} using the subtract-a-shifted-copy derivation.`,sum,[[a*q**(n-1),'This is the last term only.'],[a*(q**n)/(q-1),'The derivation leaves r^n−1 in the numerator.']],`Subtracting S from qS isolates (q−1)S and gives ${sum}.`)}
 if(c==='sr-inf-apply'){const h=pick(r,5,15),[qn,qd]=choose(r,[[1,2],[2,3],[3,4]] as const),q=qn/qd,total=h+2*h*q/(1-q);return num(SR,`A ball drops ${h} m and rebounds ${qn}/${qd} of each previous height. Count all upward and later downward trips. Find total distance.`,total,[[h/(1-q),'This counts one copy of each rebound height instead of both up and down.'],[2*h/(1-q),'This doubles the initial drop, which occurs only once.']],`Total distance is h+2h·q/(1−q)=${fmt(total)}.`,0.000001)}
 if(c==='sr-inf-converge'){const q=choose(r,[0.2,0.5,0.8,1.2,-1.1] as const);return mcq(r,SR,`What happens to the infinite geometric series with common ratio ${q}?`,[Math.abs(q)<1?'Its partial sums approach a finite limit.':'It does not converge to a finite sum.',Math.abs(q)<1?'A geometric series converges exactly when |r|<1.':'Here |r|≥1, so terms do not shrink to zero.'],[[Math.abs(q)<1?'It diverges because there are infinitely many terms.':'It always converges because the terms follow a pattern.','The size of the ratio, not merely the number or pattern of terms, decides convergence.'],['Its sum is always zero','A geometric series generally has a nonzero sum.'],['Its behavior depends only on the first term','The common ratio determines whether later terms shrink.']]);}
 if(c==='sr-inf-sum'){const den=choose(r,[2,3,4] as const),a=den===3?9:den===4?3*pick(r,1,4):pick(r,2,12),q=1/den,ans=a/(1-q);return num(SR,`Find ${a}+${fmt(a*q)}+${fmt(a*q*q)}+… forever (common ratio 1/${den}).`,ans,[[a/(1+q),'The denominator is 1−r, not 1+r.'],[a*q/(1-q),'This starts from the second term and omits the first.']],`Since |r|<1, S=a/(1−r)=${fmt(ans)}.`,0.000001)}
 if(c==='sr-sigma-read'){if(s==='numeric'){const p=choose(r,[1,2,3] as const),n=pick(r,3,6),sum=Array.from({length:n},(_,i)=>(i+1)**p).reduce((a,v)=>a+v,0);return num(SR,`Evaluate Σ(k=1 to ${n}) k^${p}.`,sum,[[n**p,'This reports only the final term.'],[sum-n**p,'This omits the final term.']],`Expand every integer k from 1 through ${n} and add the powers.`)}const m=choose(r,[3,4] as const),co=choose(r,[2,3] as const),ks=Array.from({length:m},(_,i)=>i+1);return pairs(r,SR,'Match each sigma notation to its expansion.',[[`Σ(k=1 to ${m}) k`,ks.join('+')],[`Σ(k=1 to ${m}) k²`,ks.map(k=>k*k).join('+')],[`Σ(k=1 to ${m}) ${co}k`,ks.map(k=>co*k).join('+')]],'Each sigma is expanded by substituting every integer index in its stated range.');}
 if(c==='sr-sigma-write'){const n=pick(r,5,10),q=pick(r,2,5);if(s==='numeric')return num(SR,`The sum ${q}+${2*q}+…+${n*q} is Σ(k=1 to N) ${q}k. Find N.`,n,[[n*q,'That is the final term, not the upper index.'],[n-1,'This stops one term too early.']],`The last term ${n*q} occurs when k=${n}.`);return mcq(r,SR,`Which sigma represents 1²+2²+…+${n}²?`,[`Σ(k=1 to ${n}) k²`,'The index runs through the bases and each term squares the index.'],[[`Σ(k=1 to ${n}) 2k`,'This produces even numbers, not squares.'],[`Σ(k=0 to ${n}) k²`,'This includes an extra zero term; while numerically equal, it does not match the stated indexing exactly.'],[`Σ(k=1 to ${n*n}) k`,'This changes both the terms and the upper bound.']]);}
 throw new Error(`unsupported ${SR} ${form}`)}

const SI='a2-statistics';
function statistics(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 const conceptual=(prompt:string,correct:[string,string],wrong:Array<[string,string]>)=>mcq(r,SI,prompt,correct,wrong);
 if(c==='si-bias-vs-variability')return conceptual('A huge voluntary online poll is strongly biased. What does the huge sample mainly improve?',['It reduces random variability but does not remove selection bias.','Large n tightens the estimate around the biased center.'],[['It removes all bias','Sample size cannot repair a nonrepresentative selection process.'],['It proves causation','A survey design does not create random assignment.'],['It makes the population parameter equal the sample statistic','Sampling error may shrink, but the statistic is still an estimate.']]);
 if(c==='si-bias'){if(s==='dragBucket')return bucket(r,SI,'Sort each survey flaw by its primary source of bias.',[['Selection bias',['Poll only visitors to a fan website','Survey only volunteers who click a link']],['Response bias',['Ask a leading question','Ask about illegal behavior face to face']]],'Selection changes who enters the sample; response bias changes how sampled people answer.');return conceptual('Which survey question is least biased?',['How many hours did you exercise last week?','It asks for a concrete quantity without praise, blame, or a suggested answer.'],[['Don’t you agree exercise is essential?','The wording pushes respondents toward agreement.'],['How often do you make the healthy choice to exercise?','The value-laden phrase encourages socially desirable answers.'],['Why do you avoid enough exercise?','The question assumes the respondent exercises too little.']]);}
 if(c==='si-causation'){if(s==='dragBucket')return bucket(r,SI,'Sort each explanation of an association.',[['Possible confounder',['Larger fires cause both more damage and more firefighters','Age affects both medication use and health']],['Direct causal mechanism',['Random assignment changes only the treatment','A controlled intervention changes the outcome pathway']]],'A confounder influences both variables; a randomized intervention can isolate a causal pathway.');return conceptual('An observational study finds breakfast eaters score higher. What is the main limitation?',['The association may reflect confounding rather than a breakfast effect.','Other differences between breakfast eaters and non-eaters may explain the score gap.'],[['The sample is automatically too small','Sample size is separate from confounding.'],['The result proves breakfast lowers scores','The observed direction is opposite and still noncausal.'],['Observational data can never show any association','They can estimate associations, but not isolate causation reliably.']]);}
 if(c==='si-ci-meaning'){if(s==='matchPairs')return pairs(r,SI,'Match each change to its effect on a confidence interval.',[['Larger sample','Narrower interval'],['Higher confidence level','Wider interval from higher confidence'],['More variable data','Wider interval from more variability'],['Smaller sample','Wider interval from less information']],'Interval width reflects information, confidence, and variability.');return conceptual('A 95% confidence interval is 44% to 52%. Which statement is appropriate?',['The method is designed to capture the population proportion in about 95% of repeated samples.','Confidence describes the long-run performance of the interval procedure.'],[['There is a 95% probability this fixed interval contains the fixed parameter','After sampling, the classical parameter and interval are fixed.'],['95% of individuals fall between 44% and 52%','The interval estimates a population proportion, not individual values.'],['The sample proportion must be 48% exactly','The midpoint often is the estimate, but rounding or asymmetric methods can differ.']]);}
 if(c==='si-claim-capstone'){if(s==='dragBucket')return bucket(r,SI,'Sort each finding by whether immediate action is justified.',[['Act cautiously',['Randomized trial shows a meaningful benefit with narrow uncertainty','Replicated experiment shows a practically important effect']],['Wait or investigate',['Tiny effect is statistically significant only because n is enormous','Voluntary poll conflicts with representative samples']]],'Action requires credible design, practical importance, and uncertainty small enough for the decision.');return conceptual('A voluntary survey of 300,000 app users reports 78% satisfaction. What question should be asked first?',['Who was able and willing to respond?','A very precise estimate can still target the wrong population because of selection bias.'],[['Is the margin of error below 1%?','Precision cannot repair a biased sample.'],['Was the percentage rounded?','Rounding is secondary to representativeness.'],['Was the sample larger than 1,000?','The sample is already huge; design is the main concern.']]);}
 if(c==='si-claim-design'){if(s==='matchPairs')return pairs(r,SI,'Match each study design to the strongest supported claim.',[['Random sample survey','Generalize an association to the sampled population'],['Randomized experiment','Support a causal effect for the experimental units'],['Convenience sample','Describe only the observed sample cautiously'],['Census of the whole population','State the population value without sampling error']],'Random sampling supports generalization; random assignment supports causation.');return conceptual('An observational study finds app users sleep longer. Which claim is defensible?',['App use is associated with longer sleep in the studied population.','The design supports an association, not a causal effect.'],[['The app causes longer sleep','Without random assignment, confounding remains.'],['Everyone will sleep longer if they use the app','This overgeneralizes and claims causation.'],['The app has no relationship with sleep','The observed association contradicts that statement.']]);}
 if(c==='si-claim-overreach'){if(s==='numeric'){const N=choose(r,[10000,20000] as const),prev=choose(r,[0.01,0.02,0.04,0.05] as const),sens=0.95,fpr=0.05,ans=N*prev*sens+N*(1-prev)*fpr;return num(SI,`In ${N} people, prevalence is ${prev*100}%, sensitivity is 95%, and false-positive rate is 5%. How many positive tests are expected?`,ans,[[N*prev*sens,'This counts true positives but omits false positives.'],[N*fpr,'This applies the false-positive rate to everyone, including diseased people.']],`Add true positives and false positives to obtain ${ans}.`,0,{kind:'diagnostic-total',N,prev})}return conceptual('A random sample from one city station finds 61% support a fare freeze. Which claim overreaches?',['61% of all national commuters support a fare freeze.','The sampling frame covers one location, not the national commuter population.'],[['About 61% of sampled station commuters support it','This describes the sample.'],['The station result estimates support among similar station users','This is cautious about the target population.'],['Sampling variability should be reported','Uncertainty is relevant rather than an overreach.']]);}
 if(c==='si-experiment-design')return conceptual('A treatment group recovers at 90%. What is missing before attributing recovery to the treatment?',['A comparable control group with random assignment','Without a control and random assignment, natural recovery and confounding cannot be separated.'],[['A larger percentage','The observed percentage alone cannot establish causation.'],['A more complicated formula','Design, not algebraic complexity, is missing.'],['A voluntary response survey','That would add selection bias rather than causal control.']]);
 if(c==='si-margin'){if(s==='dragBucket')return bucket(r,SI,'Sort changes by their effect on margin of error.',[['Shrinks margin',['Increase sample size','Use a lower confidence level']],['Does not necessarily shrink margin',['Increase population size from one million to ten million','Use more leading wording']]],'Margin depends mainly on sample size, variability, and confidence level, not a huge population size.');if(s==='numeric'){const n=choose(r,[100,256,400,625,1600,2500,6400,10000] as const),p=0.5,moe=2*Math.sqrt(p*(1-p)/n)*100;return num(SI,`For p-hat=0.5 and n=${n}, estimate the 2-SE margin of error in percentage points.`,moe,[[Math.sqrt(p*(1-p)/n),'This is a decimal standard error, not a two-SE percentage-point margin.'],[moe/2,'This gives one standard error rather than two.']],`2√(p(1−p)/n)×100=${fmt(moe)} percentage points.`,0.1)}return conceptual('A poll reports 48% with margin of error 3 points. Which interval matches?',['45% to 51%','Add and subtract three percentage points from the estimate.'],[['48% to 51%','The margin applies in both directions.'],['3% to 48%','The margin is not an endpoint.'],['45% to 48%','This includes only the lower half.']]);}
 if(c==='si-null-model'){if(s==='dragOrder')return order(r,SI,'Order the steps of a randomization test.',['State the null model','Shuffle labels under the null','Recompute the statistic many times','Compare the observed statistic with the null distribution'],'The test first defines chance behavior, simulates it, then locates the observation.');return conceptual('What assumption is represented when labels are shuffled in a randomization test?',['The null hypothesis that the labels are unrelated to outcomes.','Shuffling destroys any systematic group effect while preserving the observed values.'],[['The alternative hypothesis is certainly true','The shuffle models no effect, not the alternative.'],['Every observation becomes independent of all others','The exact design determines dependence; the key is exchangeability under the null.'],['The sample becomes representative','Shuffling does not change the sampling process.']]);}
 if(c==='si-parameter-statistic'){if(s==='matchPairs')return pairs(r,SI,'Match each quantity to its role.',[['Population mean μ','Population parameter'],['Sample mean x-bar','Sample statistic'],['Population proportion p','Population proportion parameter'],['Sample proportion p-hat','Sample proportion statistic']],'Parameters describe populations; statistics are computed from samples.');return conceptual('Twenty small polls vary widely around the same center. What does that show?',['The statistic has high sampling variability at this sample size.','Repeated samples can produce different estimates even with honest random sampling.'],[['The population parameter changes between every poll','The target parameter is treated as fixed.'],['Every poll is biased','Variation alone does not imply systematic bias.'],['A larger sample would vary more','Larger samples usually reduce sampling variability.']]);}
 if(c==='si-pvalue-idea'){if(s==='numeric'){const extreme=pick(r,3,15),total=choose(r,[100,200,250,500] as const),ans=100*extreme/total;return num(SI,`${extreme} of ${total} null-model simulations are at least as extreme as observed. Find the p-value as a percentage.`,ans,[[extreme/total,'This is a decimal proportion, not a percentage.'],[100*(total-extreme)/total,'This counts non-extreme simulations.']],`The p-value is ${extreme}/${total}×100=${fmt(ans)}%.`,0.1)}return conceptual('A p-value of 0.79 means what?',['Results at least this extreme are common under the null model.','A large p-value indicates the observation is not unusual if the null is true.'],[['There is a 79% chance the null hypothesis is true','A p-value is conditional on the null; it is not a probability that the hypothesis is true.'],['The alternative is proven false','Failure to find evidence is not proof of no effect.'],['The effect size is 79%','The p-value is not the magnitude of the effect.']]);}
 if(c==='si-read-poll'){if(s==='dragBucket')return bucket(r,SI,'Sort poll headlines by whether the intervals justify the claim.',[['Supported',['Candidates are separated by more than combined uncertainty','A difference remains after accounting for margins']],['Not supported',['Two estimates differ by 2 points with ±3-point margins','The intervals overlap substantially']]],'Headline certainty should reflect the uncertainty intervals, not point estimates alone.');if(s==='dragOrder')return order(r,SI,'Order the questions that best protect a poll interpretation.',['Who was sampled and how?','What is the margin of error?','What population and wording are claimed?','Does the headline stay within what the interval supports?'],'Design comes before precision, and both come before broad interpretation.');return conceptual('Candidate A has 48%, B has 45%, each with ±3 points. What is justified?',['The poll does not clearly establish a leader.','The uncertainty intervals overlap.'],[['A definitely leads by 3 points','The observed gap is no larger than the reported margin.'],['B definitely leads','The point estimates show the opposite direction.'],['The candidates are exactly tied','Overlapping intervals do not prove exact equality.']]);}
 if(c==='si-sampling-dist'){if(s==='numeric'){const n=choose(r,[25,100,225,400,900] as const),factor=choose(r,[2,3,4,5] as const);return num(SI,`A poll with n=${n} has a standard error of about 1/√n. What sample size cuts the error by factor ${factor}?`,n*factor*factor,[[n*factor,'Standard error scales with the square root, so sample size must grow by the square.'],[n/factor,'Reducing variability requires increasing, not decreasing, sample size.']],`Multiply sample size by ${factor}² to divide standard error by ${factor}.`)}return conceptual('What happens to a sampling distribution when n increases substantially?',['It becomes narrower around the same parameter if the estimator is unbiased.','Standard error decreases roughly as 1/√n.'],[['Its center necessarily shifts upward','Sample size changes spread, not systematic center.'],['It becomes wider','Larger samples reduce random variability.'],['It becomes biased','Bias comes from design or estimator choice, not n alone.']]);}
 if(c==='si-sampling-variability')return conceptual('Repeated honest random samples land on both sides of the true value. What does the center of their estimates indicate?',['Whether the estimator is centered on the population parameter.','A centered sampling distribution indicates little systematic bias.'],[['The exact result of the next sample','The next statistic remains random.'],['The population size','The center estimates the parameter, not the population count.'],['The margin of error of one individual','Sampling variability concerns statistics, not individual uncertainty.']]);
 if(c==='si-significance-limits'){if(s==='dragBucket')return bucket(r,SI,'Sort findings by whether practical action is justified.',[['Potentially actionable',['Moderate meaningful effect with credible design and narrow uncertainty','Replicated benefit large enough to matter']],['Not yet actionable',['0.3-point gain on a 100-point scale despite tiny p-value','Biased survey with an extremely precise percentage']]],'Statistical significance must be combined with design quality and practical importance.');return conceptual('A huge randomized study finds a 0.3-point score increase with p<0.001. What is the best conclusion?',['The effect is statistically detectable but may be too small to justify the cost.','Large samples can detect effects that have little practical importance.'],[['The program is automatically worth buying','A decision also depends on effect size, cost, and alternatives.'],['The result must be due to bias','Randomization supports causation, though practical value remains separate.'],['The effect is exactly zero','The estimate is nonzero and statistically detectable.']]);}
 if(c==='si-standard-error'){if(s==='numeric'){const n=choose(r,[100,256,400,625,1600,2500,6400,10000] as const),p=0.5,ans=100*Math.sqrt(p*(1-p)/n);return num(SI,`Estimate the standard error in percentage points for p=0.5 and n=${n}.`,ans,[[ans*2,'This is an approximate two-standard-error margin, not one standard error.'],[Math.sqrt(p*(1-p)/n),'This is the decimal scale rather than percentage points.']],`SE=√(p(1−p)/n)×100=${fmt(ans)} ${ans===1?'point':'points'}.`,0.1,{kind:'standard-error',n,mult:1})}return conceptual('Two 1,000-person polls sample from populations of 100,000 and 100 million. Which has noticeably smaller standard error?',['Neither; with tiny sampling fractions their standard errors are nearly the same.','For large populations, sample size matters much more than population size.'],[['The poll from 100 million','A larger population does not make the same sample more precise.'],['The poll from 100,000','The finite-population correction is negligible at this sampling fraction.'],['Both have zero error','Random samples still vary.']]);}
 if(c==='si-study-type'){if(s==='matchPairs')return pairs(r,SI,'Match each design to its strongest conclusion.',[['Randomized experiment','Causal effect'],['Random sample observational study','Population association'],['Convenience survey','Sample description only'],['Census','Exact population description']],'Random assignment addresses causation; random sampling addresses generalization.');return conceptual('Researchers follow adults for ten years without assigning exercise. What type of study is this?',['Observational study','The researchers observe existing behavior rather than assign treatment.'],[['Randomized experiment','Random assignment does not occur in this design.'],['Census','Only a sample of adults is followed.'],['Simulation','The outcomes are observed in real participants.']]);}
 throw new Error(`unsupported ${SI} ${form}`)}

const TF='a2-trig';
function trig(r:Rand,b:Band,form:string):Variant{const [c,s]=form.split('__');
 if(c==='tf-amp-period'){const A=pick(r,2,7),k=pick(r,-5,5);return num(TF,`Find the minimum of y=${A}sin(x) ${sign(k)}.`,k-A,[[k+A,'That is the maximum.'],[-A,'This omits the vertical shift.']],`Since sin ranges from −1 to 1, the minimum is ${k}−${A}=${k-A}.`)}
 if(c==='tf-arc-length'){const rad=pick(r,2,9),den=choose(r,[2,3,4,6] as const),theta=Math.PI/den,ans=rad*theta;return num(TF,`A circle has radius ${rad} and central angle π/${den}. Find arc length to hundredths.`,ans,[[theta,'This omits the radius.'],[rad*Math.PI*den,'The angle denominator should divide π.']],`Use s=rθ=${rad}·π/${den}.`,0.01)}
 if(c==='tf-exact-values'){const data=choose(r,[['sin',30,0.5],['cos',60,0.5],['sin',45,Math.SQRT1_2],['cos',45,Math.SQRT1_2],['tan',45,1],['cos',30,Math.sqrt(3)/2],['sin',60,Math.sqrt(3)/2],['tan',30,1/Math.sqrt(3)],['tan',60,Math.sqrt(3)]] as const);return num(TF,`Find ${data[0]} ${data[1]}° to hundredths.`,data[2],[[1-data[2],'This confuses the ratio with a complementary value.'],[data[2]*data[2],'This squares the trigonometric value.']],`The unit-circle exact value rounds to ${round(data[2],2)}.`,0.01)}
 if(c==='tf-identity'){const sin=choose(r,[0.28,0.3,0.352,0.4,0.5,0.6,0.8,0.96] as const),cos=Math.sqrt(1-sin*sin);if(s==='numeric')return num(TF,`sin θ=${sin} and θ is in Quadrant I. Find cos θ.`,cos,[[-cos,'Quadrant I requires a positive cosine.'],[1-sin,'The identity uses squares, not direct subtraction.']],`cos θ=√(1−sin²θ)=${fmt(cos)}.`,0.001);return mcq(r,TF,'Why does solving cos²θ=0.64 first give cosθ=±0.8?',['Both 0.8 and −0.8 have square 0.64.','Squaring removes sign, so both signs are algebraic candidates.'],[['Cosine is always positive','Cosine is negative in Quadrants II and III.'],['The angle must have two values only','The sign step concerns the ratio; periodic angles may yield more solutions.'],['Square roots never have a principal value','The principal root is positive, but solving an equation requires both signs.']]);}
 if(c==='tf-inverse'){const opp=pick(r,2,8),adj=pick(r,2,8),ans=180/Math.PI*Math.atan(opp/adj);return num(TF,`A right triangle has opposite side ${opp} and adjacent side ${adj}. Find θ in degrees to tenths.`,ans,[[Math.atan(opp/adj),'This is in radians rather than degrees.'],[180/Math.PI*Math.atan(adj/opp),'This reverses opposite and adjacent.']],`θ=tan⁻¹(${opp}/${adj})≈${round(ans,1)}°.`,0.1)}
 if(c==='tf-model'){const mid=pick(r,15,30),A=pick(r,5,12),T=choose(r,[20,24,30] as const);if(s==='numeric')return num(TF,`For h(t)=${mid}−${A}cos(2πt/${T}), find h(${T/2}).`,mid+A,[[mid-A,'That is the value at t=0.'],[mid,'That is the midline, not the opposite extreme.']],`At half a period cosπ=−1, so h=${mid}+${A}.`);return mcq(r,TF,'Why might a ride-height model begin with −A cos(ωt) instead of +A sin(ωt)?',['It starts at the minimum height when t=0.','cos0=1, so a negative cosine begins A units below the midline.'],[['Sine and cosine are unrelated','They are phase-shifted versions of the same wave family.'],['Negative cosine has no period','Its period is unchanged by reflection.'],['It makes the amplitude negative','Amplitude is the positive magnitude |A|.']]);}
 if(c==='tf-ratios'){if(s==='dragBucket')return bucket(r,TF,'Sort each side description relative to angle θ.',[['Opposite',['Across from θ','Does not touch θ']],['Adjacent',['Touches θ but is not the hypotenuse','Forms θ with the hypotenuse']],['Hypotenuse',['Opposite the right angle','Longest side']]],'Side names depend on the marked angle and the right angle.');const triples=choose(r,[[3,4,5],[5,12,13],[8,15,17],[7,24,25],[9,40,41],[20,21,29],[12,35,37]] as const),opp=triples[0],adj=triples[1],hyp=triples[2];return num(TF,`In a ${opp}-${adj}-${hyp} right triangle, θ is opposite ${opp}. If cosθ=n/${hyp}, find n.`,adj,[[opp,'This is the opposite side used by sine.'],[hyp,'The hypotenuse is already the denominator.']],`Cosine is adjacent over hypotenuse, so n=${adj}.`)}
 if(c==='tf-reference'){const q=choose(r,[2,3,4] as const),ref=choose(r,[30,45,60] as const),angle=q===2?180-ref:q===3?180+ref:360-ref;return num(TF,`Find the reference angle of ${angle}°.`,ref,[[angle-ref,'This gives an axis angle rather than the acute reference angle.'],[180-ref,'This rule works only in Quadrant II.']],`The acute angle to the nearest x-axis is ${ref}°.`)}
 if(c==='tf-solve-sides'){const hyp=choose(r,[8,10,12,14] as const),angle=choose(r,[30,45,60] as const),ans=hyp*Math.sin(angle*Math.PI/180);return num(TF,`A ramp of length ${hyp} meets the ground at ${angle}°. Find its vertical rise.`,ans,[[hyp*Math.cos(angle*Math.PI/180),'This finds the horizontal run.'],[hyp*Math.tan(angle*Math.PI/180),'Tangent uses the adjacent side rather than the hypotenuse.']],`The rise is opposite the angle, so use ${hyp}sin${angle}°.` ,0.01)}
 if(c==='tf-transform'){const B=choose(r,[0.25,0.5,2,3,4,5,6,8] as const),period=2*Math.PI/Math.abs(B);return num(TF,`Find the period of y=cos(${B}x).`,period,[[2*Math.PI*B,'The frequency factor divides the parent period.'],[Math.PI/Math.abs(B),'This gives half the full cycle.']],`Period=2π/|B|=${fmt(period)}.`,0.01)}
 if(c==='tf-unit-circle'){const angle=choose(r,[0,90,180,270,360,450,540,630] as const),cos=Math.cos(angle*Math.PI/180),sin=Math.sin(angle*Math.PI/180);if(s==='numeric')return num(TF,`Find cos ${angle}°.`,round(cos),[[round(sin),'This uses the y-coordinate instead of the x-coordinate.'],[-round(cos),'This reverses the unit-circle x-coordinate sign.']],`Cosine is the x-coordinate, ${round(cos)}.`);return mcq(r,TF,'In which quadrant are both sine and cosine negative?',['Quadrant III','Both x- and y-coordinates are negative there.'],[['Quadrant I','Both are positive.'],['Quadrant II','Sine is positive and cosine negative.'],['Quadrant IV','Cosine is positive and sine negative.']]);}
 if(c==='tf-wave-read'){const A=pick(r,2,7),k=pick(r,-4,4);return num(TF,`Find the maximum value of y=${A}sin x ${sign(k)}.`,k+A,[[k-A,'That is the minimum.'],[A,'This omits the vertical shift.']],`The maximum occurs when sinx=1, giving ${k+A}.`)}
 throw new Error(`unsupported ${TF} ${form}`)}

const FORMS:Record<string,string[]>={
 [CN]: ["cn-add-sub__mcq","cn-build-quad__buildExpression","cn-build-quad__mcq","cn-complex-plane__mcq","cn-complex-plane__plotPoint","cn-cts-solve__mcq","cn-formula-complex__buildExpression","cn-method-choice__mcq","cn-multiply__mcq","cn-neg-eq__buildExpression","cn-neg-eq__mcq"],
 [FT]: ["ft-arith__mcq","ft-arith__numeric","ft-compose-rule__mcq","ft-compose-rule__numeric","ft-compose__numeric","ft-full-rule__dragOrder","ft-full-rule__numeric","ft-inverse-graph__mcq","ft-inverse-graph__numeric","ft-inverse-graph__pointEntry","ft-inverse-rule__mcq","ft-inverse-undo__mcq","ft-inverse-undo__numeric"],
 [LG]: ["lg-cob__mcq","lg-cob__numeric","lg-define__mcq","lg-define__numeric","lg-e-solve__mcq","lg-e-solve__numeric","lg-e__mcq","lg-e__numeric","lg-evaluate__mcq","lg-evaluate__numeric","lg-exp-solve__mcq","lg-exp-solve__numeric","lg-expand-condense__mcq","lg-expand-condense__numeric","lg-graph__mcq","lg-halflife__mcq","lg-halflife__numeric","lg-ln__mcq","lg-ln__numeric","lg-log-solve__mcq","lg-log-solve__numeric","lg-models__mcq","lg-models__numeric","lg-power__buildExpression","lg-power__numeric","lg-product__mcq","lg-product__numeric","lg-scales__mcq","lg-scales__numeric"],
 [PF]: ["pf-anatomy__mcq","pf-anatomy__numeric","pf-build__mcq","pf-build__numeric","pf-cubes__buildExpression","pf-cubes__mcq","pf-cubes__numeric","pf-div-theorems__buildExpression","pf-div-theorems__mcq","pf-div-theorems__numeric","pf-end-behavior__buildExpression","pf-end-behavior__mcq","pf-factor-thm__mcq","pf-factor-thm__numeric","pf-grouping__buildExpression","pf-grouping__mcq","pf-leading-term__mcq","pf-leading-term__numeric","pf-long-div__buildExpression","pf-long-div__mcq","pf-long-div__numeric","pf-multiplicity__mcq","pf-multiplicity__numeric","pf-quad-form__buildExpression","pf-quad-form__numeric","pf-sketch__buildExpression","pf-sketch__mcq","pf-synthetic__buildExpression","pf-synthetic__mcq","pf-synthetic__numeric","pf-turning__mcq","pf-turning__numeric","pf-zeros__buildExpression","pf-zeros__numeric"],
 [RE]: ["re-both-sides__mcq","re-both-sides__numeric","re-conjugates__buildExpression","re-conjugates__numeric","re-convert__buildExpression","re-convert__mcq","re-convert__numeric","re-domains__buildExpression","re-domains__mcq","re-domains__numeric","re-extraneous__buildExpression","re-extraneous__mcq","re-extraneous__numeric","re-models__mcq","re-models__numeric","re-plusminus__buildExpression","re-plusminus__mcq","re-plusminus__numeric","re-power-solve__numeric","re-products__buildExpression","re-products__numeric","re-rationalize__buildExpression","re-rules__mcq","re-rules__numeric","re-solve__mcq","re-solve__numeric","re-sqrt-fn__mcq","re-sqrt-fn__numeric","re-transform__buildExpression","re-transform__numeric","re-var-radicals__buildExpression"],
 [RF]: ["rf-divide__buildExpression","rf-divide__mcq","rf-equations__buildExpression","rf-equations__mcq","rf-equations__numeric","rf-excluded__mcq","rf-excluded__numeric","rf-ha__mcq","rf-ha__numeric","rf-holes__mcq","rf-lcd__buildExpression","rf-like-denoms__buildExpression","rf-like-denoms__numeric","rf-mixed__buildExpression","rf-mixed__mcq","rf-multiply__buildExpression","rf-multiply__mcq","rf-opposite__buildExpression","rf-opposite__mcq","rf-reciprocal__mcq","rf-simplify__buildExpression","rf-simplify__mcq","rf-simplify__numeric","rf-unlike__buildExpression","rf-variation__mcq","rf-variation__numeric","rf-work__mcq","rf-work__numeric"],
 [SR]: ["sr-arith-apply__dragOrder","sr-arith-apply__numeric","sr-convert__mcq","sr-convert__numeric","sr-geo-apply__dragBucket","sr-geo-apply__numeric","sr-geo-derive__numeric","sr-inf-apply__numeric","sr-inf-converge__mcq","sr-inf-sum__numeric","sr-sigma-read__matchPairs","sr-sigma-read__numeric","sr-sigma-write__mcq","sr-sigma-write__numeric"],
 [SI]: ["si-bias-vs-variability__mcq","si-bias__dragBucket","si-bias__mcq","si-causation__dragBucket","si-causation__mcq","si-ci-meaning__matchPairs","si-ci-meaning__mcq","si-claim-capstone__dragBucket","si-claim-capstone__mcq","si-claim-design__matchPairs","si-claim-design__mcq","si-claim-overreach__mcq","si-claim-overreach__numeric","si-experiment-design__mcq","si-margin__dragBucket","si-margin__mcq","si-margin__numeric","si-null-model__dragOrder","si-null-model__mcq","si-parameter-statistic__matchPairs","si-parameter-statistic__mcq","si-pvalue-idea__mcq","si-pvalue-idea__numeric","si-read-poll__dragBucket","si-read-poll__dragOrder","si-read-poll__mcq","si-sampling-dist__mcq","si-sampling-dist__numeric","si-sampling-variability__mcq","si-significance-limits__dragBucket","si-significance-limits__mcq","si-standard-error__mcq","si-standard-error__numeric","si-study-type__matchPairs","si-study-type__mcq"],
 [TF]: ["tf-amp-period__numeric","tf-arc-length__numeric","tf-exact-values__numeric","tf-identity__mcq","tf-identity__numeric","tf-inverse__numeric","tf-model__mcq","tf-model__numeric","tf-ratios__dragBucket","tf-ratios__numeric","tf-reference__numeric","tf-solve-sides__numeric","tf-transform__numeric","tf-unit-circle__mcq","tf-unit-circle__numeric","tf-wave-read__numeric"],
};
const HANDLERS:Record<string,(r:Rand,b:Band,f:string)=>Variant>={[CN]:complex,[FT]:transformations,[LG]:logarithms,[PF]:polynomials,[RE]:radicals,[RF]:rationals,[SR]:series,[SI]:statistics,[TF]:trig};
export const ALGEBRA2_GENERATORS:VariantGen[]=Object.keys(FORMS).map(tag=>({tag,label:`Algebra II reusable variants: ${tag}`,forms:FORMS[tag] as never[],declarationOnly:true,gen:(r,b='core',f='default')=>HANDLERS[tag](r,b,f)}));
