const round=(n,d=10)=>Number(n.toFixed(d));
const clean=s=>String(s).replace(/−/g,'-').replace(/²/g,'^2').replace(/³/g,'^3').replace(/⁴/g,'^4').replace(/₁/g,'1').replace(/ₙ/g,'n').replace(/π/g,'pi').replace(/θ/g,'theta').replace(/√/g,'sqrt').replace(/∛/g,'cbrt').replace(/⁻¹/g,'^-1').replace(/·/g,'*').replace(/≥/g,'>=').replace(/≤/g,'<=').replace(/≠/g,'!=').replace(/–/g,'-').replace(/\+\-/g,'-').replace(/-\-/g,'+');
const nums=s=>(clean(s).match(/-?\d+(?:\.\d+)?/g)||[]).map(Number);
function split(input){const parts=String(input).split('||'),prompt=parts[0];let visible=null,options=[];for(const part of parts.slice(1)){if(!part)continue;try{const parsedPart=JSON.parse(part);if(parsedPart&&typeof parsedPart==='object'){visible=parsedPart;continue}}catch{}if(!options.length)options=part.split(';;')}return{prompt,visible,options};}
const literalSource=r=>r.source.replace(/\\([\\^$.*+?()[\]{}|/])/g,'$1');
const opt=(options,pred)=>{const found=typeof pred==='string'?options.find(x=>x===pred||clean(x)===clean(pred)):(options.find(x=>pred.test(clean(x)))||options.find(x=>clean(x).includes(clean(literalSource(pred)))));if(!found)throw new Error(`option not found ${pred} in ${options.join(' | ')}`);return found};
const tokenLabels=v=>(v?.tokens||[]).map(x=>x.label);
const matchToken=(labels,pred)=>{const x=labels.find(l=>typeof pred==='string'?(l===pred||clean(l)===clean(pred)):pred.test(clean(l)))||(typeof pred!=='string'?labels.find(l=>clean(l).includes(clean(literalSource(pred)))):undefined);if(!x)throw new Error(`token not found ${pred} in ${labels.join(' | ')}`);return x};
const allMatching=(labels,pred)=>labels.filter(l=>pred.test(clean(l)));
function solveRaw(form,input){const {prompt:p,visible:v,options}=split(input),q=clean(p),[concept,surface]=form.split('__'),z=nums(q);
 // Complex numbers
 if(concept==='cn-add-sub')return opt(options,/basis directions|independent directions/);
 if(concept==='cn-build-quad'){const h=z[0],k=z[1],B=-2*h,C=h*h+k*k;if(surface==='mcq'){const sign=B<0?'-':'+';return opt(options,`x^2 ${sign} ${Math.abs(B)}x + ${C} = 0`)}const labels=tokenLabels(v);return[matchToken(labels,'x²'),matchToken(labels,new RegExp(`${B<0?'-':'\\+'} ${Math.abs(B)}x`)),matchToken(labels,new RegExp(`\\+ ${C}$`)),matchToken(labels,'= 0')];}
 if(concept==='cn-complex-plane'){const m=q.match(/z = (-?\d+) ([+-]) (\d+)i/),re=+m[1],im=(m[2]==='-'?-1:1)*+m[3];if(surface==='plotPoint')return[{x:re+4,y:im+4}];return opt(options,String(im));}
 if(concept==='cn-cts-solve')return opt(options,/preserves equality.*perfect-square|perfect-square trinomial/);
 if(concept==='cn-formula-complex'){const m=q.match(/x\^2 ([+-]) (\d+)x \+ (\d+) = 0/),B=(m[1]==='-'?-1:1)*+m[2],C=+m[3],h=-B/2,k=Math.sqrt(C-h*h),labels=tokenLabels(v);return[matchToken(labels,`x = ${h} + ${k}i`),matchToken(labels,'or'),matchToken(labels,`x = ${h} − ${k}i`)];}
 if(concept==='cn-method-choice')return opt(options,'The quadratic formula');
 if(concept==='cn-multiply'){const m=q.match(/\((\d+)i\)\((\d+)i\)/);return opt(options,String(-(+m[1])*(+m[2])));}
 if(concept==='cn-neg-eq'){const m=q.match(/\(x ([+-]) (\d+)\)\^2 = -(\d+)/);if(surface==='buildExpression'){const printed=(m[1]==='-'?1:-1)*+m[2],k=Math.sqrt(+m[3]),labels=tokenLabels(v);return[matchToken(labels,`x = ${printed} + ${k}i`),matchToken(labels,'or'),matchToken(labels,`x = ${printed} − ${k}i`)]}return opt(options,'Yes');}
 // Function transformations
 if(concept==='ft-arith'){if(surface==='mcq')return opt(options,'f(x) − g(x)');const m=q.match(/g\(x\)=(-?\d+)x ([+-]) (\d+).*\(f-g\)\((-?\d+)\)/),a=+m[1],d=(m[2]==='-'?-1:1)*+m[3],x=+m[4];return x*x-(a*x+d);}
 if(concept==='ft-compose-rule'){if(surface==='mcq'){const k=+(q.match(/\(x\+(\d+)\)\^2/)||[])[1];return opt(options,`f(u)=u^2 and g(x)=x+${k}`)}const m=q.match(/g\(x\)=x\+(\d+).*g\((-?\d+)\)/),k=+m[1],x=+m[2];return(x+k)**2;}
 if(concept==='ft-compose'){const m=q.match(/g\(x\)=(-?\d+)x ([+-]) (\d+).*g\(f\((-?\d+)\)\)/),a=+m[1],d=(m[2]==='-'?-1:1)*+m[3],x=+m[4];return a*x*x+d;}
 if(concept==='ft-full-rule'){const m=q.match(/y=(-?\d+)\(x ([+-]) (\d+)\)\^2 ([+-]) (\d+)/),a=+m[1],h=(m[2]==='-'?1:-1)*+m[3],k=(m[4]==='-'?-1:1)*+m[5];if(surface==='numeric')return h;const labels=(v.items||[]).map(x=>x.label);return[`Shift the input by ${-h}`,'Square the result',`Multiply by ${a}`,`Add ${k}`];}
 if(concept==='ft-inverse-graph'){if(surface==='mcq')return opt(options,'y = x');if(surface==='pointEntry'){const m=q.match(/\((-?\d+), (-?\d+)\)/);return[+m[2],+m[1]]}const m=q.match(/f\(x\)=(-?\d+)x ([+-]) (\d+)/),a=+m[1],d=(m[2]==='-'?-1:1)*+m[3];return d/(1-a);}
 if(concept==='ft-inverse-rule'){const m=q.match(/f\(x\)=(-?\d+)x ([+-]) (\d+)/),a=+m[1],d=(m[2]==='-'?-1:1)*+m[3];return opt(options,`f^-1(x)=(x ${d<0?'+':'-'} ${Math.abs(d)})/${a}`);}
 if(concept==='ft-inverse-undo'){if(surface==='mcq'){const m=q.match(/f\((-?\d+)\)=(-?\d+)/);return opt(options,m[1])}const m=q.match(/g\(x\)=(-?\d+)x ([+-]) (\d+).*g\^-1\((-?\d+)\)/),a=+m[1],d=(m[2]==='-'?-1:1)*+m[3],y=+m[4];return(y-d)/a;}
 // Logarithms
 if(concept==='lg-cob'){const m=q.match(/log_(\d+)\((\d+)\)/),base=+m[1],n=+m[2];if(surface==='numeric')return round(Math.log(n)/Math.log(base));return opt(options,`log(${n}) / log(${base})`);}
 if(concept==='lg-define'){const m=q.match(/log_(\d+)\((\d+)\)(?:=(\d+))?/),base=+m[1],n=+m[2],power=round(Math.log(n)/Math.log(base));if(surface==='numeric')return power;return opt(options,`${base}^${power} = ${n}`);}
 if(concept==='lg-e-solve'){if(surface==='numeric'){const m=q.match(/(\d+)e\^x=(\d+)/);return round(Math.log(+m[2]/+m[1]))}const m=q.match(/(\d+) ln\(x\)=(\d+)/),power=+m[2]/+m[1];return opt(options,`x = e^${power}`);}
 if(concept==='lg-e'){if(surface==='numeric')return round(Math.exp(z[0]));return opt(options,/Faster than 2\^x but slower than 3\^x/);}
 if(concept==='lg-evaluate'){const m=q.match(/log_(\d+)\(([^)]+)\)/),base=+m[1],arg=m[2].includes('/')?eval(m[2]):+m[2],ans=round(Math.log(arg)/Math.log(base));return surface==='numeric'?ans:opt(options,String(ans));}
 if(concept==='lg-exp-solve'){const m=q.match(/(?:(\d+)\*)?(\d+)\^x=(\d+)/),coef=+(m[1]||1),base=+m[2],rhs=+m[3];if(surface==='numeric')return round(Math.log(rhs/coef)/Math.log(base));return opt(options,new RegExp(`log_${base}\(${rhs}\)`));}
 if(concept==='lg-expand-condense'){const m=q.match(/(\d+)log_(\d+)\(([^)]+)\) - log_\2\(([^)]+)\)/);if(surface==='mcq'){const power=+m[1],base=+m[2];return opt(options,new RegExp(`log_${base}\(x\^${power}\/y\)`))}const mm=q.match(/(\d+)log_(\d+)\((\d+)\) \+ log_\2\((\d+)\)/),coef=+mm[1],base=+mm[2],a=+mm[3],d=+mm[4];return coef*Math.log(a)/Math.log(base)+Math.log(d)/Math.log(base);}
 if(concept==='lg-graph')return opt(options,/domain is x>0.*vertical asymptote x=0/i);
 if(concept==='lg-halflife'){const m=q.match(/half-life (\d+).*1\/(\d+)/i);if(surface==='numeric')return +m[1]*Math.log2(+m[2]);return opt(options,'The half-life');}
 if(concept==='lg-ln'){if(surface==='numeric')return z.at(-1);return opt(options,/ln 5 \+ ln x - ln y/);}
 if(concept==='lg-log-solve'){if(surface==='numeric'){const m=q.match(/log_(\d+)\((\d+)x ([+-]) (\d+)\) = log_\1\(x \+ (\d+)\)/),A=+m[2],B=(m[3]==='-'?-1:1)*+m[4],qv=+m[5];return(qv-B)/(A-1)}const m=q.match(/log_(\d+)\(x\) \+ log_\1\(x-(\d+)\) = 3/),base=+m[1],d=+m[2];return opt(options,`x(x−${d}) = ${base**3}`);}
 if(concept==='lg-models'){const A=z[0],rate=z[1],t=z.at(-1);if(surface==='numeric')return Math.round(A*Math.exp(rate*t));return opt(options,`${A} is the initial amount and ${rate} is the continuous rate`);}
 if(concept==='lg-power'){const m=q.match(/log_(\d+)\(\((\d+)\)\^(\d+)\)/);if(surface==='numeric'){return round(Math.log((+m[2])**(+m[3]))/Math.log(+m[1]))}const mm=q.match(/log_(\d+)\(x\^(\d+)\)/),power=+mm[2],labels=tokenLabels(v);return[matchToken(labels,String(power)),matchToken(labels,new RegExp(`log_${mm[1]}\(x\)`))];}
 if(concept==='lg-product'){if(surface==='numeric'){const m=q.match(/log_(\d+)\((\d+)\) \+ log_\1\((\d+)\)/);return round(Math.log(+m[2]) / Math.log(+m[1]) + Math.log(+m[3])/Math.log(+m[1]))}return opt(options,/2 \+ log_\d+\(y\)/);}
 if(concept==='lg-scales'){const diff=z[0];return surface==='numeric'?10**diff:opt(options,new RegExp(`${10**diff} times`));}
 // Polynomial functions
 if(concept==='pf-anatomy'){if(surface==='numeric'){const m=q.match(/degree-(\d+)/);return +m[1]-1;}return opt(options,/3\/x \+ 2/);}
 if(concept==='pf-build'){if(surface==='numeric'){const m=q.match(/V\(x\)=x\((\d+)-2x\)\((\d+)-2x\).*V\((\d+)\)/),L=+m[1],W=+m[2],x=+m[3];return x*(L-2*x)*(W-2*x)}const m=q.match(/crosses at x=(-?\d+) and bounces at x=(\d+)/),a=+m[1],d=+m[2];return opt(options,new RegExp(`\(x ${a<0?'\\+':'-'} ${Math.abs(a)}\)\(x-${d}\)\^2`));}
 if(concept==='pf-cubes'){const m=q.match(/x\^3 \+ (\d+)/),cube=+m[1],a=Math.round(Math.cbrt(cube));if(surface==='numeric')return-a;if(surface==='mcq')return opt(options,'1');const labels=tokenLabels(v);return[matchToken(labels,`(x + ${a})`),matchToken(labels,new RegExp(`x² − ${a}x \+ ${a*a}`))];}
 if(concept==='pf-div-theorems'){if(surface==='mcq')return opt(options,/remainder is 0/);if(surface==='numeric')return 0;const roots=[];for(const m of q.matchAll(/\(x\s*([+-])\s*(\d+)\)/g))roots.push(m[1]==='+'?-Number(m[2]):Number(m[2]));const labels=tokenLabels(v);return roots.map(root=>matchToken(labels,`x = ${root}`));}
 if(concept==='pf-end-behavior'){let neg,n;if(surface==='buildExpression'){const m=q.match(/f\(x\)=(-?)x\^(\d+)/);neg=!!m[1];n=+m[2];}else{neg=/negative leading/.test(q);n=/even degree/.test(q)?2:3;}const behavior=n%2===0?(neg?'falls left and falls right':'rises left and rises right'):(neg?'rises left and falls right':'falls left and rises right');if(surface==='buildExpression'){const labels=tokenLabels(v);return[matchToken(labels,behavior)]}return opt(options,behavior);}
 if(concept==='pf-factor-thm'){if(surface==='numeric')return 0;const m=q.match(/f\((-?\d+)\)=0/),a=+m[1];return opt(options,`x ${a<0?'+':'−'} ${Math.abs(a)}`);}
 if(concept==='pf-grouping'){if(surface==='mcq')return opt(options,/No common binomial factor/);const m=q.match(/x\^3\+(\d+)x\^2\+(\d*)x\+(\d+)/),a=+m[1],b=m[2]?+m[2]:1,labels=tokenLabels(v);return[matchToken(labels,`(x + ${a})`),matchToken(labels,`(x² + ${b})`)];}
 if(concept==='pf-leading-term'){if(surface==='mcq'){const m=q.match(/f\(x\)=(-?\d*)x\^(\d+)/),coef=m[1]==='-'?-1:+m[1]||1,n=+m[2];return opt(options,new RegExp(`${coef===1?'':coef===-1?'-':coef}x\^${n}`))}const m=q.match(/f\((-?\d+)\).*f\(x\)=(-?\d*)x\^(\d+) ([+-]) (\d*)x/),x=+m[1],coef=m[2]==='-'?-1:+m[2]||1,n=+m[3],low=(m[4]==='-'?-1:1)*(m[5]?+m[5]:1);return coef*x**n+low*x;}
 if(concept==='pf-long-div'){if(surface==='mcq')return opt(options,/dividend = divisor.*quotient \+ remainder/);if(surface==='numeric'){const m=q.match(/x\^2\+(\d+)x\+(\d+) is divided by x\+(\d+)/),sum=+m[1],constant=+m[2],a=+m[3],x=-a;return x*x+sum*x+constant;}const m=q.match(/x\^2\+(\d+)x\+(\d+) by x\+(\d+)/),sum=+m[1],a=+m[3],b=sum-a,labels=tokenLabels(v);return[matchToken(labels,`x + ${b}`)];}
 if(concept==='pf-multiplicity'){if(surface==='numeric'){const m=q.match(/\(x\+1\)\^(\d+)\(x-2\)\^(\d+)/);return +m[1]+ +m[2];}const m=q.match(/multiplicity (\d+)/),m1=+m[1];return opt(options,m1%2?'It crosses the x-axis':'It touches and turns');}
 if(concept==='pf-quad-form'){const m=q.match(/x\^4-(\d+)x\^2\+(\d+)/),sum=+m[1],prod=+m[2],disc=sum*sum-4*prod,a=(sum-Math.sqrt(disc))/2,bv=(sum+Math.sqrt(disc))/2;if(surface==='numeric')return 4;const roots=[-Math.sqrt(a),Math.sqrt(a),-Math.sqrt(bv),Math.sqrt(bv)].map(x=>`x = ${Number.isInteger(x)?x:round(x,6)}`),labels=tokenLabels(v);return roots.map(x=>matchToken(labels,x));}
 if(concept==='pf-sketch'){if(surface==='buildExpression'){const m=q.match(/\(x ([+-]) (\d+)\)\(x-(\d+)\)\^2/),a=(m[1]==='+'?-1:1)*+m[2],d=+m[3],labels=tokenLabels(v);return[matchToken(labels,`cross at x=${a}`),matchToken(labels,`bounce at x=${d}`)]}return opt(options,/touches the axis and turns/);}
 if(concept==='pf-synthetic'){if(surface==='mcq'){const m=q.match(/divisor x ([+-]) (\d+)/),root=(m[1]==='-'?1:-1)*+m[2];return opt(options,String(root))}if(surface==='numeric')return z.at(-1);const m=q.match(/bottom row 1, (-?\d+), (-?\d+), \| (-?\d+)/),a=+m[1],b=+m[2],labels=tokenLabels(v);return[matchToken(labels,'x²'),matchToken(labels,a<0?new RegExp(`- ${Math.abs(a)===1?'':Math.abs(a)}x`):new RegExp(`\\+ ${a===1?'':a}x`)),matchToken(labels,new RegExp(`${b<0?'-':'\\+'} ${Math.abs(b)}$`))];}
 if(concept==='pf-turning'){if(surface==='numeric')return z[0]+1;return opt(options,'4');}
 if(concept==='pf-zeros'){if(surface==='numeric')return 3;const roots=[...q.matchAll(/\(x([+-])(\d+)\)/g)].map(m=>m[1]==='+'?-Number(m[2]):Number(m[2])),labels=tokenLabels(v);return roots.map(x=>matchToken(labels,`x = ${x}`));}
 // Radical functions
 if(concept==='re-both-sides'){if(surface==='mcq'){const m=q.match(/sqrt\(x\^2-(\d+)\)=(-?\d+(?:\.\d+)?)/),a=+m[1],rhs=+m[2],x=Math.round(Math.sqrt(rhs*rhs+a));return opt(options,`x = ±${x}`)}const m=q.match(/cbrt\((\d+)x ([+-]) (\d+)\)=(\d+)/),a=+m[1],C=(m[2]==='-'?-1:1)*+m[3],root=+m[4];return(root**3-C)/a;}
 if(concept==='re-conjugates'){const roots=[...q.matchAll(/sqrt(\d+)/g)].map(m=>+m[1]),a=roots[0],d=roots[1];if(surface==='numeric')return a-d;const labels=tokenLabels(v);return[matchToken(labels,new RegExp(`sqrt${a} - sqrt${d}`)),matchToken(labels,new RegExp(`\/ \(${a-d}\)`))];}
 if(concept==='re-convert'){if(surface==='numeric'){const m=q.match(/(\d+)\^\((\d+)\/(\d+)\)/);return round((+m[1])**(+m[2]/+m[3]))}if(surface==='buildExpression'){const m=q.match(/x\^\((\d+)\/(\d+)\)/),p=+m[1],labels=tokenLabels(v);return[matchToken(labels,new RegExp(`x\^${p}`))]}const m=q.match(/(?:the )?(square|cube|fourth|\d+(?:th|st|nd|rd)) root of x\^(\d+)/),n=m[1]==='square'?2:m[1]==='cube'?3:m[1]==='fourth'?4:parseInt(m[1],10),p=+m[2];return opt(options,`x^(${p}/${n})`);}
 if(concept==='re-domains'){if(surface==='mcq'){const m=q.match(/sqrt\(x ([+-]) (\d+)\)/),h=(m[1]==='-'?1:-1)*+m[2];return opt(options,`(${h}, 0)`);}const m=q.match(/sqrt\((\d+)x ([+-]) (\d+)\)/),a=+m[1],C=(m[2]==='-'?-1:1)*+m[3],h=-C/a;if(surface==='numeric')return h;const labels=tokenLabels(v);return[matchToken(labels,`x ≥ ${h}`)];}
 if(concept==='re-extraneous'){if(surface==='mcq')return opt(options,/Squaring loses sign information/);const m=q.match(/sqrt\(x\+(\d+)\)=x/),k=+m[1],disc=1+4*k,sol=(1+Math.sqrt(disc))/2;if(surface==='numeric')return sol;const labels=tokenLabels(v);return[matchToken(labels,`x = ${sol}`)];}
 if(concept==='re-models'){if(surface==='numeric'){const m=q.match(/h=(\d+)/);return Math.sqrt(+m[1])/4}return opt(options,/multiplied by 2/);}
 if(concept==='re-plusminus'){const m=q.match(/x\^\(2\/(\d+)\)=(\d+)/),n=+m[1],rhs=+m[2],a=Math.sqrt(rhs),sol=a**n;if(surface==='numeric')return sol;if(surface==='buildExpression'){const labels=tokenLabels(v);return[matchToken(labels,`x = ${sol}`),matchToken(labels,'or'),matchToken(labels,`x = −${sol}`)]}return opt(options,'2');}
 if(concept==='re-power-solve'){const m=q.match(/x\^\((\d+)\/(\d+)\)=(\d+)/),p=+m[1],den=+m[2],rhs=+m[3];return round(rhs**(den/p));}
 if(concept==='re-products'){if(surface==='numeric')return z[0];const m=q.match(/\(1\+sqrt(\d+)\)\^2/),a=+m[1],labels=tokenLabels(v);return[matchToken(labels,'1'),matchToken(labels,`+ 2√${a}`),matchToken(labels,`+ ${a}`)];}
 if(concept==='re-rationalize'){const m=q.match(/(\d+)\/sqrt(\d+)/),k=+m[1],a=+m[2],labels=tokenLabels(v);return[matchToken(labels,`${k}√${a}`),matchToken(labels,`/ ${a}`)];}
 if(concept==='re-rules'){if(surface==='numeric')return z[0];return opt(options,'x');}
 if(concept==='re-solve'){if(surface==='mcq')return opt(options,/Check every candidate/);const m=q.match(/sqrt\(x(?:([+-]\d+))?\)=x-(\d+)/),C=m[1]?+m[1]:0,a=+m[2];const B=-(2*a+1),D=a*a-C,disc=B*B-4*D,roots=[(-B+Math.sqrt(disc))/2,(-B-Math.sqrt(disc))/2];return roots.find(x=>Math.abs(Math.sqrt(x+C)-(x-a))<1e-6);}
 if(concept==='re-sqrt-fn'){const m=q.match(/sqrt\(x ([+-]) (\d+)\) ([+-]) (\d+)/),h=(m[1]==='-'?1:-1)*+m[2],k=(m[3]==='-'?-1:1)*+m[4];if(surface==='numeric')return k;return opt(options,`(${h}, ${k})`);}
 if(concept==='re-transform'){const m=q.match(/sqrt\(x ([+-]) (\d+)\) ([+-]) (\d+)/),h=(m[1]==='-'?1:-1)*+m[2],k=(m[3]==='-'?-1:1)*+m[4];if(surface==='numeric')return h;const labels=tokenLabels(v);return[matchToken(labels,`(${h}, ${k})`)];}
 if(concept==='re-var-radicals'){const m=q.match(/sqrt\((\d+)x\^2y\)/),a=Math.sqrt(+m[1]),labels=tokenLabels(v);return[matchToken(labels,`${a}x√y`)];}
 // Rational functions
 if(concept==='rf-divide'){if(surface==='mcq')return opt(options,/Multiply by the reciprocal/);const m=q.match(/x\/(\d+)\) ÷ \(\(x\+(\d+)\)\/(\d+)/),d=+m[2],labels=tokenLabels(v);return[matchToken(labels,'x'),matchToken(labels,`/ (x + ${d})`)];}
 if(concept==='rf-equations'){if(surface==='mcq')return opt(options,/excluded or extraneous values/);const m=q.match(/1\/\(x-(\d+)\) = 1\/(\d+)/),a=+m[1],k=+m[2];if(surface==='numeric')return a+k;const labels=tokenLabels(v);return[matchToken(labels,`x ≠ ${a}`)];}
 if(concept==='rf-excluded'){if(surface==='numeric'){const m=q.match(/\((\d+)x-(\d+)\)/),coef=+m[1],C=+m[2];return C/coef}const roots=[...q.matchAll(/\(x([+-])(\d+)\)/g)].map(m=>m[1]==='+'?-Number(m[2]):Number(m[2]));return opt(options,`${roots.at(-2)} and ${roots.at(-1)}`);}
 if(concept==='rf-ha'){const m=q.match(/\((\d+)x(?:\^2)?[^)]*\)\/\((\d+)x(?:\^2)?/),a=+m[1],d=+m[2],ans=a/d;if(surface==='numeric')return ans;const g=(x,y)=>y?g(y,x%y):x,k=g(a,d);return opt(options,`y = ${d/k===1?String(a/k):`${a/k}/${d/k}`}`);}
 if(concept==='rf-holes'){const roots=[...q.matchAll(/\(x([+-])(\d+)\)/g)].map(m=>m[1]==='+'?-Number(m[2]):Number(m[2])),h=roots[0],a=roots.at(-1),den=h-a;return opt(options,`(${h}, ${Math.abs(den)===1?String(1/den):`${den<0?'-':''}1/${Math.abs(den)}`})`);}
 if(concept==='rf-lcd'){const m=q.match(/\(x-(\d+)\)\(x\+(\d+)\)/),a=+m[1],d=+m[2],labels=tokenLabels(v);return[matchToken(labels,`(x − ${a})`),matchToken(labels,`(x + ${d})`)];}
 if(concept==='rf-like-denoms'){if(surface==='numeric'){const m=q.match(/\((\d+)x\).*\(x-(\d+)\) - \((\d*)x\+(\d+)\)/),a=+m[1],d=+m[2],b=m[3]?+m[3]:1;return a-b}const m=q.match(/\((\d+)x\).*\(x\+(\d+)\) - \((\d*)x-3\)/),a=+m[1],d=+m[2],k=m[3]?+m[3]:1,labels=tokenLabels(v),coef=a-k;return[matchToken(labels,`${coef===1?'x':coef+'x'} + 3`),matchToken(labels,`/ (x + ${d})`)];}
 if(concept==='rf-mixed'){const m=q.match(/x\^2-(\d+)/),a=Math.sqrt(+m[1]);if(surface==='buildExpression'){const labels=tokenLabels(v);return[matchToken(labels,'2')]}return opt(options,`x ≠ 0, ${-a}, ${a}`);}
 if(concept==='rf-multiply'){if(surface==='buildExpression'){const m=q.match(/x\^2-(\d+)/),a=Math.sqrt(+m[1]),labels=tokenLabels(v);return[matchToken(labels,`x + ${a}`)]}const mm=q.match(/x\+(\d+)/),d=+mm[1];return opt(options,`x ≠ ${-d}`);}
 if(concept==='rf-opposite'){const m=q.match(/\((\d+)-x\)|\((\d+)-x\^2\)/),a=+(m[1]||Math.sqrt(+m[2]));if(surface==='mcq')return opt(options,'−1');const labels=tokenLabels(v);return[matchToken(labels,`−(x + ${a})`)];}
 if(concept==='rf-reciprocal')return opt(options,/nonzero numerator.*cannot produce zero/);
 if(concept==='rf-simplify'){if(surface==='numeric'){const m=q.match(/\((\d+)x\+(\d+)\)\/\(x\+(\d+)\)/),a=+m[1];return a}if(surface==='buildExpression'){const labels=tokenLabels(v);return[matchToken(labels,'1')]}return opt(options,/No; x is part of sums/);}
 if(concept==='rf-unlike'){const m=q.match(/(\d+)\/\(x\+(\d+)\) - 2\/x/),a=+m[1],d=+m[2],labels=tokenLabels(v),coef=a-2;return[matchToken(labels,coef===0?`−${2*d}`:`${coef===1?'x':coef+'x'} − ${2*d}`),matchToken(labels,`/ (x(x + ${d}))`)];}
 if(concept==='rf-variation'){if(surface==='mcq')return opt(options,/Speed and travel time/);const m=q.match(/y=(-?\d+).*x=(-?\d+).*x=(-?\d+)/),y1=+m[1],x1=+m[2],x2=+m[3];return x1*y1/x2;}
 if(concept==='rf-work'){const m=q.match(/in (\d+) hours(?: and another in (\d+) hours)?/),a=+m[1];if(surface==='mcq')return opt(options,`1/${a}`);const b=+m[2];return 1/(1/a+1/b);}
 // Sequences and series
 if(concept==='sr-arith-apply'){if(surface==='dragOrder')return['Find the last term','Add the first and last terms','Multiply by the number of terms','Divide by 2'];const m=q.match(/begins (\d+), (\d+).*has (\d+) terms/),a=+m[1],d=+m[2]-a,n=+m[3],last=a+(n-1)*d;return n*(a+last)/2;}
 if(concept==='sr-convert'){if(surface==='numeric'){const m=q.match(/a1=(\d+).*\+(\d+).*a_(\d+)/),a=+m[1],d=+m[2],n=+m[3];return a+(n-1)*d}const m=q.match(/a1=(\d+).*=(\d+)a_/),a=+m[1],d=+m[2];return opt(options,`a_n=${a}·${d}^(n−1)`);}
 if(concept==='sr-geo-apply'){if(surface==='dragBucket'){const out={};for(const item of v.items){out[item.label]=/through|sum of/i.test(item.label)?'Series total':'One term'}return out}const m=q.match(/starts at (\d+).*multiplies by (\d+).*for (\d+) weeks/),a=+m[1],r=+m[2],n=+m[3];return a*(r**n-1)/(r-1);}
 if(concept==='sr-geo-derive'){const m=q.match(/Evaluate (\d+)\+(\d+)\+\u2026\+(\d+)/),a=+m[1],second=+m[2],last=+m[3],r=second/a,n=Math.round(Math.log(last/a)/Math.log(r))+1;return a*(r**n-1)/(r-1);}
 if(concept==='sr-inf-apply'){const m=q.match(/drops (\d+) m and rebounds (\d+)\/(\d+)/),h=+m[1],r=+m[2]/+m[3];return h+2*h*r/(1-r);}
 if(concept==='sr-inf-converge'){const m=q.match(/ratio (-?[\d.]+)/),r=+m[1];return opt(options,Math.abs(r)<1?'Its partial sums approach a finite limit.':'It does not converge to a finite sum.');}
 if(concept==='sr-inf-sum'){const m=q.match(/Find (\d+).*common ratio 1\/(\d+)/i),a=+m[1],den=+m[2];return a/(1-1/den);}
 if(concept==='sr-sigma-read'){if(surface==='numeric'){const m=q.match(/to (\d+)\) k\^(\d+)/),n=+m[1],p=+m[2];let sum=0;for(let k=1;k<=n;k++)sum+=k**p;return sum}const out={};for(const l of v.left){const mm=+l.label.match(/to (\d+)\)/)[1],ks=Array.from({length:mm},(_,i)=>i+1);const cm=l.label.match(/\) (\d+)k/);out[l.label]=l.label.includes('k²')?ks.map(k=>k*k).join('+'):cm?ks.map(k=>+cm[1]*k).join('+'):ks.join('+')}return out;}
 if(concept==='sr-sigma-write'){if(surface==='numeric'){const m=q.match(/\+(\d+) is.*(\d+)k/),last=+m[1],qv=+m[2];return last/qv}const m=q.match(/\u2026\+(\d+)\^2/),n=+m[1];return opt(options,`Σ(k=1 to ${n}) k²`);}
 // Statistical inference
 if(concept==='si-bias-vs-variability')return opt(options,/reduces random variability.*does not remove selection bias/i);
 if(concept==='si-bias'){if(surface==='dragBucket'){const out={};for(const i of v.items)out[i.label]=/leading|illegal behavior/.test(i.label)?'Response bias':'Selection bias';return out}return opt(options,/How many hours did you exercise/);}
 if(concept==='si-causation'){if(surface==='dragBucket'){const out={};for(const i of v.items)out[i.label]=/Random assignment|controlled intervention/.test(i.label)?'Direct causal mechanism':'Possible confounder';return out}return opt(options,/confounding rather than a breakfast effect/);}
 if(concept==='si-ci-meaning'){if(surface==='matchPairs'){const map={'Larger sample':'Narrower interval','Higher confidence level':'Wider interval from higher confidence','More variable data':'Wider interval from more variability','Smaller sample':'Wider interval from less information'};return map}return opt(options,/designed to capture.*95% of repeated samples/i);}
 if(concept==='si-claim-capstone'){if(surface==='dragBucket'){const out={};for(const i of v.items)out[i.label]=/Randomized trial|Replicated experiment/.test(i.label)?'Act cautiously':'Wait or investigate';return out}return opt(options,/Who was able and willing to respond/);}
 if(concept==='si-claim-design'){if(surface==='matchPairs')return{'Random sample survey':'Generalize an association to the sampled population','Randomized experiment':'Support a causal effect for the experimental units','Convenience sample':'Describe only the observed sample cautiously','Census of the whole population':'State the population value without sampling error'};return opt(options,/associated with longer sleep/);}
 if(concept==='si-claim-overreach'){if(surface==='numeric'){const m=q.match(/In (\d+) people, prevalence is (\d+)%/),N=+m[1],prev=+m[2]/100;return N*prev*.95+N*(1-prev)*.05}return opt(options,/all national commuters/);}
 if(concept==='si-experiment-design')return opt(options,/comparable control group with random assignment/);
 if(concept==='si-margin'){if(surface==='dragBucket'){const out={};for(const i of v.items)out[i.label]=/Increase sample size|lower confidence/.test(i.label)?'Shrinks margin':'Does not necessarily shrink margin';return out}if(surface==='numeric'){const m=q.match(/n=(\d+)/),n=+m[1];return 2*Math.sqrt(.25/n)*100}return opt(options,'45% to 51%');}
 if(concept==='si-null-model'){if(surface==='dragOrder')return['State the null model','Shuffle labels under the null','Recompute the statistic many times','Compare the observed statistic with the null distribution'];return opt(options,/labels are unrelated to outcomes/);}
 if(concept==='si-parameter-statistic'){if(surface==='matchPairs')return{'Population mean μ':'Population parameter','Sample mean x-bar':'Sample statistic','Population proportion p':'Population proportion parameter','Sample proportion p-hat':'Sample proportion statistic'};return opt(options,/high sampling variability/);}
 if(concept==='si-pvalue-idea'){if(surface==='numeric'){const m=q.match(/(\d+) of (\d+)/),a=+m[1],n=+m[2];return 100*a/n}return opt(options,/common under the null model/);}
 if(concept==='si-read-poll'){if(surface==='dragBucket'){const out={};for(const i of v.items)out[i.label]=/separated by more|remains after/.test(i.label)?'Supported':'Not supported';return out}if(surface==='dragOrder')return['Who was sampled and how?','What is the margin of error?','What population and wording are claimed?','Does the headline stay within what the interval supports?'];return opt(options,/does not clearly establish a leader/);}
 if(concept==='si-sampling-dist'){if(surface==='numeric'){const m=q.match(/n=(\d+).*factor (\d+)/),n=+m[1],f=+m[2];return n*f*f}return opt(options,/becomes narrower around the same parameter/);}
 if(concept==='si-sampling-variability')return opt(options,/centered on the population parameter/);
 if(concept==='si-significance-limits'){if(surface==='dragBucket'){const out={};for(const i of v.items)out[i.label]=/Moderate meaningful|Replicated benefit/.test(i.label)?'Potentially actionable':'Not yet actionable';return out}return opt(options,/statistically detectable but may be too small/);}
 if(concept==='si-standard-error'){if(surface==='numeric'){const m=q.match(/n=(\d+)/),n=+m[1];return 100*Math.sqrt(.25/n)}return opt(options,/Neither;.*nearly the same/);}
 if(concept==='si-study-type'){if(surface==='matchPairs')return{'Randomized experiment':'Causal effect','Random sample observational study':'Population association','Convenience survey':'Sample description only','Census':'Exact population description'};return opt(options,'Observational study');}
 // Trigonometric functions
 if(concept==='tf-amp-period'){const m=q.match(/y=(\d+)sin\(x\) ([+-]) (\d+)/),A=+m[1],k=(m[2]==='-'?-1:1)*+m[3];return k-A;}
 if(concept==='tf-arc-length'){const m=q.match(/radius (\d+).*pi\/(\d+)/),r=+m[1],d=+m[2];return r*Math.PI/d;}
 if(concept==='tf-exact-values'){const m=q.match(/Find (sin|cos|tan) (\d+)/),fn=m[1],ang=+m[2]*Math.PI/180;return round(fn==='sin'?Math.sin(ang):fn==='cos'?Math.cos(ang):Math.tan(ang));}
 if(concept==='tf-identity'){if(surface==='mcq')return opt(options,/Both 0.8 and -0.8/);const m=q.match(/sin theta=([\d.]+)/),sine=+m[1];return Math.sqrt(1-sine*sine);}
 if(concept==='tf-inverse'){const m=q.match(/opposite side (\d+) and adjacent side (\d+)/),opp=+m[1],adj=+m[2];return 180/Math.PI*Math.atan(opp/adj);}
 if(concept==='tf-model'){if(surface==='mcq')return opt(options,/starts at the minimum height/);const m=q.match(/h\(t\)=(\d+)-(\d+)cos\(2pi\s*t\/(\d+)\).*h\((\d+)\)/),mid=+m[1],A=+m[2],T=+m[3],t=+m[4];return mid-A*Math.cos(2*Math.PI*t/T);}
 if(concept==='tf-ratios'){if(surface==='dragBucket'){const out={};for(const i of v.items)out[i.label]=/Across|Does not touch/.test(i.label)?'Opposite':/right angle|Longest/.test(i.label)?'Hypotenuse':'Adjacent';return out}const m=q.match(/In a (\d+)-(\d+)-(\d+)/),opp=+m[1],adj=+m[2];return adj;}
 if(concept==='tf-reference'){const a=z[0]%360;return a<=90?a:a<180?180-a:a<270?a-180:360-a;}
 if(concept==='tf-solve-sides'){const m=q.match(/length (\d+).*at (\d+)/),h=+m[1],ang=+m[2];return h*Math.sin(ang*Math.PI/180);}
 if(concept==='tf-transform'){const m=q.match(/cos\(([\d.]+)x\)/),B=+m[1];return 2*Math.PI/Math.abs(B);}
 if(concept==='tf-unit-circle'){if(surface==='mcq')return opt(options,'Quadrant III');const ang=z[0];return round(Math.cos(ang*Math.PI/180));}
 if(concept==='tf-wave-read'){const m=q.match(/y=(\d+)sin x ([+-]) (\d+)/),A=+m[1],k=(m[2]==='-'?-1:1)*+m[3];return k+A;}
 throw new Error(`unsupported independent form ${form}: ${p}`);
}
function solvePrompt(form,input){const v=solveRaw(form,input);if(typeof v==='number')return round(v);return v;}
module.exports={solvePrompt};
