import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { classifyProcess, MULTI_CONTROL, moveRelation, type ProcessEvent } from "./processEvents";

/**
 * S116: `extraneousRootLab` is instrumented for process evidence, which is what earns its
 * `adapt: 3` capability (every engine scoring 3 there appears in processEvents; before this it
 * scored 0, recorded honestly).
 *
 * The subtle requirement pinned here: BOTH controls must emit. `one-control-fixation` fires when
 * four moves sit on one control while the other was never touched. If the SQUARE button stayed
 * silent, a learner who correctly squared and then probed unproductively would still produce an
 * all-probe stream and be told they never squared — a false accusation generated by the
 * instrumentation itself.
 */
const ev = (control: string, dir: ProcessEvent["dir"]): ProcessEvent => ({ control, dir });

describe("extraneousRootLab process instrumentation (S116)", () => {
  it("is registered as a multi-control engine", () => {
    expect(MULTI_CONTROL.has("extraneousRootLab")).toBe(true);
  });

  it("probing without ever squaring reaches one-control-fixation", () => {
    const stream = [ev("probe", "away"), ev("probe", "toward"), ev("probe", "past"), ev("probe", "away")];
    expect(classifyProcess(stream, { multiControl: true })).toBe("one-control-fixation");
  });

  it("does NOT accuse a learner who squared and then probed unproductively", () => {
    // The square emits too, so the stream is no longer single-control — the false accusation the
    // silent-button design would have produced cannot occur.
    const stream = [ev("squared", "toward"), ev("probe", "away"), ev("probe", "past"), ev("probe", "away")];
    expect(classifyProcess(stream, { multiControl: true })).not.toBe("one-control-fixation");
  });

  it("aims the probe at the phantom when the phase is about the phantom", () => {
    // identifyPhantom / explainPhantom -> phantom is the target, so moving toward it is progress.
    // (trueRoot 2, phantomRoot -1 for sqrt(x + 2) = x.)
    const phantom = -1;
    expect(moveRelation(3, 1, phantom)).toBe("toward");
    expect(moveRelation(0, 3, phantom)).toBe("away");
    expect(moveRelation(0, -2, phantom)).toBe("past");
  });

  it("carries fixation copy for BOTH controls, naming what has not changed", () => {
    const src = readFileSync(join(process.cwd(), "src", "lib", "processEvents.ts"), "utf8");
    const block = src.slice(src.indexOf("extraneousRootLab: {", src.indexOf("FIXATION_CUES")));
    expect(block).toMatch(/probe:/);
    expect(block).toMatch(/squared:/);
    // The cue's job is the contrast, and it must never reveal the answer.
    expect(block.slice(0, 600)).not.toMatch(/x\s*=\s*-?\d/);
  });

  it("the capability vector records adapt: 3, now that it is earned", () => {
    const caps = JSON.parse(
      readFileSync(join(process.cwd(), "scripts", "engine-capabilities.json"), "utf8")
    ).types as Record<string, Record<string, number>>;
    expect(caps.extraneousRootLab.adapt).toBe(3);
  });
});
