type Band = "support" | "core" | "stretch";
type Variant = { tag: string; widget: any; answer: any };
type VariantGen = { tag: string; label: string; forms?: readonly never[]; gen: (rand:()=>number, band?:Band, form?:string)=>Variant };
type Rand=()=>number; type Handler=(r:Rand,b:Band)=>Variant;
const pick=(r:Rand,a:number,b:number)=>a+Math.floor(r()*(b-a+1));
const choose=<T>(r:Rand,xs:readonly T[])=>xs[pick(r,0,xs.length-1)];
const hi=(b:Band,s:number,c:number,t:number)=>b==='support'?s:b==='stretch'?t:c;
function shuffle<T>(r:Rand,xs:readonly T[]){const a=[...xs];for(let i=a.length-1;i;i--){const j=pick(r,0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function safe(answer:number, vals:Array<[number,string]>){const seen=new Set([answer]);const out=[] as Array<[number,string]>;for(const x of vals)if(Number.isFinite(x[0])&&!seen.has(x[0])){seen.add(x[0]);out.push(x)};for(let d=1;out.length<2;d++)if(!seen.has(answer+d)){seen.add(answer+d);out.push([answer+d,`That is ${d} more than the requested value. Recount the visible quantities and operation.`])}return out.slice(0,3)}
const num=(tag:string,prompt:string,answer:number,errs:Array<[number,string]>,success?:string):Variant=>({tag,answer,widget:{type:'numeric',prompt,answer,tolerance:0,unit:'',commonErrors:safe(answer,errs).map(([value,feedback])=>({value,feedback})),fallbackFeedback:'Use the quantities and relationship shown, then recompute one step at a time.',successFeedback:success??`Correct — the requested value is ${answer}.`}});
const mcq=(r:Rand,tag:string,prompt:string,correct:[string,string],wrong:Array<[string,string]>):Variant=>{const seen=new Set([correct[0]]);const ws=wrong.filter(x=>!seen.has(x[0])&&seen.add(x[0]));if(ws.length<1)throw new Error(`MCQ ${tag} needs at least one genuine distractor`);const options=shuffle(r,[{label:correct[0],feedback:correct[1],correct:true},...ws.slice(0,3).map(([label,feedback])=>({label,feedback,correct:false}))]).map((o,i)=>({id:`o${i}`,...o}));return{tag,answer:options.find(o=>o.correct)!.id,widget:{type:'mcq',prompt,options}}};
const line=(tag:string,prompt:string,start:number,hops:number,direction:'forward'|'back'='forward',hop=1):Variant=>{const sign=direction==='back'?-1:1,answer=start+sign*hop*hops,min=Math.max(0,Math.min(start,answer)-2*hop),max=Math.max(start,answer)+2*hop;const traps=safe(answer,[[answer-sign*hop,`That stops one hop too soon. Make all ${hops} ${hops===1?'hop':'hops'}.`],[answer+sign*hop,`That goes one hop too far. Stop after ${hops} ${hops===1?'hop':'hops'}.`],[start,`That is the starting point. Move ${direction} before checking.`]]).filter(x=>x[0]>=min&&x[0]<=max);return{tag,answer,widget:{type:'numberLineHop',prompt,min,max,start,hop,hops,direction,commonLandings:traps.map(([value,feedback])=>({value,feedback})),missFeedback:`Start at ${start} and make ${hops} ${hop}-unit ${direction} ${hops===1?'hop':'hops'}.`,successFeedback:`Correct — the hop path lands on ${answer}.`}}};
const fractionBar=(r:Rand,tag:string,den:number):Variant=>{const object=choose(r,['bar','ribbon','paper strip'] as const);const starts=[1,3,5,6].filter(x=>x!==den),denStart=choose(r,starts);return{tag,answer:{n:1,d:den},widget:{type:'fractionBar',notation:'words',showTarget:false,prompt:`Split the ${object} into ${den} equal parts so each part is ${den===2?'a half':'a fourth'}.`,targetNum:1,targetDen:den,numMin:1,numMax:1,denMin:1,denMax:6,numStart:1,denStart,commonFractions:[{num:1,den:den===2?4:2,feedback:`That makes ${den===2?'fourths':'halves'}, not ${den===2?'halves':'fourths'}. The number of equal parts must be ${den}.`}],successFeedback:`Correct — ${den} equal parts make each part ${den===2?'a half':'a fourth'}.`,lowFeedback:`Those parts are too small. Use exactly ${den} equal parts.`,highFeedback:`Those parts are too large. Use exactly ${den} equal parts.`}}};
const baseTen=(tag:string,target:number):Variant=>{const tens=Math.floor(target/10),ones=target%10;return{tag,answer:{hundreds:0,tens,ones},widget:{type:'baseTenCompose',prompt:`Build ${target} with ten-rods and one-cubes.`,target,requireStandard:true,maxHundreds:0,maxTens:12,maxOnes:12,commonBuilds:[{tens:ones,ones:tens,feedback:`That reverses the digits and builds ${ones*10+tens}. Use ${tens} tens and ${ones} ${ones===1?"one":"ones"}.`},{tens,ones:0,feedback:`That builds ${tens*10}. Add ${ones} ${ones===1?'one':'ones'} to reach ${target}.`}].filter(x=>x.tens*10+x.ones!==target),missFeedback:`Use ${tens} ten-rods and ${ones} ${ones===1?"one-cube":"one-cubes"}.`,successFeedback:`Correct — ${tens} tens and ${ones} ${ones===1?"one":"ones"} build ${target}.`}}};

const A='g1-add-subtract';
const addHandlers:Record<string,Handler>={
 BiggerFirstNumeric:(r,b)=>{const big=pick(r,6,hi(b,10,13,16)),small=pick(r,1,Math.min(5,20-big));return num(A,`${small} + ${big} = ? Start at ${big} and count on ${small}.`,big+small,[[big,`That is the starting number; count on ${small} more.`],[small,`That is only the smaller addend, not the total.`]])},
 BiggerFirstMcq:(r)=>{const a=pick(r,2,6),b=pick(r,a+1,10);return mcq(r,A,`To add ${a} + ${b} with the fewest hops, where should you start?`,[String(b),`Correct — start at the larger addend, ${b}, and count on ${a}.`],[[String(a),`Starting at ${a} requires ${b} hops, which is not the fewest.`],[String(a+b),`That is the total, not the starting point.`],['0',`Starting at zero would require counting the entire total.`]])},
 CompareNumeric:(r,b)=>{const small=pick(r,3,hi(b,7,9,11)),diff=pick(r,1,6),big=small+diff;return num(A,`${big} red blocks and ${small} blue blocks. How many more red blocks are there?`,diff,[[big+small,`That adds both groups. “How many more” asks for the difference.`],[small,`That repeats the smaller group instead of finding the gap.`]])},
 CompareMcq:(r)=>{const small=pick(r,3,8),big=small+pick(r,1,6);return mcq(r,A,`${big} birds and ${small} squirrels. Which equation finds how many more birds there are?`,[`${big} − ${small} = ?`,`Correct — subtract the smaller group from the larger group to find the difference.`],[[`${big} + ${small} = ?`,`Addition finds the total, not how many more.`],[`${small} − ${big} = ?`,`This reverses the comparison and would not represent the positive gap.`],[`${big} − 1 = ?`,`Subtracting one does not compare the two groups.`]])},
 CountBackMcq:(r)=>{const start=pick(r,6,14),h=pick(r,2,4);return mcq(r,A,`To count back ${h} from ${start}, where does the first hop land?`,[String(start-1),`Correct — the first backward hop moves one less, to ${start-1}.`],[[String(start-h),`That is the final landing after all ${h} hops, not the first hop.`],[String(start+1),`That moves forward instead of back.`],[String(start),`That stays at the starting point without making a hop.`]])},
 CountOnSmallNumeric:(r,b)=>{const a=pick(r,3,hi(b,8,10,13)),d=pick(r,0,3);return num(A,`${a} + ${d} = ? Count on ${d}.`,a+d,[[a,`That stops before counting on ${d}.`],[d,`That is only the amount counted on.`]])},
 CountingOnNumeric:(r,b)=>{const a=pick(r,4,hi(b,8,11,14)),d=pick(r,2,Math.min(5,20-a));return num(A,`${a} + ${d} = ? Start at ${a} and count on ${d}.`,a+d,[[a,`That is the start; count ${d} more.`],[a+d-1,`That stops one count too soon.`]])},
 CountingOnMcq:(r)=>{const a=pick(r,6,10),d=pick(r,1,4);return mcq(r,A,`What is the fast way to add ${a} + ${d}?`,[`Start at ${a} and count on ${d}`,`Correct — start with the larger amount and count only the smaller addend.`],[[`Start at 0 and count to ${a+d}`,`That works, but it is not the fast counting-on strategy.`],[`Start at ${d} and count on ${a}`,`This uses more hops because it starts at the smaller addend.`],[`Count backward from ${a}`,`Counting backward represents subtraction, not addition.`]])},
 DifferenceMcq:(r)=>{const b=pick(r,6,12),a=pick(r,2,b-1);return mcq(r,A,`How do you find how many more ${b} is than ${a}?`,[`${b} − ${a}`,`Correct — subtract the smaller number from the larger number.`],[[`${b} + ${a}`,`That finds a total, not a difference.`],[`${a} − ${b}`,`The order is reversed for a positive “how many more” question.`],[`${b} − 1`,`Subtracting one does not compare both numbers.`]])},
 EqualSignMcq:(r)=>{const a=pick(r,2,8),b=pick(r,1,8),same=r()<0.5;const c=same?a+b:Math.max(0,a+b-1);return mcq(r,A,`True or false: ${a} + ${b} = ${c}`,same?['True',`Correct — both sides have value ${a+b}.`]:['False',`Correct — the left side is ${a+b}, not ${c}.`],same?[[`False`,`Both sides equal ${a+b}, so the statement is true.`]]:[[`True`,`The two sides have different values, so the statement is false.`]])},
 EqualSignNumeric:(r)=>{const a=pick(r,3,8),b=pick(r,2,7),c=pick(r,2,a+b-1),ans=a+b-c;return num(A,`Make both sides equal: ${a} + ${b} = ${c} + ?`,ans,[[a+b,`That is the whole value of the left side, not the missing addend after ${c}.`],[c,`Repeating ${c} does not necessarily balance both sides.`]])},
 FactFamilyNumeric:(r)=>{const a=pick(r,3,9),b=pick(r,2,9),t=a+b;return num(A,`Fact family ${a}, ${b}, ${t}: ${t} − ${a} = ?`,b,[[a,`That subtracts the other part. The missing partner is ${b}.`],[t,`That repeats the whole instead of removing ${a}.`]])},
 MakeTenFirstNumeric:(r)=>{const a=pick(r,6,9),b=pick(r,11-a,Math.min(9,20-a)),used=10-a;return num(A,`${a} takes ${used} from ${b} to make ten. How many of the ${b} are left?`,b-used,[[used,`That is the part used to make ten, not the part left.`],[b,`That is the original addend before splitting it.`]])},
 MakeTenFirstMcq:(r)=>{const a=pick(r,6,9),b=pick(r,11-a,8),need=10-a,left=b-need;return mcq(r,A,`To add ${a} + ${b} by making ten, how should you split ${b}?`,[`${need} and ${left}`,`Correct — ${need} completes ten and ${left} remains.`],[[`${left} and ${need+1}`,`Those parts do not total ${b} correctly.`],[`${a} and ${b-a}`,`This split is based on the first addend rather than what ten needs.`],[`${need+1} and ${Math.max(0,left-1)}`,`Taking ${need+1} would pass ten instead of completing it exactly. Use only ${need}.`]])},
 PartWholeNumeric:(r)=>{const a=pick(r,3,10),b=pick(r,2,9);return num(A,`${a} red counters and ${b} blue counters. How many counters in all?`,a+b,[[Math.abs(a-b),`That finds the difference, not the whole.`],[Math.max(a,b),`That counts only the larger part.`]])},
 PartWholeMcq:(r)=>{const whole=pick(r,10,18),part=pick(r,3,whole-2);return mcq(r,A,`${whole} fruits in all. ${part} are apples. Which equation finds the other fruits?`,[`${whole} − ${part} = ?`,`Correct — subtract the known part from the whole.`],[[`${whole} + ${part} = ?`,`That adds the known part to the whole and double-counts it.`],[`${part} − ${whole} = ?`,`The whole should be first in this missing-part subtraction.`],[`${part} + ${whole} = ?`,`That also double-counts the known part.`]])},
 ResultUnknownNumeric:(r)=>{const add=r()<0.5;if(add){const a=pick(r,3,12),b=pick(r,2,Math.min(8,20-a));return num(A,`${a} frogs sit by a pond. ${b} more arrive. How many frogs are there now?`,a+b,[[a-b,`That subtracts even though more frogs arrive.`],[a,`That ignores the frogs that arrived.`]])}const a=pick(r,8,18),b=pick(r,2,a-2);return num(A,`${a} frogs sit by a pond. ${b} hop away. How many are left?`,a-b,[[a+b,`That adds the frogs that left instead of removing them.`],[b,`That gives the number that left, not the number remaining.`]])},
 ResultUnknownMcq:(r)=>{const a=pick(r,4,12),b=pick(r,2,7);return mcq(r,A,`${a} apples are in a basket. ${b} more are added. Which equation finds how many apples there are now?`,[`${a} + ${b} = ?`,`Correct — “more are added” means addition.`],[[`${a} − ${b} = ?`,`Subtraction would remove apples rather than add them.`],[`${b} − ${a} = ?`,`The story describes joining, not comparing or removing.`],[`${a} + 1 = ?`,`More than one apple is added.`]])},
 SubFactsMcq:(r)=>{const a=pick(r,8,15),b=pick(r,2,a-2),d=a-b;return mcq(r,A,`Which addition fact helps solve ${a} − ${b}?`,[`${b} + ${d} = ${a}`,`Correct — addition checks the related subtraction fact.`],[[`${a} + ${b} = ${a+b}`,`This uses the whole and removed part, not the missing difference.`],[`${d} + ${a} = ${a+d}`,`This does not rebuild the original whole.`],[`${b} + ${a} = ${a+b}`,`This adds both original numbers rather than finding the missing part.`]])},
 TakeAwayMcq:(r)=>{const a=pick(r,6,12),b=pick(r,2,a-1);return mcq(r,A,`What does ${a} − ${b} mean?`,[`Start with ${a} and take away ${b}`,`Correct — subtraction can describe removing ${b} from ${a}.`],[[`Start with ${b} and add ${a}`,`That describes addition, not taking away.`],[`Put ${a} and ${b} together`,`Putting groups together represents addition.`],[`Make both groups equal`,`The expression describes removal, not balancing groups.`]])},
 TensPartnersNumeric:(r)=>{const a=pick(r,1,9);return num(A,`${a} + ? = 10. What makes ten with ${a}?`,10-a,[[a,`That repeats the known part; the two parts must total ten.`],[10,`Ten is the whole, not the missing partner.`]])},
 TensPartnersMcq:(r)=>{const a=pick(r,1,9),b=10-a;return mcq(r,A,`Which pair are partners of ten?`,[`${a} and ${b}`,`Correct — ${a} and ${b} are partners because their sum is exactly 10.`],[[`${a} and ${b+1}`,`That pair totals 11, not 10.`],[`${a} and ${Math.max(0,b-1)}`,`That pair totals 9, not 10.`],[`${a} and ${a}`,`Equal parts make ten only when each part is 5.`]])},
 UnknownNumeric:(r)=>{const add=r()<0.6;if(add){const total=pick(r,8,18),known=pick(r,2,total-2);return num(A,`${known} + ? = ${total}. What is the missing number?`,total-known,[[total,`That is the whole, not the missing part.`],[known,`That repeats the known addend.`]])}const whole=pick(r,9,19),remain=pick(r,2,whole-2);return num(A,`${whole} − ? = ${remain}. What was taken away?`,whole-remain,[[remain,`That is what remains, not what was removed.`],[whole,`That is the starting whole.`]])}
};

const C='g1-counting-120';
const countHandlers:Record<string,Handler>={
 ChartFindNumeric:(r)=>{const start=pick(r,1,11)*10+1,pos=pick(r,2,8);return num(C,`Fill the missing number: ${start+pos-2}, ${start+pos-1}, __, ${start+pos+1}.`,start+pos,[[start+pos-1,`That repeats the number before the gap.`],[start+pos+1,`That is the number after the gap.`]])},
 ChartFindMcq:(r)=>{const n=pick(r,11,119),row=Math.ceil(n/10);return mcq(r,C,`Which row of a 1–120 chart contains ${n}?`,[`Row ${row}`,`Correct — row ${row} contains ${10*(row-1)+1} through ${10*row}.`],[[`Row ${Math.max(1,row-1)}`,`That row ends before ${n}, so it cannot contain the requested number.`],[`Row ${Math.min(12,row+1)}`,`That row starts after ${n}.`],[`Row ${n%10||10}`,`The ones digit does not name the row.`]])},
 ChartPatternNumeric:(r)=>{const n=pick(r,11,109);return num(C,`What is ten more than ${n} on a number chart?`,n+10,[[n+1,`That moves one space right, not one row down.`],[n-10,`That moves one row up, which is ten less.`]])},
 ChartPatternMcq:(r)=>mcq(r,C,`What do numbers in the same column of a 1–120 chart share?`,['The same ones digit',`Correct — moving down a column adds ten, so the ones digit stays the same.`],[['The same tens digit',`The tens digit changes as you move down rows.`],['They are equal',`Each row down is ten greater.`],['They all end in zero',`Only one column ends in zero.`]]),
 ChartRowsNumeric:(r)=>{const row=pick(r,1,12),start=(row-1)*10+1;return num(C,`A chart row starts at ${start}. What number ends the row?`,row*10,[[row*10-1,`That stops one square before the row ends.`],[start+10,`That is the first number of the next row.`]])},
 ChartRowsMcq:(r)=>{const row=pick(r,1,12),end=row*10;return mcq(r,C,`Which number ends row ${row} of a 1–120 chart?`,[String(end),`Correct — each row ends with a multiple of ten.`],[[String(end-1),`That is one square before the row end.`],[String(end+1),`That begins the next row.`],[String(row),`The row number is not the ending value.`]])},
 CountPileNumeric:(r)=>{const n=pick(r,20,99),ask=r()<0.5?'tens':'ones',ans=ask==='tens'?Math.floor(n/10):n%10;return num(C,`How many ${ask.toUpperCase()} are in ${n}?`,ans,[[ask==='tens'?n%10:Math.floor(n/10),`That uses the other place-value digit.`],[n,`That is the whole numeral, not the number of ${ask}.`]])},
 CountPileMcq:(r)=>{const a=pick(r,20,89),b=a+pick(r,1,10);return mcq(r,C,`Which is greater: ${a} or ${b}?`,[String(b),`Correct — ${b} is farther along in the count.`],[[String(a),`${a} comes before ${b} in counting order, so it is the smaller number.`],['They are equal',`The two numerals are different.`],['Cannot tell',`The numerals can be compared directly.`]])},
 CountSequenceNumeric:(r,b)=>{const n=pick(r,1,hi(b,55,89,119)),dir=r()<0.75?1:-1;return num(C,`What number comes ${dir===1?'right after':'right before'} ${n}?`,n+dir,[[n,`That repeats the starting number.`],[n-dir,`That moves in the opposite direction.`]])},
 CountSequenceNumberLineHop:(r,b)=>{const n=pick(r,5,hi(b,50,90,118));return line(C,`What number comes right after ${n}? Hop one forward and tap where you land.`,n,1,'forward',1)},
 CountSequenceMcq:(r)=>{const start=pick(r,10,110);const seq=[start,start+1,start+2,start+3];return mcq(r,C,`Which list is in counting order?`,[seq.join(', '),`Correct — each number is exactly one more than the number before it.`],[[[start,start+2,start+1,start+3].join(', '),`The middle two numbers are reversed.`],[seq.slice().reverse().join(', '),`That counts backward, not forward.`],[[start,start+1,start+3,start+4].join(', '),`This list skips ${start+2}, so it is not consecutive counting order.`]])},
 MixJumpsNumeric:(r)=>{const n=pick(r,20,99),ones=pick(r,1,4),ans=n+10+ones;return num(C,`Start at ${n}. Add ten, then add ${ones}. Where do you land?`,ans,[[n+ones,`That makes only the one-jump and forgets the ten-jump.`],[n+10,`That makes the ten-jump but forgets the final ${ones}.`]])},
 MixJumpsMcq:(r)=>mcq(r,C,`A jump of ten changes which place-value digit?`,['The tens digit',`Correct — adding ten changes the tens place while the ones digit stays the same.`],[['The ones digit',`A one-jump changes the ones digit.`],['Both digits every time',`The ones digit normally stays the same when ten is added.`],['No digit',`The numeral changes by one ten.`]]),
 OneMoreLessNumeric:(r)=>{const n=pick(r,10,110),less=r()<0.5;return num(C,`What is one ${less?'less':'more'} than ${n}?`,n+(less?-1:1),[[n,`That does not move one count.`],[n+(less?1:-1),`That moves in the opposite direction.`]])},
 OneMoreLessMcq:(r)=>{const n=pick(r,10,110);return mcq(r,C,`What is one less than ${n}?`,[String(n-1),`Correct — one count backward from ${n} is ${n-1}.`],[[String(n+1),`That is one more, not one less.`],[String(n-10),`That moves backward by ten instead of backward by one.`],[String(n),`That does not change the number.`]])},
 PastHundredNumeric:(r)=>{const n=pick(r,100,119);return num(C,`What number comes right after ${n}?`,n+1,[[n,`That repeats the starting number.`],[n-1,`That is the number before ${n}.`]])},
 PastHundredMcq:(r)=>{const tens=pick(r,10,12);return mcq(r,C,`How many tens make ${tens*10}?`,[String(tens),`Correct — ${tens} groups of ten make ${tens*10}.`],[[String(tens*10),`That is the total number of ones, not tens.`],[String(tens-1),`That many tens make only ${(tens-1)*10}, which is one ten too small.`],[String(tens+1),`That makes ${(tens+1)*10}, which is too many.`]])},
 SkipTenNumeric:(r)=>{const n=pick(r,10,109);return num(C,`Skip-count one ten: ${n} + 10 = ?`,n+10,[[n+1,`That adds one, not one ten.`],[n-10,`That moves backward by ten instead of skip-counting forward by ten.`]])},
 SkipTenMcq:(r)=>{const n=pick(r,11,69);return mcq(r,C,`Counting ${n}, ${n+10}, ${n+20}, ${n+30}: what stays the same?`,['The ones digit',`Correct — every jump adds one ten and keeps the ones digit.`],[['The tens digit',`The tens digit increases each jump.`],['The entire number',`The values increase by ten.`],['Nothing',`The ones digit remains constant.`]])},
 TeensNumeric:(r)=>{const ones=pick(r,1,9);return num(C,`What numeral is 1 ten and ${ones} ${ones===1?"one":"ones"}?`,10+ones,[[ones,`That counts only the ones and omits the ten.`],[ones*10+1,`That reverses the tens and ones.`]])},
 TeensMcq:(r)=>{const ones=pick(r,1,9),n=10+ones;return mcq(r,C,`Which numeral is 1 ten and ${ones} ${ones===1?"one":"ones"}?`,[String(n),`Correct — one ten plus ${ones} ${ones===1?"one":"ones"} is ${n}.`],[[String(ones),`That counts only the ones and omits the required group of ten.`],[String(ones*10+1),`That reverses the place values.`],[String(n+10),`That uses two tens even though the prompt names exactly one ten.`]])},
 TenMoreLessNumeric:(r)=>{const n=pick(r,20,109),less=r()<0.5;return num(C,`What is ten ${less?'less':'more'} than ${n}?`,n+(less?-10:10),[[n+(less?-1:1),`That changes by one, not ten.`],[n,`That does not make the ten-jump.`]])},
 TenMoreLessMcq:(r)=>{const n=pick(r,20,89);return mcq(r,C,`When you add ten to ${n}, what usually stays the same?`,['The ones digit',`Correct — adding ten changes the tens place and preserves the ones digit.`],[['The tens digit',`The tens digit increases by one.`],['The whole number',`The value becomes ten greater.`],['Both digits always change',`The ones digit stays the same in this range.`]])},
 TensOnesBaseTenCompose:(r,b)=>baseTen(C,pick(r,21,hi(b,69,94,99))),
 TensOnesNumeric:(r)=>{const tens=pick(r,2,9),ones=pick(r,0,9);return num(C,`What numeral is ${tens} tens and ${ones} ${ones===1?"one":"ones"}?`,10*tens+ones,[[10*ones+tens,`That reverses the tens and ones.`],[tens+ones,`That adds the digits instead of using place value.`]])},
 TensOnesMcq:(r)=>{const tens=pick(r,2,9),ones=pick(r,0,9),n=10*tens+ones;return mcq(r,C,`What is ${n} made of?`,[`${tens} tens and ${ones} ${ones===1?"one":"ones"}`,`Correct — the tens digit is ${tens} and the ones digit is ${ones}.`],[[`${ones} ${ones===1?"ten":"tens"} and ${tens} ones`,`That reverses the digits.`],[`${n} tens and 0 ones`,`That would be ${n*10}, not ${n}.`],[`${tens+ones} ones`,`Adding the digits does not describe the place-value build.`]])},
 To120Numeric:(r)=>{const n=choose(r,[60,70,80,90,100,110]);return num(C,`${n} + 10 = ?`,n+10,[[n+1,`That adds one instead of ten.`],[n,`That does not make the ten-jump.`]])},
 To120Mcq:(r)=>mcq(r,C,`Counting by ones, what comes right after 100?`,['101',`Correct — one more than 100 is 101.`],[['110',`That is ten more than the starting number, not one more.`],['99',`That number comes immediately before 100, not immediately after it.`],['100',`That repeats the starting number.`]])
};

const S='g1-shapes-measure';
const shapes:Record<string,{dim:'2D'|'3D',sides?:number,corners?:number,faces?:number,edges?:number,curved?:number}>={triangle:{dim:'2D',sides:3,corners:3},square:{dim:'2D',sides:4,corners:4},rectangle:{dim:'2D',sides:4,corners:4},circle:{dim:'2D',sides:0,corners:0},cube:{dim:'3D',faces:6,edges:12,curved:0},cone:{dim:'3D',faces:1,edges:1,curved:1},cylinder:{dim:'3D',faces:2,edges:2,curved:1},sphere:{dim:'3D',faces:0,edges:0,curved:1}};
const shapeHandlers:Record<string,Handler>={
 Smg12D3DMcq:(r)=>{const name=choose(r,Object.keys(shapes)),d=shapes[name].dim;return mcq(r,S,`Is a ${name} 2D or 3D?`,[d,`Correct — a ${name} is classified as ${d} from its visible dimensions.`],[[d==='2D'?'3D':'2D',`A ${name} ${d==='2D'?'is flat':'has length, width, and height'}, so it is ${d}.`],['Both',`This object is classified as ${d}.`],['Neither',`It is a standard ${d} shape.`]])},
 Smg12D3DNumeric:(r)=>{const name=choose(r,['cube','cone','cylinder','sphere'] as const),s=shapes[name],ask=choose(r,['faces','curved'] as const),ans=ask==='faces'?s.faces!:s.curved!;return num(S,`How many ${ask==='faces'?'flat faces':'curved surfaces'} does a ${name} have?`,ans,[[ans+1,`That counts one surface too many.`],[Math.max(0,ans-1),`That misses one of the surfaces.`]])},
 Smg1HalvesFractionBar:(r)=>fractionBar(r,S,2), Smg1FourthsFractionBar:(r)=>fractionBar(r,S,4),
 Smg1HalvesNumeric:(r)=>{const x=choose(r,['circle','sandwich','paper strip','pizza','cracker','ribbon'] as const);return num(S,`If a ${x} is split into halves, how many equal parts are there?`,2,[[1,`One part is the whole, not halves.`],[4,`Four equal parts are fourths.`]])},
 Smg1FourthsNumeric:(r)=>{const x=choose(r,['circle','sandwich','paper strip','pizza','cracker','ribbon'] as const);return num(S,`If a ${x} is split into fourths, how many equal parts are there?`,4,[[2,`Two equal parts are halves.`],[1,`One part is the unsplit whole.`]])},
 Smg1HalvesMcq:(r)=>mcq(r,S,`A shape is split into 2 equal parts. What is each part called?`,['A half',`Correct — each of two equal parts is a half.`],[['A fourth',`A fourth is one of four equal parts.`],['A whole',`The whole is the entire unsplit shape.`],['An unequal part',`The parts are stated to be equal.`]]),
 Smg1FourthsMcq:(r)=>mcq(r,S,`A shape is split into 4 equal parts. What is each part called?`,['A fourth',`Correct — each of four equal parts is a fourth.`],[['A half',`A half is one of two equal parts.`],['A whole',`The whole is the entire shape.`],['A third',`Thirds come from three equal parts.`]]),
 Smg1HalvesFourthsNumeric:(r)=>{const x=choose(r,['circle','sandwich','paper strip','pizza','cracker','ribbon'] as const);return num(S,`For the same-size ${x}, how many fourths make one half?`,2,[[1,`One fourth is smaller than one half.`],[4,`Four fourths make a whole.`]])},
 Smg1HalvesFourthsMcq:(r)=>mcq(r,S,`Which is smaller: a half or a fourth?`,['A fourth',`Correct — splitting a whole into more equal parts makes smaller pieces.`],[['A half',`A half is larger because only two equal pieces make the whole.`],['They are equal',`Two fourths equal one half, so one fourth is smaller.`],['It depends on color',`Fraction size depends on equal partitioning, not color.`]]),
 Smg1LengthDifferenceNumeric:(r,b)=>{const short=pick(r,2,hi(b,5,7,9)),diff=pick(r,1,5),long=short+diff;return num(S,`A marker is ${long} cubes long and a crayon is ${short} cubes long. How many more cubes long is the marker?`,diff,[[long+short,`That adds both lengths instead of finding the difference.`],[short,`That repeats the shorter length.`]])},
 // Added for g1m-03-02/k3 (S327 A6 redesign: numeric -> mcq, "same count, different-size unit,
 // is it the same length?" -- a genuinely different concept from LengthDifferenceNumeric above,
 // not just a surface change of it, so it gets its own name rather than a "...Mcq" suffix on that
 // one). Correct answer always names the object measured in the bigger unit as longer.
 Smg1UnitSizeCompareMcq:(r)=>{const count=pick(r,4,9),pairs=[['crayon','clip','pencil','cube'],['ribbon','block','string','bead'],['stick','hand-span','rope','footstep']] as const,[nameBig,unitBig,nameSmall,unitSmall]=choose(r,pairs);return mcq(r,S,`A ${nameBig} is ${count} ${unitBig}s long. A ${nameSmall} is ${count} ${unitSmall}s long, and a ${unitBig} is bigger than a ${unitSmall}. Are the ${nameBig} and the ${nameSmall} the same length?`,[`No — the ${nameBig} is longer`,`Correct — each ${unitBig} covers more length than a ${unitSmall}, so ${count} ${unitBig}s covers more length than ${count} ${unitSmall}s.`],[[`Yes — both counts are ${count}`,`Same count, but a ${unitBig} covers more length than a ${unitSmall}, so equal counts do not mean equal length.`],[`No — the ${nameSmall} is longer`,`The ${unitBig} is the bigger unit here, so the bigger length belongs to the ${nameBig}, not the ${nameSmall}.`],[`Cannot tell from the counts`,`You can tell without remeasuring: the count made of the bigger unit covers more length, even though the numbers match.`]])},
 Smg1ShapeSidesNumeric:(r)=>{const name=choose(r,['triangle','square','rectangle','circle'] as const),ask=r()<0.5?'sides':'corners',ans=shapes[name][ask]!;return num(S,`How many ${ask} does a ${name} have?`,ans,[[ans+1,`That counts one too many.`],[Math.max(0,ans-1),`That count misses one ${ask==='sides'?'side':'corner'} of the visible shape.`]])},
 Smg1ShapeSidesMcq:(r)=>{const target=choose(r,['triangle','circle'] as const),s=shapes[target];return mcq(r,S,`Which shape has ${s.sides} sides and ${s.corners} corners?`,[target[0].toUpperCase()+target.slice(1),`Correct — a ${target} has ${s.sides} sides and ${s.corners} corners.`],Object.keys(shapes).filter(x=>shapes[x].dim==='2D'&&x!==target).slice(0,3).map(x=>[x[0].toUpperCase()+x.slice(1),`A ${x} has ${shapes[x].sides} sides and ${shapes[x].corners} corners.`] as [string,string]))},
 Smg1SolidPartsNumeric:(r)=>{const name=choose(r,['cube','cone','cylinder','sphere'] as const),ask=choose(r,['faces','edges'] as const),ans=shapes[name][ask]??0;return num(S,`How many ${ask==='faces'?'flat faces':'edges'} does a ${name} have?`,ans,[[ans+1,`That counts one too many.`],[Math.max(0,ans-1),`That count misses one visible part of the solid.`]])},
 Smg1SolidPartsMcq:(r)=>mcq(r,S,`Which solid has 6 flat faces and no curved surface?`,['Cube',`Correct — a cube has six flat square faces.`],[['Sphere',`A sphere has one curved surface and no flat faces.`],['Cone',`A cone has one flat face and one curved surface.`],['Cylinder',`A cylinder has two flat faces and one curved surface.`]])
};

const T='g1-tens-ones';
const tensHandlers:Record<string,Handler>={
 TnoAddTensNumeric:(r,b)=>{const n=pick(r,10,hi(b,59,79,89)),t=pick(r,1,Math.min(3,Math.floor((99-n)/10)));return num(T,`${n} + ${t*10} = ?`,n+t*10,[[n+t,`That adds ${t} ${t===1?"one":"ones"} instead of ${t} ${t===1?"ten":"tens"}.`],[n,`That forgets to add the tens.`]])},
 TnoBlocksNumeric:(r)=>{const t=pick(r,1,9),o=pick(r,0,9);return num(T,`${t} ${t===1?"ten-rod":"ten-rods"} and ${o} ${o===1?"one-cube":"one-cubes"} show what number?`,10*t+o,[[10*o+t,`That reverses rods and cubes.`],[t+o,`That adds the digits instead of using place value.`]])},
 TnoDigitValueNumeric:(r)=>{const t=pick(r,1,9);let o=pick(r,0,9);if(o===t)o=(o+1)%10;const askT=r()<0.5,n=10*t+o,ans=askT?t*10:o;return num(T,`In ${n}, what is the value of the ${askT?t:o}?`,ans,[[askT?t:o,`That gives the digit, not its place value.`],[askT?o:t*10,`That uses the other digit's value.`]])},
 TnoExpandNumeric:(r)=>{const t=pick(r,1,9),o=pick(r,0,9);return num(T,`${10*t+o} = ${10*t} + ?`,o,[[t,`That uses the number of tens, not the ones value.`],[10*o,`The ones digit is worth ${o}, not ${10*o}.`]])},
 TnoReadExpandedNumeric:(r)=>{const t=pick(r,1,9),o=pick(r,0,9);return num(T,`What number is ${10*t} + ${o}?`,10*t+o,[[t+o,`That adds the digits without preserving the tens value.`],[10*o+t,`That reverses the places.`]])},
 TnoTenBundleNumeric:(r)=>{const t=pick(r,1,9);return num(T,`How many ones are the same as ${t} ${t===1?"ten":"tens"}?`,10*t,[[t,`That gives the number of tens, not equivalent ones.`],[t+10,`Each ten contributes ten ones, so multiply by ten.`]])},
 TnoTenMoreLessNumeric:(r)=>{const n=pick(r,20,89),more=r()<0.5;return num(T,`${n} ${more?'+':'−'} 10 = ?`,n+(more?10:-10),[[n+(more?1:-1),`That changes by one instead of ten.`],[n,`That leaves the number unchanged.`]])},
 TnoTensOnesNumeric:(r)=>{const t=pick(r,1,9),o=pick(r,0,9),ask=r()<0.5?'tens':'ones';return num(T,`How many ${ask} are in ${10*t+o}?`,ask==='tens'?t:o,[[ask==='tens'?o:t,`That uses the other place-value digit.`],[10*t+o,`That is the whole number, not the number of ${ask}.`]])}
};
const D='g1-data';
// Category counts are drawn distinct so most/fewest is single-valued; totals stay within the
// Grade-1 add-within-20 range wherever the form asks for arithmetic.
const cats3=(r:Rand):[string[],number[]]=>{const names=shuffle(r,['Cats','Dogs','Fish','Birds','Frogs'] as const).slice(0,3);const a=pick(r,5,8),b=pick(r,2,a-1),c=pick(r,0,b-1);const counts=shuffle(r,[a,b,c]);return[[...names],counts]};
const dataHandlers:Record<string,Handler>={
 GdTotalNumeric:(r)=>{const[nm,ct]=cats3(r);const t=ct[0]+ct[1]+ct[2];return num(D,`Votes: ${nm[0]} ${ct[0]}, ${nm[1]} ${ct[1]}, ${nm[2]} ${ct[2]}. How many votes in all?`,t,[[ct[0]+ct[1],`That adds only the first two categories and leaves out ${nm[2]}. "In all" means every category counts toward the total.`],[Math.max(...ct),`That is the biggest single category, not the total. Add all three counts together.`]])},
 GdCompareNumeric:(r)=>{const[nm,ct]=cats3(r);const i=ct.indexOf(Math.max(...ct)),j=ct.indexOf(Math.min(...ct));return num(D,`Votes: ${nm[0]} ${ct[0]}, ${nm[1]} ${ct[1]}, ${nm[2]} ${ct[2]}. How many more votes does ${nm[i]} have than ${nm[j]}?`,ct[i]-ct[j],[[ct[i]+ct[j],`That adds the two categories. "How many more" asks for the difference, so subtract the smaller count from the larger.`],[ct[i],`That is ${nm[i]}'s whole count. The question asks how far ahead it is, which is the difference between the two counts.`]])},
 GdMostMcq:(r)=>{const[nm,ct]=cats3(r);const i=ct.indexOf(Math.max(...ct));const rest=[0,1,2].filter(x=>x!==i);return mcq(r,D,`Votes: ${nm[0]} ${ct[0]}, ${nm[1]} ${ct[1]}, ${nm[2]} ${ct[2]}. Which got the MOST votes?`,[nm[i],`Correct — ${ct[i]} is the biggest count, so ${nm[i]} got the most votes.`],rest.map(x=>[nm[x],`${nm[x]} got ${ct[x]} votes, and ${ct[i]} is bigger. The most votes means the biggest count.`] as [string,string]))},
 GdLeastMcq:(r)=>{const[nm,ct]=cats3(r);const i=ct.indexOf(Math.min(...ct));const rest=[0,1,2].filter(x=>x!==i);return mcq(r,D,`Votes: ${nm[0]} ${ct[0]}, ${nm[1]} ${ct[1]}, ${nm[2]} ${ct[2]}. Which got the FEWEST votes?`,[nm[i],`Correct — ${ct[i]} is the smallest count, so ${nm[i]} got the fewest votes.`],rest.map(x=>[nm[x],`${nm[x]} got ${ct[x]} votes, and ${ct[i]} is smaller. The fewest votes means the smallest count.`] as [string,string]))},
 GdTallyReadNumeric:(r)=>{const g=pick(r,1,3),sg=pick(r,1,4);return num(D,`A tally row shows ${g} crossed five-${g===1?'group':'groups'} and ${sg} single ${sg===1?'mark':'marks'}. How many does it count?`,5*g+sg,[[g+sg,`That counts each crossed group as one mark, but a crossed group holds FIVE marks. Count the groups by fives, then add the singles.`],[5*g,`That counts only the five-groups and skips the single marks after them. Count on from ${5*g} by ones.`]])},
 GdTallyMakeNumeric:(r)=>{const n=pick(r,6,19);return num(D,`${n} students voted. When you tally the votes in five-groups, how many CROSSED groups will there be?`,Math.floor(n/5),[[n,`That is the whole count of votes. Each crossed group bundles five of them; the question asks how many full bundles fit.`],[n%5===Math.floor(n/5)?n-1:n%5,`That is the number of leftover single marks after the five-groups, not the number of crossed groups.`]])},
 GdTallySinglesNumeric:(r)=>{let n=pick(r,6,19);if(n%5===0)n+=1;if(n%5===Math.floor(n/5))n+=1;return num(D,`${n} students voted. After the crossed five-groups, how many SINGLE marks will the tally show?`,n%5,[[Math.floor(n/5),`That is the number of crossed five-groups, not the leftover single marks.`],[n,`That is the whole count. Only the marks left over after bundling fives stand alone.`]])},
 GdNotCategoryNumeric:(r)=>{const[nm,ct]=cats3(r);const t=ct[0]+ct[1]+ct[2];return num(D,`${t} answers were sorted: ${nm[0]} ${ct[0]}, ${nm[1]} ${ct[1]}, ${nm[2]} ${ct[2]}. How many are NOT ${nm[0]}?`,t-ct[0],[[ct[0],`That is the count that IS ${nm[0]}. "Not ${nm[0]}" means everything in the other categories.`],[t,`That is the whole collection. Take away the ${nm[0]} count to find what is left.`]])},
 GdQuestionMcq:(r)=>{const topic=choose(r,['pets','fruits','colors','sports'] as const);const q={pets:'Which pet do you like best?',fruits:'Which fruit do you like best?',colors:'Which color do you like best?',sports:'Which sport do you like best?'}[topic];return mcq(r,D,`A class wants to collect data about favorite ${topic}. Which is a good survey question?`,[q,`Correct — it asks every person for one answer that can be sorted into categories and counted.`],[['Do you like things?',`That question is too vague to sort — the answers would not fall into countable categories about ${topic}.`],['What is 3 + 4?',`That is an arithmetic problem with one right answer, not a survey question that collects different people's choices.`],[`Why is the sky blue?`,`That asks for an explanation, not a choice that can be tallied into categories.`]])},
 GdSortMcq:(r)=>{const kind=choose(r,[['a red apple','color','Red things',['Round things','Round describes the apple\u2019s shape, and this sort goes by COLOR \u2014 check what color it is first.'],['Big things','Big describes size, not color. The sorting rule here asks only about the color.']],['a toy car','what it does','Things that roll',['Things that fly','A toy car rolls on its wheels \u2014 it has no wings and cannot fly.'],['Things that swim','A toy car has wheels for rolling, not fins for swimming.']],['a triangle','shape','Shapes with 3 sides',['Shapes with 4 sides','A triangle has exactly 3 sides \u2014 one short of this group\u2019s rule.'],['Round shapes','Every side of a triangle is straight; nothing about it is round.']]] as const);return mcq(r,D,`You are sorting by ${kind[1]}. Where does ${kind[0]} belong?`,[kind[2],`Correct — sorted by ${kind[1]}, ${kind[0]} matches this group's rule.`],[[kind[3][0],kind[3][1]],[kind[4][0],kind[4][1]]])},
 GdInterpretMcq:(r)=>{const[nm,ct]=cats3(r);const i=ct.indexOf(Math.max(...ct)),j=ct.indexOf(Math.min(...ct));return mcq(r,D,`Votes: ${nm[0]} ${ct[0]}, ${nm[1]} ${ct[1]}, ${nm[2]} ${ct[2]}. Which sentence tells the data's story truthfully?`,[`${nm[i]} got the most votes`,`Correct — ${ct[i]} is the biggest count, so that sentence matches the data.`],[[`${nm[j]} got the most votes`,`${nm[j]} got ${ct[j]} votes — the SMALLEST count. The data says the opposite.`],[`Every category got the same votes`,`The three counts are all different, so no two categories tied.`],[`${nm[i]} got the fewest votes`,`${nm[i]} has the biggest count, ${ct[i]}. It got the most, not the fewest.`]])},
 GdBarCompareNumeric:(r)=>{const h=pick(r,4,9),d=pick(r,1,3);return num(D,`On a bar graph, the Dogs bar reaches ${h}. The Cats bar is ${d} shorter. How tall is the Cats bar?`,h-d,[[h+d,`That makes the Cats bar TALLER by ${d}. "Shorter" means the bar reaches a smaller number.`],[h,`That is the Dogs bar's height. The Cats bar is ${d} below it.`]])},
};
function fam(tag:string,label:string,handlers:Record<string,Handler>):VariantGen{const forms=Object.keys(handlers);return{tag,label,forms:forms as any,gen:(r,b='core',f='default')=>{const key=f==='default'?forms[0]:f;const h=handlers[key];if(!h)throw new Error(`unknown ${tag} form ${key}`);return h(r,b)}} as VariantGen}
export const G1_GENERATORS:readonly VariantGen[]=[fam(D,'Grade 1 data: sorting, tallying, and reading category counts',dataHandlers),fam(A,'Grade 1 addition and subtraction within 20',addHandlers),fam(C,'Grade 1 counting and place-value patterns through 120',countHandlers),fam(S,'Grade 1 shapes, fractions, solids, and measurement',shapeHandlers),fam(T,'Grade 1 tens-and-ones arithmetic and representation',tensHandlers)];
export const G1_FORM_SURFACES:Readonly<Record<string,string>>=Object.fromEntries([...Object.keys(dataHandlers),...Object.keys(addHandlers),...Object.keys(countHandlers),...Object.keys(shapeHandlers),...Object.keys(tensHandlers)].map(f=>[f,f.endsWith('Mcq')?'mcq':f.endsWith('Numeric')?'numeric':f.endsWith('NumberLineHop')?'numberLineHop':f.endsWith('BaseTenCompose')?'baseTenCompose':f.endsWith('FractionBar')?'fractionBar':'unknown']));
