type Band = "support" | "core" | "stretch";
type Variant = { tag: string; widget: any; answer: any };
type VariantGen = { tag: string; label: string; forms?: readonly never[]; gen: (rand:()=>number, band?:Band, form?:string)=>Variant };
type Rand=()=>number; type Handler=(r:Rand,b:Band)=>Variant;
const pick=(r:Rand,a:number,b:number)=>a+Math.floor(r()*(b-a+1));
const choose=<T>(r:Rand,xs:readonly T[])=>xs[pick(r,0,xs.length-1)];
const hi=(b:Band,s:number,c:number,t:number)=>b==='support'?s:b==='stretch'?t:c;
function shuffle<T>(r:Rand,xs:readonly T[]){const a=[...xs];for(let i=a.length-1;i;i--){const j=pick(r,0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function traps(answer:number,vals:Array<[number,string]>){const seen=new Set([answer]),out:Array<[number,string]>=[];for(const x of vals)if(Number.isFinite(x[0])&&!seen.has(x[0])){seen.add(x[0]);out.push(x)}for(let d=1;out.length<2;d++)if(!seen.has(answer+d)){seen.add(answer+d);out.push([answer+d,`That is ${d} more than the requested value. Recheck each visible quantity and operation.`])}return out.slice(0,3)}
const num=(tag:string,prompt:string,answer:number,errs:Array<[number,string]>,success?:string):Variant=>({tag,answer,widget:{type:'numeric',prompt,answer,tolerance:0,unit:'',commonErrors:traps(answer,errs).map(([value,feedback])=>({value,feedback})),fallbackFeedback:'Use the visible quantities and relationship, then recompute one step at a time.',successFeedback:success??`Correct — the requested value is ${answer}.`}});
const gridRead=(tag:string,prompt:string,rows:number,cols:number,errs:Array<[number,string]>,success?:string):Variant=>{const answer=rows*cols,seen=new Set([answer]),reachable:Array<[number,string]>=[];for(const [count,feedback] of errs)if(Number.isInteger(count)&&count>0&&count<answer&&!seen.has(count)){seen.add(count);reachable.push([count,feedback])}for(let d=1;reachable.length<2&&d<answer;d++){const count=answer-d;if(count>0&&!seen.has(count)){seen.add(count);reachable.push([count,`That is ${d} ${d===1?'square':'squares'} short of the complete grid. Count the remaining unit squares.`])}}return{tag,answer,widget:{type:'areaModel',prompt,targetArea:answer,wMax:cols,hMax:rows,wStart:cols,hStart:rows,countGrid:true,commonCounts:reachable.slice(0,3).map(([count,feedback])=>({count,feedback})),successFeedback:success??`Correct — ${rows} rows of ${cols} squares make ${answer} in all.`,lowFeedback:'Keep marking every square in every row.',highFeedback:'The fixed grid has no more squares than the ones shown.'}}};
const mcq=(r:Rand,tag:string,prompt:string,correct:[string,string],wrong:Array<[string,string]>):Variant=>{const seen=new Set([correct[0]]),ws=wrong.filter(x=>!seen.has(x[0])&&seen.add(x[0]));for(const f of [['A different choice','That choice does not match the visible quantities or relationship.'],['There is not enough information','The prompt gives enough information to decide.']] as Array<[string,string]>)if(ws.length<3&&!seen.has(f[0])){seen.add(f[0]);ws.push(f)}const options=shuffle(r,[{label:correct[0],feedback:correct[1],correct:true},...ws.slice(0,3).map(([label,feedback])=>({label,feedback,correct:false}))]).map((o,i)=>({id:`o${i}`,...o}));return{tag,answer:options.find(o=>o.correct)!.id,widget:{type:'mcq',prompt,options}}};
const words1to99=(n:number):string=>{const one=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'];const tens=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];return n<20?one[n]:tens[Math.floor(n/10)]+(n%10?` ${one[n%10]}`:'')};
const words=(n:number):string=>n<100?words1to99(n):`${words1to99(Math.floor(n/100))} hundred${n%100?` ${words1to99(n%100)}`:''}`;
const plural=(n:number,s:string,p=s+'s')=>n===1?s:p;

const A='g2-add-subtract-100';
const addHandlers:Record<string,Handler>={
 Add2DigitNumeric:(r,b)=>{const a=pick(r,21,hi(b,49,69,79)),c=pick(r,12,Math.min(99-a,hi(b,39,49,69)));return num(A,`${a} + ${c} = ?`,a+c,[[a+c-10,'That misses one ten from the sum. Add tens and ones carefully.'],[a+c-1,'That is one less than the total. Recheck the ones.']])},
 Add2DigitMcq:(r)=>{const at=pick(r,2,6),ao=pick(r,1,8),bt=pick(r,1,3),bo=pick(r,1,9-ao),a=10*at+ao,b=10*bt+bo;return mcq(r,A,`Which split correctly solves ${a} + ${b}?`,[`${at*10} + ${bt*10} and ${ao} + ${bo}`,`Correct — combine tens with tens and ones with ones.`],[[`${at} + ${bt} and ${ao} + ${bo}`,'The tens digits represent tens, not single ones.'],[`${at*10} + ${bo} and ${ao} + ${bt*10}`,'That mixes a tens part with an ones part.'],[`${a} − ${b}`,'That changes the operation from addition to subtraction.']])},
 AddOnesNumeric:(r)=>{const a=pick(r,21,89),d=pick(r,1,Math.min(9,99-a));return num(A,`${a} + ${d} = ?`,a+d,[[a,'That leaves the starting number unchanged. Add the ones.'],[a+10*d,'That treats each added one as a ten.']])},
 AddOnesMcq:(r)=>{const a=pick(r,21,89),d=pick(r,1,Math.min(9,99-a)),ans=a+d;return mcq(r,A,`${a} + ${d} = ?`,[String(ans),`Correct — adding ${d} ${plural(d,'one')} gives ${ans}.`],[[String(a),`That leaves out the ${d} added ones. Count them onto the starting number.`],[String(a+10*d),'That adds tens instead of ones.'],[String(ans-1),'That stops one count too soon.']])},
 AddTensNumeric:(r)=>{const a=10*pick(r,1,7),b=10*pick(r,1,9-a/10);return num(A,`${a} + ${b} = ?`,a+b,[[a/10+b/10,'That adds the tens digits as ones. Each digit names a group of ten.'],[a+b-10,'That misses one group of ten.']])},
 AddTensMcq:(r)=>{const a=10*pick(r,1,6),b=10*pick(r,1,9-a/10),ans=a+b;return mcq(r,A,`${a} + ${b} = ?`,[String(ans),`Correct — ${a/10} ${plural(a/10,'ten')} plus ${b/10} ${plural(b/10,'ten')} is ${ans/10} ${plural(ans/10,'ten')}.`],[[String(a/10+b/10),'That gives the number of tens, not the value.'],[String(ans-10),'That is one ten too small. Recount all groups of ten.'],[String(Math.abs(a-b)),'That subtracts instead of adding.']])},
 ChooseStepsNumeric:(r)=>{const start=pick(r,35,75),away=pick(r,8,Math.min(25,start-10)),back=pick(r,4,20),ans=start-away+back;return num(A,`Start with ${start} pencils. Subtract ${away}, then add ${back}. How many pencils now?`,ans,[[start-away,`That stops after the first step. Add ${back} next.`],[start-away-back,`The final step adds ${back}; it does not subtract it.`]])},
 ChooseStepsMcq:(r)=>{const large=pick(r,45,89),small=pick(r,20,large-5),diff=large-small;return mcq(r,A,`${large} stamps and ${small} stamps. Which equation finds how many more the larger collection has?`,[`${large} − ${small} = ${diff}`,`Correct — “how many more” asks for the difference.`],[[`${large} + ${small} = ${large+small}`,'Addition finds the combined total, not the difference.'],[`${small} − ${large}`,'This reverses the comparison.'],[`${large} − 1 = ${large-1}`,'Subtracting one does not compare both collections.']])},
 DoublesNumeric:(r,b)=>{const a=pick(r,4,hi(b,8,9,10));return num(A,`${a} + ${a} = ?`,2*a,[[a,'That names one addend instead of doubling it.'],[2*a-1,'That is one less than the double.']])},
 DoublesMcq:(r)=>{const a=pick(r,4,9),b=a+1;return mcq(r,A,'Which expression is a double?',[`${a} + ${a}`,`Correct — a double adds the same number to itself.`],[[`${a} + ${b}`,'The addends differ, so this is a near double.'],[`${a} − ${a}`,'A double uses addition, not subtraction.'],[`${a} + 2`,'Adding two is not necessarily doubling.']])},
 Fluency20Numeric:(r)=>{const a=pick(r,4,10),b2=pick(r,2,Math.min(10,20-a));return num(A,`${a} + ${b2} = ?`,a+b2,[[a+b2-1,'That stops one count too soon.'],[Math.abs(a-b2),'That finds a difference instead of a sum.']])},
 Fluency20Mcq:(r)=>{const a=pick(r,8,9),b2=pick(r,2,6),left=b2-(10-a);return mcq(r,A,`What is the fastest strategy for ${a} + ${b2}?`,[`Make 10, then add ${left}`,`Correct — use ${10-a} to make ten, then add the ${left} left over.`],[[`Count every object from 1`,'That can work, but it ignores a faster known-fact strategy.'],[`Subtract ${b2} from ${a}`,'That changes addition into subtraction.'],[`Double ${b2}`,'Doubling the smaller addend does not represent this sum.']])},
 NearDoublesNumeric:(r)=>{const a=pick(r,4,9),b2=a+1;return num(A,`${a} + ${b2} = ?`,a+b2,[[2*a,'That uses the nearby double but forgets to add one.'],[2*b2,'That doubles the larger addend without subtracting one.']])},
 NearDoublesMcq:(r)=>{const a=pick(r,4,8),b2=a+1;return mcq(r,A,`Which double helps solve ${a} + ${b2}?`,[`${a} + ${a}`,`Correct — double ${a} is one less than ${a}+${b2}.`],[[`${b2} + ${b2}`,'That double is one more than the target, not the closest lower double used here.'],[`${a} + ${b2}`,'That is the original near-double fact, not a double.'],[`${a-1} + ${a-1}`,'That double is too far from the target.']])},
 OddEvenMcq:(r)=>{const e=2*pick(r,6,45),o=e+(r()<0.5?-1:1),o2=e+(r()<0.5?-3:3);return mcq(r,A,'Which number is even?',[String(e),`Correct — ${e} can be paired with no leftover.`],[[String(o),`${o} leaves one unpaired, so it is odd.`],[String(o2),`${o2} leaves one unpaired, so it is odd.`]])},
 OddEvenOddEvenPairs:(r,b)=>{let n=pick(r,8,hi(b,20,70,120));if(n<10)n+=10;const answer=n%2?'odd':'even';return{tag:A,answer,widget:{type:'oddEvenPairs',prompt:`Is ${n} odd or even? Pair the ones digit, then choose.`,n,mode:n<=20?'pair':'onesDigit',answer,...(answer==='odd'?{evenFeedback:`${n} leaves one unpaired, so it is odd rather than even.`}:{oddFeedback:`${n} pairs completely, so it is even rather than odd.`}),unfinishedFeedback:'Finish pairing the visible chips before choosing odd or even.',successFeedback:`Correct — pairing the ones shows that ${n} is ${answer}.`}}},
 ParitySumNumeric:(r)=>{const a=pick(r,2,9),b2=pick(r,2,9),ans=a+b2;return num(A,`${a} + ${b2} = ? First predict odd or even, then add.`,ans,[[ans%2?ans-1:ans+1,'That has the opposite parity. Recheck the ones after adding.'],[Math.abs(a-b2),'That subtracts the addends instead of adding them.']])},
 ParitySumMcq:(r)=>mcq(r,A,'Every double, such as 7 + 7, is always…',['even','Correct — two equal groups can be paired completely.'],[['odd','A double has no unpaired item, so it is even.'],['sometimes odd','The parity rule does not change with the doubled number.'],['zero','Only doubling zero gives zero.']]),
 RegroupAddNumeric:(r,b)=>{const a=pick(r,27,hi(b,58,69,79));let c=pick(r,16,Math.min(89,99-a));if(a%10+c%10<10)c+=10-(a%10+c%10);if(a+c>99)c-=10;const ans=a+c;return num(A,`${a} + ${c} = ?`,ans,[[ans-10,'That forgot the new ten made by the ones.'],[ans-1,'That miscounted the regrouped ones by one.']])},
 Sub2DigitMcq:(r)=>{const a=pick(r,64,98),b2=pick(r,21,a-10),ans=a-b2,at=Math.floor(a/10),ao=a%10,bt=Math.floor(b2/10),bo=b2%10;return mcq(r,A,`Which split correctly solves ${a} − ${b2}?`,[`${at*10} − ${bt*10} and ${ao} − ${bo}`,`Correct — subtract tens from tens and ones from ones when no trade is needed.`],[[`${at} − ${bt} and ${ao} − ${bo}`,'The tens digits stand for groups of ten.'],[`${at*10} + ${bt*10} and ${ao} + ${bo}`,'That changes subtraction into addition.'],[`${a} − ${ans}`,'That uses the answer as a subtrahend instead of decomposing the given subtraction.']])},
 SubOnesMcq:(r)=>{const a=pick(r,31,99),d=pick(r,1,Math.min(9,a%10||9)),ans=a-d;return mcq(r,A,`${a} − ${d} = ?`,[String(ans),`Correct — subtracting ${d} ${plural(d,'one')} gives ${ans}.`],[[String(a),'That does not subtract anything.'],[String(a-10*d),'That subtracts tens instead of ones.'],[String(ans+1),'That stops one count too soon.']])},
 SubTensMcq:(r)=>{const a=10*pick(r,4,9),d=10*pick(r,1,a/10-1),ans=a-d;return mcq(r,A,`${a} − ${d} = ?`,[String(ans),`Correct — subtract ${d/10} ${plural(d/10,'ten')} from ${a/10} ${plural(a/10,'ten')}.`],[[String(a/10-d/10),'That gives the number of tens, not their value.'],[String(a+d),'That adds instead of subtracting.'],[String(ans+10),'That subtracts one ten too few.']])},
 TwoStepTradeNumeric:(r)=>{const start=pick(r,45,85),out=pick(r,16,Math.min(38,start-10)),back=pick(r,8,25),ans=start-out+back;return num(A,`Start with ${start} stickers. Subtract ${out}, then add ${back}. How many stickers now?`,ans,[[start-out,`That stops after subtracting ${out}. Add ${back} next.`],[start-out-back,`The last step adds ${back}; it does not subtract it.`]])},
 TwoStepTradeMcq:(r)=>{const tens=10*pick(r,5,9),sub=pick(r,21,48);return mcq(r,A,`For ${tens} − ${sub}, what must happen in the ones place?`,['Break one ten into 10 ones','Correct — zero ones cannot subtract the ones in the second number, so trade one ten.'],[['Subtract the larger ones digit from the smaller','That reverses the subtraction instead of regrouping.'],['Add the ones digits','The operation is subtraction, so the ones are not added.'],['Do nothing to the tens','Trading one ten changes both the tens and ones places.']])},
 UnbundleSubMcq:(r)=>{const a=10*pick(r,4,9)+pick(r,0,4),b2=10*pick(r,1,3)+pick(r,a%10+1,9);return mcq(r,A,`When solving ${a} − ${b2}, when do we break a ten?`,['When the top ones are fewer than the bottom ones','Correct — regroup when the ones place cannot subtract directly.'],[['Whenever the numbers have two digits','Two-digit subtraction does not always require regrouping.'],['When the top tens are larger','Larger tens do not determine whether the ones need a trade.'],['Only when the answer is odd','Parity does not decide whether regrouping is needed.']])}
};

const M='g2-measure-money-time';
const coinNames:Record<number,string>={1:'penny',5:'nickel',10:'dime',25:'quarter'};
const coinPlurals:Record<number,string>={1:'pennies',5:'nickels',10:'dimes',25:'quarters'};
const centWord=(n:number)=>`${n} ${n===1?'cent':'cents'}`;
const measureHandlers:Record<string,Handler>={
 MmtBarGraphNumeric:(r)=>{const n=pick(r,2,12);return num(M,`A bar reaches ${n} on a graph where each gridline is worth 1. What value does the bar show?`,n,[[n-1,'That stops one gridline below the top of the bar.'],[n+1,'That counts one gridline beyond the bar.']])},
 MmtBestUnitMcq:(r)=>{const item=choose(r,[['pencil','inches'],['hallway','feet'],['crayon','centimeters'],['classroom','meters']] as const);return mcq(r,M,`Which unit is best for measuring the length of a ${item[0]}?`,[item[1],`Correct — ${item[1]} are a sensible-sized unit for a ${item[0]}.`],[[item[1]==='inches'?'miles':'inches','That unit is poorly sized for this object.'],[item[1]==='meters'?'centimeters':'kilometers','That unit would make the measurement awkward or unrealistic.'],['cups','Cups measure capacity, not length.']])},
 MmtCoinNameMcq:(r)=>{const value=choose(r,[1,5,10,25] as const),name=coinNames[value];return mcq(r,M,`Which coin is worth ${centWord(value)}?`,[name,`Correct — a ${name} is worth ${centWord(value)}.`],Object.entries(coinNames).filter(([v])=>+v!==value).map(([v,n])=>[n,`A ${n} is worth ${centWord(+v)}, not ${value}.`] as [string,string]))},
 MmtCoinReverseMoneyBoard:(r,b)=>{const cents=choose(r,[1,5,10,25] as const),count=pick(r,2,hi(b,6,8,10)),target=cents*count,label=coinNames[cents];const wrong1=Math.max(0,target-cents),wrong2=target+cents;return{tag:M,answer:{[cents]:count},widget:{type:'moneyBoard',mode:'compose',prompt:`Build ${target} cents using only ${plural(count,label,coinPlurals[cents])}.`,targetCents:target,tray:[{cents,label,max:count+2}],commonTotals:[{cents:wrong1,feedback:`That is one ${label} short. Add ${centWord(cents)}.`},{cents:wrong2,feedback:`That is one ${label} too many. Remove ${centWord(cents)}.`}].filter(x=>x.cents>0),countFeedback:`The number of coins is not the same as their cent value. Each ${label} is worth ${centWord(cents)}.`,lowFeedback:`The tray total is below ${target} cents. Add another ${label}.`,highFeedback:`The tray total is above ${target} cents. Remove a ${label}.`,successFeedback:`Correct — ${count} ${plural(count,label,coinPlurals[cents])} make ${target} cents.`}}},
 MmtEstimateMcq:(r)=>{const [item,target]=choose(r,[['crayon',6],['key',4],['notebook',11],['spoon',7]] as const);return mcq(r,M,`A ${item} is about ${target} inches long. Which is the best estimate?`,[`${target} inches`,`Correct — ${target} inches is a reasonable estimate for a ${item}.`],[[`${Math.max(2,target-4)} inches`,'That estimate is much too short for the described object.'],[`${target+8} inches`,'That estimate is much too long for the described object.'],[`${target} feet`,'Feet make the estimate far too large.']])},
 MmtGraphCompareNumeric:(r)=>{const a=pick(r,3,10),b2=a+pick(r,1,7);return num(M,`Monday has ${a} votes and Tuesday has ${b2} votes. How many more votes are on Tuesday?`,b2-a,[[a+b2,'That adds both bars instead of finding their difference.'],[a,'That repeats Monday’s value rather than the gap.']])},
 MmtLengthCompareMcq:(r)=>{const names=shuffle(r,['key','book','phone'] as const),lens=shuffle(r,[pick(r,3,5),pick(r,7,9),pick(r,11,13)]),longer=r()<0.5;const idx=longer?lens.indexOf(Math.max(...lens)):lens.indexOf(Math.min(...lens));return mcq(r,M,`${names.map((n,i)=>`The ${n} is ${lens[i]} inches`).join(', ')}. Which is ${longer?'longest':'shortest'}?`,[names[idx],`Correct — ${lens[idx]} inches is the ${longer?'greatest':'least'} length.`],names.filter((_,i)=>i!==idx).map((n,i)=>[n,'Compare the stated inch measurements before choosing.'] as [string,string]))},
 MmtLengthDifferenceNumeric:(r)=>{const short=pick(r,3,10),long=short+pick(r,1,8);return num(M,`One object is ${long} inches long and another is ${short} inches long. How many inches longer is the first object?`,long-short,[[long+short,'That adds both lengths instead of finding the difference.'],[short,'That repeats the shorter length.']])},
 MmtLinePlotNumeric:(r)=>{const value=pick(r,2,10),count=pick(r,2,12);return num(M,`A line plot shows ${count} X marks above ${value}. How many data points are at ${value}?`,count,[[value,'That gives the data value, not the frequency above it.'],[count-1,'That misses one X mark. Count every mark above the value.']])},
 // S237 — was MmtPictureGraphNumeric, which generated a bare `numeric` widget for a prompt about a
 // picture graph. Repairing the authored steps alone would have restored the defect the moment a
 // learner re-asked the item, so the generator draws the row it asks about. Singular/plural forms are
 // stored, never derived: the old handler printed "1 apple pictures" on every seed where count === 1.
 MmtPictureGraphRead:(r)=>{const count=pick(r,0,12),day=choose(r,['Monday','Tuesday','Friday','Saturday'] as const);
  const pics=count===1?'apple picture':'apple pictures';
  const results:Array<{value:number;feedback:string}>=[{value:count+1,feedback:'That counts one picture beyond the row. Touch each picture exactly once as you count.'}];
  if(count>0)results.push({value:count-1,feedback:'That misses one picture in the row. Sweep the whole row before settling the marker.'});
  return{tag:M,answer:count,widget:{type:'graphRead',mode:'picture',prompt:`A picture graph shows ${count} ${pics} for ${day}. Each picture equals 1 vote. How many votes is that?`,drawn:count,unitValue:1,categoryLabel:day,unitNoun:'vote',unitNounPlural:'votes',scaleMax:count+3,icon:'\u{1F34E}',commonResults:results,fallbackFeedback:'Count the pictures one at a time \u2014 each picture stands for exactly one vote.',successFeedback:count===1?'Correct \u2014 one picture, and each picture is one vote, so the row shows 1 vote.':`Correct \u2014 ${count} pictures, each worth one vote, so the row shows ${count} votes.`}}},
 MmtRulerReadNumeric:(r)=>{const start=pick(r,0,4),len=pick(r,2,9),end=start+len;return num(M,`An object starts at ${start} and ends at ${end} on an inch ruler. How long is it?`,len,[[end,'That reads the ending mark instead of subtracting the starting mark.'],[end+start,'That adds the endpoints instead of finding the distance between them.']])},
 MmtRulerSubtractNumeric:(r)=>{const start=pick(r,1,6),len=pick(r,3,10),end=start+len;return num(M,`An object starts at ${start} and ends at ${end} on a centimeter ruler. How long is it?`,len,[[end,'That uses the endpoint as the length. Subtract the starting mark.'],[start+end,'That adds the marks rather than finding their distance apart.']])},
 MmtSkip5sNumeric:(r)=>{const mark=pick(r,1,11);return num(M,`The minute hand points to ${mark}. How many minutes past the hour is that?`,mark*5,[[mark,'That reads the clock number without multiplying by five minutes.'],[mark*5+5,'That counts one extra five-minute interval.']])},
 MmtUnitFitMcq:(r)=>{const [item,unit]=choose(r,[['classroom','meters'],['hand','inches'],['playground','yards'],['paper clip','centimeters']] as const);return mcq(r,M,`Which unit is best for measuring the length of a ${item}?`,[unit,`Correct — ${unit} fit the size of a ${item}.`],[[unit==='meters'?'centimeters':'miles','That unit is poorly sized for the object.'],['liters','Liters measure capacity, not length.'],['minutes','Minutes measure time, not length.']])}
};

const P='g2-place-value-1000';
const placeHandlers:Record<string,Handler>={
 Pv1000AddByPlaceNumeric:(r)=>{const a=100*pick(r,1,4)+10*pick(r,1,5)+pick(r,1,4),b2=100*pick(r,1,4)+10*pick(r,1,3)+pick(r,1,4),ans=a+b2;return num(P,`${a} + ${b2} = ?`,ans,[[ans-100,'That misses one hundred from the sum.'],[ans-10,'That misses one ten from the sum.']])},
 Pv1000AddTradeNumeric:(r)=>{const a=pick(r,145,589),b2=pick(r,126,Math.min(399,999-a));const ans=a+b2;return num(P,`${a} + ${b2} = ?`,ans,[[ans-100,'That loses a regrouped hundred.'],[ans-10,'That loses a regrouped ten.']])},
 Pv1000BuildNumberNumeric:(r)=>{const h=pick(r,1,9),t=pick(r,0,9),o=pick(r,0,9),ans=100*h+10*t+o;return num(P,`What number has ${h} ${plural(h,'hundred')}, ${t} ${plural(t,'ten')}, and ${o} ${plural(o,'one')}?`,ans,[[100*o+10*t+h,'That reverses the hundreds and ones digits.'],[h+t+o,'That adds the digits instead of using place value.']])},
 Pv1000CountForwardNumeric:(r,b)=>{const step=choose(r,[5,10,100] as const),times=pick(r,2,hi(b,3,4,5)),start=step===100?100*pick(r,1,5):step*pick(r,20,hi(b,80,120,160)),ans=start+step*times;return num(P,`Count forward from ${start} by ${step}s, ${times} times. What number do you land on?`,ans,[[start+step*(times-1),'That stops one jump too soon.'],[start+times,'That adds the number of jumps instead of the jump size.']])},
 Pv1000DigitWorthNumeric:(r)=>{const h=pick(r,1,9),t=pick(r,0,9),o=pick(r,0,9),places=shuffle(r,[['hundreds',h,100*h],['tens',t,10*t],['ones',o,o]] as const).filter(x=>x[1]!==0),[place,digit,ans]=places[0],n=100*h+10*t+o;return num(P,`In ${n}, what is the value of the ${digit} in the ${place} place?`,ans,[[digit,'That gives the digit, not its place value.'],[place==='hundreds'?10*digit:place==='tens'?100*digit:10*digit,'That places the digit in the wrong column.']])},
 Pv1000MixedNumeric:(r)=>r()<0.5?placeHandlers.Pv1000BuildNumberNumeric(r,'core'):placeHandlers.Pv1000DigitWorthNumeric(r,'core'),
 Pv1000OrderMixedMcq:(r)=>{const a=pick(r,100,999),b2=r()<0.2?a:Math.max(100,Math.min(999,a+choose(r,[-70,-9,-1,1,8,60] as const))),sym=a<b2?'<':a>b2?'>':'=';return mcq(r,P,`Compare ${a} and ${b2}. Which symbol is correct?`,[sym,`Correct — comparing place values shows that ${a} ${sym} ${b2}.`],[['<',`Compare hundreds, then tens, then ones.`],['=',`The numbers are equal only when every digit matches.`],['>',`Compare hundreds, then tens, then ones.`]])},
 Pv1000OrderMixedNumeric:(r)=>{const n=pick(r,100,999);return num(P,`What number is “${words(n)}”?`,n,[[Math.floor(n/100)*100+n%10,'That omits the tens value from the word form.'],[Number(String(n).split('').reverse().join('')),'That reverses the place-value digits.']])},
 Pv1000ReadWordsNumeric:(r)=>placeHandlers.Pv1000OrderMixedNumeric(r,'core'),
 Pv1000RealworldNumeric:(r)=>{const add=r()<0.5,a=pick(r,230,650),b2=pick(r,105,Math.min(add?999-a:a-50,349)),ans=add?a+b2:a-b2;return num(P,`${a} ${add?'+':'−'} ${b2} = ?`,ans,[[add?ans-100:ans+100,'That mishandles one hundred during the calculation.'],[add?ans-10:ans+10,'That mishandles one ten during the calculation.']])},
 Pv1000SkipFivesNumeric:(r)=>{const start=5*pick(r,40,190);return num(P,`Skip-count by 5s: ${start}, ${start+5}, ${start+10}, ___?`,start+15,[[start+10,'That repeats the last shown number instead of making the next jump.'],[start+20,'That skips one number in the sequence.']])},
 Pv1000SkipHundredsNumeric:(r)=>{const start=100*pick(r,1,6);return num(P,`Skip-count by 100s: ${start}, ${start+100}, ${start+200}, ___?`,start+300,[[start+200,'That repeats the last shown number.'],[start+210,'That adds ten instead of one hundred.']])},
 Pv1000SkipTensNumeric:(r)=>{const start=10*pick(r,15,85);return num(P,`Skip-count by 10s: ${start}, ${start+10}, ${start+20}, ___?`,start+30,[[start+20,'That repeats the last shown number.'],[start+21,'That adds one instead of ten.']])},
 Pv1000SubtractByPlaceNumeric:(r)=>{const a=100*pick(r,4,9)+10*pick(r,4,9)+pick(r,4,9),b2=100*pick(r,1,3)+10*pick(r,1,3)+pick(r,1,3),ans=a-b2;return num(P,`${a} − ${b2} = ?`,ans,[[ans+100,'That subtracts one hundred too few.'],[ans+10,'That subtracts one ten too few.']])},
 Pv1000SubtractTradeNumeric:(r)=>{const b2=pick(r,125,389),a=pick(r,b2+100,899),ans=a-b2;return num(P,`${a} − ${b2} = ?`,ans,[[ans+100,'That misses a traded hundred.'],[ans+10,'That misses a traded ten.']])},
 Pv1000TradingNumeric:(r)=>placeHandlers.Pv1000BuildNumberNumeric(r,'core'),
 Pv1000WriteWordsBuildExpression:(r)=>{const h=pick(r,1,9),t=pick(r,0,9),o=pick(r,0,9),n=100*h+10*t+o,labels=words(n).split(' '),pool=[...new Set([...labels,words1to99((t===9?8:t+1)*10).split(' ')[0],words1to99(o===9?8:o+1)])];const tokens=shuffle(r,pool).map((label,i)=>({id:`t${i}`,label})),id=(label:string)=>tokens.find(x=>x.label===label)!.id,correct=labels.map(id);const wrongA=labels.length>2?[id(labels[0]),id('hundred')]:[correct[0]];const alt=pool.find(x=>!labels.includes(x))!;const reusable=new Set(correct).size!==correct.length;return{tag:P,answer:correct,widget:{type:'buildExpression',prompt:`Build ${n} in word form from the tiles.`,tokens,correct,acceptAlso:[],reusable,commonBuilds:[{sequence:[...correct.slice(0,-1),id(alt)],feedback:'That final word does not match the tens or ones digit in the number.'},{sequence:wrongA,feedback:'That build leaves out a needed place-value word.'}].filter(x=>x.sequence.join('|')!==correct.join('|')),missFeedback:`Read ${n} from hundreds to ones and place only the words that name its nonzero places.`,successFeedback:`Correct — ${n} is “${words(n)}.”`}}}
};

const S='g2-shapes-shares';
const shapeNames:Record<number,string>={3:'triangle',4:'quadrilateral',5:'pentagon',6:'hexagon',7:'heptagon',8:'octagon'};
const shareName=(d:number)=>d===2?'a half':d===3?'a third':'a fourth';
const shapeHandlers:Record<string,Handler>={
 Ssg2CompareSharesMcq:(r)=>{const pair=choose(r,[[2,4],[3,4],[2,3]] as const),smaller=r()<0.5,den=smaller?Math.max(...pair):Math.min(...pair),name=shareName(den);return mcq(r,S,`Which is ${smaller?'smaller':'bigger'}: ${shareName(pair[0])} or ${shareName(pair[1])}?`,[name,`Correct — for equal wholes, ${smaller?'more equal parts make smaller pieces':'fewer equal parts make bigger pieces'}.`],[[shareName(den===2?3:2),'Compare pieces from equal-sized wholes.'],['They are equal','The denominators describe different piece sizes.']])},
 Ssg2GridApplyNumeric:(r,b)=>{const rows=pick(r,2,hi(b,4,6,8)),cols=pick(r,2,hi(b,5,7,9));return num(S,`A rectangle has ${rows} rows and ${cols} columns of unit squares. How many unit squares are there?`,rows*cols,[[rows+cols,'That adds rows and columns instead of counting every row-column intersection.'],[rows*cols-cols,'That leaves out one full row.']])},
 Ssg2GridApplyRead:(r,b)=>{const rows=pick(r,2,hi(b,4,6,8)),cols=pick(r,2,hi(b,5,7,9));return gridRead(S,`A rectangle has ${rows} rows and ${cols} columns of unit squares. How many unit squares are there?`,rows,cols,[[rows+cols,'That adds rows and columns instead of counting every row-column intersection.'],[rows*cols-cols,'That leaves out one full row.']])},
 Ssg2NameAnyMcq:(r)=>{const sides=pick(r,3,8),name=shapeNames[sides];return mcq(r,S,`A shape has ${sides} sides. What is it called?`,[name,`Correct — a ${name} has ${sides} sides.`],Object.entries(shapeNames).filter(([n])=>+n!==sides).slice(0,3).map(([n,x])=>[x,`A ${x} has ${n} sides, not ${sides}.`] as [string,string]))},
 Ssg2NameAnyTapDiagram:(r)=>{const sides=choose(r,[3,5,6,8] as const),correct=shapeNames[sides],others=shuffle(r,Object.values(shapeNames).filter(x=>x!==correct)).slice(0,2),labels=shuffle(r,[correct,...others]);const hotspots=labels.map((label,i)=>({id:`h${i}`,x:17+33*i,y:50,label,icon:label==='triangle'?'🔺':label==='pentagon'?'⬟':label==='hexagon'?'⬢':'🔷',count:1,correct:label===correct,...(label===correct?{}:{feedback:`A ${label} does not have ${sides} sides. Count its sides and try again.`})}));return{tag:S,answer:hotspots.filter(x=>x.correct).map(x=>x.id),widget:{type:'tapDiagram',mode:'selectOne',prompt:`Tap the shape with ${sides} sides.`,canvas:{w:3,h:1},hotspots,missFeedback:`Count the sides of each shape and select the one with exactly ${sides}.`,successFeedback:`Correct — the ${correct} has ${sides} sides.`}}},
 Ssg2NameThirdFractionBar:(r)=>{const den=3,start=choose(r,[1,2,4,5,6] as const);return{tag:S,answer:{n:1,d:3},widget:{type:'fractionBar',notation:'words',showTarget:false,prompt:'Split the bar into 3 equal parts so each part is a third.',targetNum:1,targetDen:3,numMin:1,numMax:1,denMin:1,denMax:6,numStart:1,denStart:start,commonFractions:[{num:1,den:2,feedback:'Two equal parts make halves, not thirds.'},{num:1,den:4,feedback:'Four equal parts make fourths, not thirds.'}],successFeedback:'Correct — three equal parts make each part a third.',highFeedback:'Those pieces are too large. Split the whole into exactly three equal parts.',lowFeedback:'Those pieces are too small. Use exactly three equal parts.'}}},
 Ssg2NameThirdMcq:(r)=>{const den=choose(r,[2,3] as const),name=den===2?'a half':'a third';return mcq(r,S,`A whole is split into ${den} equal parts. What is each part called?`,[name,`Correct — one of ${den} equal parts is ${name}.`],[[den===2?'a third':'a half',`That name uses a different number of equal parts.`],['a fourth','A fourth requires four equal parts.'],['a whole','A whole is the unsplit object, not one part.']])},
 Ssg2PyramidNumeric:(r)=>{const solid=choose(r,['square pyramid','triangular pyramid'] as const),ask=choose(r,['edges','faces','vertices'] as const),counts=solid==='square pyramid'?{edges:8,faces:5,vertices:5}:{edges:6,faces:4,vertices:4},ans=counts[ask];return num(S,`How many ${ask} does a ${solid} have?`,ans,[[ans-1,`That count misses one ${ask==='vertices'?'corner':ask.slice(0,-1)}.`],[ans+1,`That count includes one extra ${ask==='vertices'?'corner':ask.slice(0,-1)}.`]])},
 Ssg2PyramidTapDiagram:(r)=>{const labels=shuffle(r,['square pyramid','cube','cylinder'] as const);const hotspots=labels.map((label,i)=>({id:`h${i}`,x:17+33*i,y:50,label,icon:label==='square pyramid'?'🔺':label==='cube'?'🧊':'🥫',count:1,correct:label==='square pyramid',...(label==='square pyramid'?{}:{feedback:`A ${label} does not have triangular faces meeting at one top point.`})}));return{tag:S,answer:hotspots.filter(x=>x.correct).map(x=>x.id),widget:{type:'tapDiagram',mode:'selectOne',prompt:'Tap the solid whose faces meet at one point on top.',canvas:{w:3,h:1},hotspots,missFeedback:'Look for a pyramid with triangular faces meeting at one top vertex.',successFeedback:'Correct — a square pyramid has faces that meet at one top vertex.'}}},
 Ssg2ShapeVocabMcq:(r)=>shapeHandlers.Ssg2NameAnyMcq(r,'core'),
 Ssg2ShapeVocabNumeric:(r)=>{const sides=pick(r,3,8),name=shapeNames[sides];return num(S,`How many sides does a ${name} have?`,sides,[[sides-1,`That count misses one side of the ${name}.`],[sides+1,`That count includes one extra side.`]])},
 Ssg2ThirdsCountMcq:(r)=>{const equal=r()<0.5;return mcq(r,S,`A whole is cut into 3 ${equal?'equal':'different-sized'} pieces. Are the pieces thirds?`,[equal?'Yes':'No',equal?'Correct — three equal pieces are thirds.':'Correct — thirds must be three equal pieces.'],[[equal?'No':'Yes',equal?'The three pieces are equal, so each is a third.':'Different-sized pieces are not thirds.']])},
 Ssg2ThirdsCountNumeric:(r)=>{const whole=choose(r,['circle','sandwich','ribbon','paper strip','pizza','cracker'] as const);return num(S,`If the ${whole} is split into thirds, how many equal parts are there?`,3,[[2,'Two equal parts are halves, not thirds.'],[4,'Four equal parts are fourths, not thirds.']])}
};

const F='g2-fluency';
// Additive fact-family key: always "min+max", so 7+8, 8+7, 15-7 and 15-8 all name ONE family.
// Mirrors factFluency.ts's sumFamilyKey exactly; kept local so this generator file stays
// dependency-free like every other g*Variants module.
const sfam=(a:number,b:number)=>`${Math.min(a,b)}+${Math.max(a,b)}`;
// Every numeric fluency form carries its family so the lesson player folds the result into the
// learner's per-family leech box (Profile.factItems), not just the conceptTag mastery estimate.
const numF=(prompt:string,answer:number,errs:Array<[number,string]>,family:string,success?:string):Variant=>{
 const v=num(F,prompt,answer,errs,success) as Variant & {factFamily?:string};
 v.factFamily=family; return v;
};
const fluencyHandlers:Record<string,Handler>={
 FlDoublesNumeric:(r,b)=>{const a=pick(r,2,hi(b,7,9,10));return numF(`${a} + ${a} = ?`,2*a,[[a,`That names one addend instead of doubling it — a double adds ${a} to itself.`],[2*a-1,`That is one short of the double. Count on ${a} from ${a}: ${2*a}.`]],sfam(a,a),`Correct — double ${a} is ${2*a}: ${a} and another ${a} together.`)},
 FlNearDoublesNumeric:(r,b)=>{const a=pick(r,2,hi(b,6,8,9));const c=a+1;return numF(`${a} + ${c} = ?`,a+c,[[2*a,`That doubles ${a}, but the second addend is ${c} — one MORE than ${a}, so the total is one more too.`],[2*c,`That doubles ${c}, but the first addend is ${a} — one LESS than ${c}.`]],sfam(a,c),`Correct — double ${a} is ${2*a}, and one more makes ${a+c}.`)},
 FlMakeTenNumeric:(r)=>{const a=pick(r,6,9);const c=pick(r,Math.max(2,11-a),9);const need=10-a;return numF(`${a} + ${c} = ? (Make ten first.)`,a+c,[[10,`That stops at ten. After using ${need} to make ten, ${c-need} still remain to add.`],[a+c-1,`That stops one short. ${a} + ${need} = 10, then ${c-need} more makes ${a+c}.`]],sfam(a,c),`Correct — ${a} + ${need} makes ten, then ${c-need} more gives ${a+c}.`)},
 FlTenPlusNumeric:(r,b)=>{const c=pick(r,1,hi(b,7,9,10));const on=c===1?'one':'ones';return numF(`10 + ${c} = ?`,10+c,[[c,`That leaves out the ten. Ten plus ${c} keeps the ten and adds ${c} ${on}.`],[10,`That leaves out the ${c}. Ten plus ${c} is ${10+c}.`]],sfam(10,c),`Correct — ten and ${c} more is ${10+c}, written as a ten and ${c} ${on}.`)},
 FlSums12Numeric:(r)=>{const t=pick(r,9,12);const a=pick(r,3,t-3);const c=t-a;return numF(`${a} + ${c} = ?`,t,[[t-1,`That stops one short. Count on ${c} from ${a} and land on ${t}.`],[Math.abs(a-c),`That finds the difference between ${a} and ${c} instead of their total.`]],sfam(a,c),`Correct — ${a} + ${c} = ${t}: count on ${c} from ${a}.`)},
 FlSums16Numeric:(r)=>{const t=pick(r,13,16);const a=pick(r,4,Math.min(9,t-4));const c=t-a;return numF(`${a} + ${c} = ?`,t,[[t-1,`That stops one short of ${t}. Make ten first, then add what is left.`],[Math.abs(a-c),`That subtracts instead of adding.`]],sfam(a,c),`Correct — ${a} + ${c} = ${t}: count on ${c} from ${a}.`)},
 FlSums20Numeric:(r)=>{const t=pick(r,17,20);const a=pick(r,8,Math.min(10,t-8));const c=t-a;return numF(`${a} + ${c} = ?`,t,[[t-1,`That stops one short of ${t}. Make ten from ${a}, then add the rest.`],[t-10,`That drops a whole ten from the total.`]],sfam(a,c),`Correct — ${a} + ${c} = ${t}: count on ${c} from ${a}.`)},
 FlFromTenNumeric:(r)=>{const c=pick(r,1,9);return numF(`10 − ${c} = ?`,10-c,[[c,`That repeats the number taken away instead of what is left.`],[10,`That leaves the ten unchanged — ${c} must come off it.`]],sfam(c,10-c),`Correct — 10 − ${c} = ${10-c}, since ${c} + ${10-c} = 10.`)},
 FlAcrossTenNumeric:(r)=>{const total=pick(r,12,18);const c=pick(r,total-10+1,9);return numF(`${total} − ${c} = ?`,total-c,[[total-10,`That takes away ten instead of ${c}.`],[total-c+1,`That is one too many left — check by adding back: ${c} + ${total-c} = ${total}.`]],sfam(c,total-c),`Correct — ${total} − ${c} = ${total-c}. Take ${total-10} to reach ten, then ${c-(total-10)} more.`)},
 FlThinkAdditionNumeric:(r)=>{const a=pick(r,3,9);const c=pick(r,3,Math.min(9,20-a));const t=a+c;return numF(`${t} − ${a} = ? Think: ${a} + ? = ${t}.`,c,[[t,`That repeats the total. The question asks what is LEFT after ${a} comes off.`],[a,`That repeats the part taken away instead of the part remaining.`]],sfam(a,c),`Correct — ${a} + ${c} = ${t}, so ${t} − ${a} = ${c}.`)},
 FlFactFamilyNumeric:(r)=>{const a=pick(r,3,9);const c=pick(r,3,Math.min(9,20-a));const t=a+c;const askSub=r()<0.5;
  if(askSub)return numF(`Fact family ${a}, ${c}, ${t}: knowing ${a} + ${c} = ${t}, what is ${t} − ${c}?`,a,[[t,`That repeats the total instead of removing ${c} from it.`],[c,`That repeats ${c} instead of the other part of the family.`]],sfam(a,c),`Correct — the family's parts are ${a} and ${c}, so ${t} − ${c} = ${a}.`);
  return numF(`Fact family ${a}, ${c}, ${t}: knowing ${a} + ${c} = ${t}, what is ${c} + ${a}?`,t,[[Math.abs(a-c),`That subtracts the parts. Addition commutes, so the total is unchanged.`],[t-1,`The order of the parts does not change the total: it is still ${t}.`]],sfam(a,c),`Correct — addition commutes: ${c} + ${a} = ${a} + ${c} = ${t}.`)},
 FlMissingNumeric:(r)=>{const a=pick(r,3,9);const c=pick(r,3,Math.min(9,20-a));const t=a+c;return numF(`${a} + ? = ${t}`,c,[[t,`That repeats the total instead of the missing part.`],[t+a,`That adds ${a} again instead of finding what fills the gap to ${t}.`]],sfam(a,c),`Correct — ${a} + ${c} = ${t}: count on ${c} from ${a}.`)},
 FlSpeedAddNumeric:(r)=>{const a=pick(r,2,10);const c=pick(r,2,Math.min(10,20-a));return numF(`Answer fast: ${a} + ${c} = ?`,a+c,[[a+c-1,`That stops one count short of the total — count on again from ${a}.`],[Math.abs(a-c),`That finds the difference between ${a} and ${c} instead of their total.`]],sfam(a,c),`Correct — ${a} + ${c} = ${a+c}.`)},
 FlSpeedSubNumeric:(r)=>{const total=pick(r,10,20);const c=pick(r,1,Math.min(10,total-1));return numF(`Answer fast: ${total} − ${c} = ?`,total-c,[[total,`That repeats the total instead of taking ${c} away.`],[total-c+1,`That leaves one too many — check by adding back.`]],sfam(c,total-c),`Correct — ${total} − ${c} = ${total-c}.`)},
};
function fam(tag:string,label:string,handlers:Record<string,Handler>):VariantGen{const forms=Object.keys(handlers);return{tag,label,forms:forms as any,gen:(r,b='core',f='default')=>{const key=f==='default'?forms[0]:f,h=handlers[key];if(!h)throw new Error(`unknown ${tag} form ${key}`);return h(r,b)}} as VariantGen}
export const G2_GENERATORS:readonly VariantGen[]=[fam(F,'Grade 2 addition and subtraction fluency within 20',fluencyHandlers),fam(A,'Grade 2 addition and subtraction within 100',addHandlers),fam(M,'Grade 2 measurement, money, time, and data',measureHandlers),fam(P,'Grade 2 place value through 1,000',placeHandlers),fam(S,'Grade 2 shapes, arrays, and equal shares',shapeHandlers)];
