import { describe, expect, it } from "vitest";
import { PointSetReasoningLabSpec, WidgetSpec, pointSetReasoningChoiceCorrect, pointSetReasoningExplorationKeys, pointSetReasoningTruth, widgetIntegrityErrors } from "./schema";
import { evaluate } from "./evaluate";
const range=PointSetReasoningLabSpec.parse({type:"pointSetReasoningLab",task:"rangeValue",answerMode:"numeric",prompt:"Find the range.",xLabel:"value",sets:[{id:"d",label:"data",points:[{id:"a",label:"2",x:2},{id:"b",label:"5",x:5},{id:"c",label:"10",x:10}]}],targetSetId:"d",choices:[],numericErrors:[{value:10,feedback:"maximum only"}],authoredStages:[],requiredStageKeys:["range:min","range:max","range:span"],requiredExplorations:3,successFeedback:"8",explorationFeedback:"inspect",fallbackFeedback:"subtract",tolerance:0});
describe("Session 150 point-set truth",()=>{
 it("remains a plain discriminated-union member",()=>expect(WidgetSpec.parse(range).type).toBe("pointSetReasoningLab"));
 it("derives range and blocks fabricated exploration",()=>{expect(pointSetReasoningTruth(range).answerNumber).toBe(8);const revealed=pointSetReasoningExplorationKeys(range);expect(evaluate(range,{revealed,numeric:8}).correct).toBe(true);expect(evaluate(range,{revealed:["fake:a","fake:b","fake:c"],numeric:8}).correct).toBe(false)});
 it("derives ordered path length",()=>{const path=PointSetReasoningLabSpec.parse({...range,task:"pathLength",sets:[{id:"p",label:"route",points:[{id:"a",label:"A",x:1,y:2},{id:"b",label:"B",x:1,y:6},{id:"c",label:"C",x:6,y:6}]}],targetSetId:"p",pathPointIds:["a","b","c"],requiredStageKeys:["point:a","point:b","path:leg:1","point:c","path:leg:2","path:total"],requiredExplorations:6,numericErrors:[]});expect(pointSetReasoningTruth(path).answerNumber).toBe(9)});
 it("keeps endpoint claims distinct from interior blindness",()=>{const choice=PointSetReasoningLabSpec.parse({...range,task:"rangeEndpoints",answerMode:"choice",choices:[{id:"ok",label:"2 and 10",claim:"range:endpoints:2:10",feedback:"yes"},{id:"bad",label:"all values",claim:"misconception:all",feedback:"no"}],numericErrors:[]});expect(choice.choices.filter(c=>pointSetReasoningChoiceCorrect(choice,c))).toHaveLength(1)});
 it("rejects missing targets and impossible stages",()=>{const broken=PointSetReasoningLabSpec.parse({...range,targetSetId:"missing",requiredStageKeys:["fake"],requiredExplorations:9});expect(widgetIntegrityErrors(broken).some(x=>x.includes("targetSetId"))).toBe(true);expect(widgetIntegrityErrors(broken).some(x=>x.includes("invalid required stage"))).toBe(true)});
});
