const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const ts=require('/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript/lib/typescript.js');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,f);
const planPath=process.argv[2];if(!planPath)throw new Error('usage: node verify.cjs <plan.json>');
const plan=JSON.parse(fs.readFileSync(planPath,'utf8')),lockPath=planPath.replace(/\.plan\.json$/,'.lock.json'),lock=JSON.parse(fs.readFileSync(lockPath,'utf8'));
const canonical=(v)=>{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().filter(k=>k!=='variant').map(k=>[k,canonical(v[k])]));return v};
const digest=(v)=>crypto.createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
const schemaPath=require.resolve('../../src/lib/schema.ts');
const mixedRegroupTruth=(s)=>{const P=s.aWhole*s.den+s.aNum,Q=(s.bWhole||0)*s.den+(s.bNum||0),T=s.mode==='convert'?P:s.mode==='add'?P+Q:P-Q;return s.mode==='convert'&&s.targetForm==='improper'?{whole:0,num:T}:{whole:Math.floor(T/s.den),num:T%s.den}};
const columnCalcTruth=(op,a,b)=>op==='add'?a+b:op==='subtract'?a-b:a*b;
require.cache[schemaPath]={id:schemaPath,filename:schemaPath,loaded:true,exports:{mixedRegroupTruth,columnCalcTruth}};
const V=require('../../src/lib/variants.ts'),{evaluate}=require('../../src/lib/evaluate.ts');
if(!plan.independentModule)throw new Error('plan.independentModule is required');
const {solvePrompt}=require(path.resolve(plan.independentModule));
const NEG=/^(no|not|wrong|incorrect|sorry|try again|nope)\b/i;
const allStrings=(x,key='',out=[])=>{if(typeof x==='string')out.push([key,x]);else if(Array.isArray(x))x.forEach((v,i)=>allStrings(v,`${key}[${i}]`,out));else if(x&&typeof x==='object')for(const [k,v] of Object.entries(x))allStrings(v,k,out);return out};
for(const t of lock.targets){const doc=JSON.parse(fs.readFileSync(`content/courses/${t.course}/lessons/${t.file}`,'utf8')),s=doc.steps.find(x=>x.id===t.stepId);assert(s,`missing locked step ${t.course}/${t.file}/${t.stepId}`);assert.equal(digest(s),t.authoredHash,`authored content drift ${t.course}/${t.file}/${t.stepId}`);assert.deepStrictEqual(s.variant,{gen:t.gen,form:t.form},`declaration drift ${t.course}/${t.file}/${t.stepId}`);assert.equal(s.widget.type,t.surface);}
assert.equal(lock.targets.length,plan.expectedGaps);
const forms=[...new Map(lock.targets.map(t=>[`${t.gen}@${t.form}`,{gen:t.gen,form:t.form,surface:t.surface}])).values()];assert.equal(forms.length,Object.keys(plan.selectors).length);
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function audit(v,surface,where){const w=v.widget;assert.equal(w.type,surface,`${where} surface`);assert(typeof w.prompt==='string'&&w.prompt.length>=9,`${where} short prompt`);for(const [k,s] of allStrings(w)){if(/feedback/i.test(k)){assert(s.length>=25,`${where} short feedback: ${s}`);assert(!NEG.test(s),`${where} negative feedback: ${s}`);}assert(!/undefined|\bNaN\b|\bInfinity\b|\$\{[A-Za-z_]/.test(s),`${where} suspicious string: ${s}`);assert(!/\b1 (groups|places|minutes|units|wholes|ones|tens|hundreds|stars|hearts|dots|buttons|hops|times)\b/i.test(s),`${where} grammar: ${s}`);}
 if(surface==='numeric'){assert.equal(v.answer,w.answer);assert(Number.isFinite(w.answer));assert(w.commonErrors.length>=2);const vals=w.commonErrors.map(e=>e.value);assert.equal(new Set(vals.map(x=>Number(x).toPrecision(14))).size,vals.length,`${where} duplicate traps`);for(const e of w.commonErrors)assert(Math.abs(e.value-w.answer)>w.tolerance,`${where} trap=answer`);}
 else if(surface==='mcq'){assert(w.options.length>=3);assert.equal(w.options.filter(o=>o.correct).length,1);assert.equal(new Set(w.options.map(o=>o.label)).size,w.options.length);assert.equal(new Set(w.options.map(o=>o.id)).size,w.options.length);assert.equal(v.answer,w.options.find(o=>o.correct).id);}
 else if(surface==='rationalCompare')assert(['lt','eq','gt'].includes(v.answer));
 else if(surface==='mixedRegroup'){assert.deepStrictEqual(v.answer,{...mixedRegroupTruth(w),complete:true});assert(w.commonResults.length>=1);}
 else if(surface==='columnCalc'){assert.equal(v.answer,columnCalcTruth(w.op,w.a,w.b));assert(w.commonResults.length>=1);}
 else if(surface==='subitizeFlash'){assert.equal(v.answer,w.count);assert(w.options.includes(w.count));assert.equal(new Set(w.options).size,w.options.length);assert(w.commonPicks.every(x=>x.value!==w.count));}
 else if(surface==='numberLineHop'){const land=w.start+(w.direction==='back'?-1:1)*w.hop*w.hops;assert.equal(v.answer,land);assert(land>=w.min&&land<=w.max);assert(w.commonLandings.every(x=>x.value!==land));assert.equal(new Set(w.commonLandings.map(x=>x.value)).size,w.commonLandings.length);}
 else if(surface==='tenFrame'){assert.equal(v.answer,w.target);assert(w.preFilled<w.target);assert(w.commonCounts.every(x=>x.count!==w.target));assert.equal(new Set(w.commonCounts.map(x=>x.count)).size,w.commonCounts.length);}
 else if(surface==='tapDiagram'){const ids=w.hotspots.filter(h=>h.correct).map(h=>h.id);assert.deepStrictEqual(v.answer,ids);assert.equal(new Set(w.hotspots.map(h=>h.id)).size,w.hotspots.length);assert(w.mode==='selectAll'?ids.length>=1:ids.length===1);for(const h of w.hotspots.filter(h=>!h.correct))assert(h.feedback&&h.feedback.length>=25,`${where} wrong hotspot feedback`);}
 else if(surface==='dragOrder'){assert.deepStrictEqual(v.answer,w.correctOrder);assert.equal(new Set(w.items.map(i=>i.id)).size,w.items.length);assert.equal(new Set(w.correctOrder).size,w.items.length);assert.notEqual(w.items.map(i=>i.id).join('|'),w.correctOrder.join('|'),`${where} pre-sorted`);for(const m of w.misorderFeedback){assert(w.correctOrder.indexOf(m.first)>w.correctOrder.indexOf(m.second),`${where} dead misorder`);}}
 else if(surface==='matchPairs'){assert.deepStrictEqual(v.answer,w.pairs);assert.equal(Object.keys(w.pairs).length,w.left.length);assert.equal(new Set(w.left.map(x=>x.label)).size,w.left.length);assert.equal(new Set(w.right.map(x=>x.label)).size,w.right.length);for(const pe of w.pairErrors)assert.notEqual(w.pairs[pe.left],pe.right,`${where} dead pair error`);}
 else if(surface==='dragBucket'){assert.deepStrictEqual(v.answer,Object.fromEntries(w.items.map(i=>[i.id,i.bucketId])));assert.equal(new Set(w.buckets.map(b=>b.id)).size,w.buckets.length);assert.equal(new Set(w.buckets.map(b=>b.label)).size,w.buckets.length);assert.equal(new Set(w.items.map(i=>i.id)).size,w.items.length);assert(w.buckets.every(b=>w.items.some(i=>i.bucketId===b.id)),`${where} unused bucket`);}
 else if(surface==='pointEntry'){assert.deepStrictEqual(v.answer,w.answer);assert(Array.isArray(w.answer)&&w.answer.length>=2);assert.equal(new Set(w.commonEntries.map(e=>JSON.stringify(e.values))).size,w.commonEntries.length);for(const e of w.commonEntries)assert.notDeepStrictEqual(e.values,w.answer,`${where} trap=answer`);}
 else if(surface==='plotPoint'){assert.deepStrictEqual(v.answer,w.targets);assert(w.targets.length>=1);const key=p=>`${p.x},${p.y}`;assert.equal(new Set(w.targets.map(key)).size,w.targets.length);for(const e of w.pointErrors)assert(!new Set(w.targets.map(key)).has(key(e)),`${where} point trap=answer`);}
 else if(surface==='lengthCompare'){assert.equal(v.answer,w.answerId);assert(w.items.some(i=>i.id===w.answerId));const targetShort=/shortest|shorter/i.test(w.prompt);const truth=targetShort?Math.min(...w.items.map(i=>i.length)):Math.max(...w.items.map(i=>i.length));assert.equal(w.items.find(i=>i.id===w.answerId).length,truth);if(w.mode==='align')assert(w.items.some(i=>i.startOffset>0),`${where} align begins solved`);}
 else if(surface==='baseTenCompose'){const h=Math.floor(w.target/100),t=Math.floor(w.target/10)%10,o=w.target%10;assert.deepStrictEqual(v.answer,{hundreds:h,tens:t,ones:o});assert(w.commonBuilds.every(x=>(x.hundreds??0)!==h||x.tens!==t||x.ones!==o));}
 else if(surface==='fractionBar'){assert.deepStrictEqual(v.answer,{n:w.targetNum,d:w.targetDen});assert(w.commonFractions.every(x=>x.num*w.targetDen!==x.den*w.targetNum));}
 else if(surface==='oddEvenPairs'){const truth=w.n%2?'odd':'even';assert.equal(w.answer,truth);assert.equal(v.answer,truth);assert(w.mode===(w.n<=20?'pair':'onesDigit'));}
 else if(surface==='moneyBoard'){assert(['compose','change'].includes(w.mode));const target=w.mode==='change'?w.paidCents-w.priceCents:w.targetCents;let total=0;for(const d of w.tray)total+=d.cents*(v.answer[d.cents]||0);assert.equal(total,target);assert(w.commonTotals.every(x=>x.cents!==target));}
 else if(surface==='buildExpression'){assert.deepStrictEqual(v.answer,w.correct);const ids=new Set(w.tokens.map(x=>x.id));assert(w.correct.length>0&&w.correct.every(x=>ids.has(x)));assert(w.commonBuilds.every(x=>x.sequence.join('|')!==w.correct.join('|')));}
 else if(surface==='signChart'){const roots=[...w.roots].sort((a,b)=>a.x-b.x);let sign=w.leadingPositive===false?-1:1;const truth=Array(roots.length+1).fill('+');truth[truth.length-1]=sign>0?'+':'-';for(let i=roots.length-1;i>=0;i--){if(roots[i].mult%2===1)sign*=-1;truth[i]=sign>0?'+':'-';}assert.deepStrictEqual(v.answer,truth);assert.equal(new Set(roots.map(r=>r.x)).size,roots.length);}
 else throw new Error(`unsupported target surface ${surface}`);
}
function routeInput(v){const w=v.widget;if(w.type==='mcq')return w.prompt+`||${w.options.map(o=>o.label).join(';;')}`;if(['subitizeFlash','numberLineHop','tenFrame','tapDiagram','dragOrder','dragBucket','matchPairs','pointEntry','plotPoint','lengthCompare','baseTenCompose','fractionBar','oddEvenPairs','moneyBoard','buildExpression'].includes(w.type)){
 const visible=w.type==='subitizeFlash'?{visibleCount:w.count,options:w.options,arrangement:w.arrangement}:
 w.type==='numberLineHop'?{min:w.min,max:w.max,start:w.start,hop:w.hop,hops:w.hops,direction:w.direction}:
 w.type==='tenFrame'?{preFilled:w.preFilled,target:w.target}:
 w.type==='tapDiagram'?{mode:w.mode,hotspots:w.hotspots.map(({label,icon,count})=>({label,icon,count}))}:
 w.type==='dragOrder'?{items:w.items.map(({label})=>({label}))}:
 w.type==='dragBucket'?{buckets:w.buckets.map(({label})=>({label})),items:w.items.map(({label})=>({label}))}:
 w.type==='matchPairs'?{left:w.left.map(({label})=>({label})),right:w.right.map(({label})=>({label}))}:
 w.type==='pointEntry'?{arity:w.answer.length,delimiter:w.delimiter}:
 w.type==='plotPoint'?{minX:w.minX,maxX:w.maxX,minY:w.minY,maxY:w.maxY,targets:w.targets.length}:
 w.type==='baseTenCompose'?{targetText:w.prompt}:
 w.type==='fractionBar'?{targetText:w.prompt,numMin:w.numMin,numMax:w.numMax,denMin:w.denMin,denMax:w.denMax}:
 w.type==='oddEvenPairs'?{n:w.n,mode:w.mode}:
 w.type==='moneyBoard'?{mode:w.mode,targetCents:w.targetCents,priceCents:w.priceCents,paidCents:w.paidCents,tray:w.tray}:
 w.type==='buildExpression'?{tokens:w.tokens.map(({label})=>({label}))}:
 {mode:w.mode,orientation:w.orientation,items:w.items.map(({label,length,startOffset})=>({label,length,startOffset}))};
 return w.prompt+'||'+JSON.stringify(visible);
 }
 return w.prompt;
}
function routeExpected(v){const w=v.widget;if(w.type==='mcq')return w.options.find(o=>o.correct).label;if(w.type==='tapDiagram')return w.hotspots.filter(h=>h.correct).map(h=>h.label).sort();if(w.type==='dragOrder')return w.correctOrder.map(id=>w.items.find(i=>i.id===id).label);if(w.type==='dragBucket')return Object.fromEntries(w.items.map(i=>[i.label,w.buckets.find(b=>b.id===i.bucketId).label]));if(w.type==='matchPairs')return Object.fromEntries(w.left.map(l=>[l.label,w.right.find(r=>r.id===w.pairs[l.id]).label]));if(w.type==='pointEntry')return w.answer;if(w.type==='plotPoint')return w.targets;if(w.type==='lengthCompare')return w.items.find(i=>i.id===w.answerId).label;if(w.type==='baseTenCompose')return v.answer;if(w.type==='fractionBar')return v.answer;if(w.type==='oddEvenPairs'||w.type==='moneyBoard')return v.answer;if(w.type==='buildExpression')return w.correct.map(id=>w.tokens.find(t=>t.id===id).label);return v.answer;}
let focusedBuilds=0,independentChecks=0,evaluatorBuilds=0,evaluatorAssertions=0;const VERIFY_N=Number(process.env.VERIFY_N||300),EVAL_N=Math.min(140,VERIFY_N);
for(const {gen,form,surface} of forms){for(const band of ['support','core','stretch'])for(let i=0;i<VERIFY_N;i++){
 const seed=`${plan.id}:focused:${gen}:${form}:${band}:${i}`,a=V.variantForGenForm(gen,form,seed,band),b=V.variantForGenForm(gen,form,seed,band);assert(a);assert.deepStrictEqual(a,b,`nondeterministic ${gen}@${form}`);audit(a,surface,`${gen}@${form}/${band}/${i}`);focusedBuilds++;
 const got=solvePrompt(form,routeInput(a)),expected=routeExpected(a);assert.deepStrictEqual(got,expected,`independent mismatch ${gen}@${form}/${band}/${i}: got ${JSON.stringify(got)} expected ${JSON.stringify(expected)}`);independentChecks++;
 if(i<EVAL_N){evaluatorBuilds++;const w=a.widget;
  if(w.type==='numeric'){let r=evaluate(w,w.answer);assert(r.correct);evaluatorAssertions++;for(const e of w.commonErrors){r=evaluate(w,e.value);assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='mcq'){for(const o of w.options){const r=evaluate(w,o.id);assert.equal(r.correct,o.correct);assert.equal(r.feedback,o.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='rationalCompare'){for(const x of ['lt','eq','gt']){const r=evaluate(w,x);assert.equal(r.correct,x===w.answer);evaluatorAssertions++;}}
  else if(w.type==='mixedRegroup'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;for(const e of w.commonResults){r=evaluate(w,{whole:e.whole,num:e.num,complete:true});assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='columnCalc'){let r=evaluate(w,{value:a.answer,complete:true});assert(r.correct);evaluatorAssertions++;for(const e of w.commonResults){r=evaluate(w,{value:e.value,complete:true});assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='subitizeFlash'){let r=evaluate(w,w.count);assert(r.correct);evaluatorAssertions++;for(const e of w.commonPicks){r=evaluate(w,e.value);assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='numberLineHop'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;for(const e of w.commonLandings){r=evaluate(w,e.value);assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='tenFrame'){let r=evaluate(w,w.target);assert(r.correct);evaluatorAssertions++;for(const e of w.commonCounts){r=evaluate(w,e.count);assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='tapDiagram'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;for(const h of w.hotspots.filter(h=>!h.correct)){r=evaluate(w,[h.id]);assert(!r.correct);assert.equal(r.feedback,h.feedback);evaluatorAssertions+=2;}if(w.mode==='selectAll'&&a.answer.length>1){r=evaluate(w,[a.answer[0]]);assert(!r.correct);evaluatorAssertions++;}}
  else if(w.type==='dragOrder'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;for(const m of w.misorderFeedback){const order=[...w.correctOrder],ia=order.indexOf(m.first),ib=order.indexOf(m.second);[order[ia],order[ib]]=[order[ib],order[ia]];r=evaluate(w,order);assert(!r.correct);assert.equal(r.feedback,m.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='dragBucket'){const truth=Object.fromEntries(w.items.map(i=>[i.id,i.bucketId]));let r=evaluate(w,truth);assert(r.correct);evaluatorAssertions++;const item=w.items[0],wrong=w.buckets.find(b=>b.id!==item.bucketId);r=evaluate(w,{...truth,[item.id]:wrong.id});assert(!r.correct);assert(r.feedback.includes(item.feedback));evaluatorAssertions+=2;}
  else if(w.type==='matchPairs'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;for(const pe of w.pairErrors){const links={...w.pairs,[pe.left]:pe.right};r=evaluate(w,links);assert(!r.correct);assert.equal(r.feedback,pe.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='pointEntry'){let r=evaluate(w,w.answer);assert(r.correct);evaluatorAssertions++;for(const e of w.commonEntries){r=evaluate(w,e.values);assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='plotPoint'){let r=evaluate(w,w.targets);assert(r.correct);evaluatorAssertions++;for(const e of w.pointErrors){r=evaluate(w,[{x:e.x,y:e.y}]);assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='baseTenCompose'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;for(const e of w.commonBuilds){r=evaluate(w,{hundreds:e.hundreds??0,tens:e.tens,ones:e.ones});assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='fractionBar'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;for(const e of w.commonFractions){r=evaluate(w,{n:e.num,d:e.den});assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='oddEvenPairs'){const ones=w.mode==='onesDigit'?w.n%10:w.n,paired=Math.floor(ones/2);let r=evaluate(w,{paired,choice:w.answer});assert(r.correct);evaluatorAssertions++;const wrong=w.answer==='odd'?'even':'odd';r=evaluate(w,{paired,choice:wrong});assert(!r.correct);assert.equal(r.feedback,wrong==='odd'?w.oddFeedback:w.evenFeedback);evaluatorAssertions+=2;if(ones>3){r=evaluate(w,{paired:0,choice:w.answer});assert(!r.correct);assert.equal(r.feedback,w.unfinishedFeedback);evaluatorAssertions+=2;}}
  else if(w.type==='moneyBoard'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;for(const e of w.commonTotals){const d=w.tray.find(x=>e.cents%x.cents===0&&e.cents/x.cents<=x.max);if(d){const state=Object.fromEntries(w.tray.map(x=>[x.cents,0]));state[d.cents]=e.cents/d.cents;r=evaluate(w,state);assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}}
  else if(w.type==='buildExpression'){let r=evaluate(w,w.correct);assert(r.correct);evaluatorAssertions++;for(const e of w.commonBuilds){r=evaluate(w,e.sequence);assert(!r.correct);assert.equal(r.feedback,e.feedback);evaluatorAssertions+=2;}}
  else if(w.type==='signChart'){let r=evaluate(w,a.answer);assert(r.correct);evaluatorAssertions++;const wrong=[...a.answer];wrong[0]=wrong[0]==='+'?'-':'+';r=evaluate(w,wrong);assert(!r.correct);evaluatorAssertions++;}
  else if(w.type==='lengthCompare'){let r=w.mode==='align'?evaluate(w,{offsets:Object.fromEntries(w.items.map(x=>[x.id,0])),picked:w.answerId}):evaluate(w,w.answerId);assert(r.correct);evaluatorAssertions++;for(const item of w.items.filter(x=>x.id!==w.answerId)){r=w.mode==='align'?evaluate(w,{offsets:Object.fromEntries(w.items.map(x=>[x.id,0])),picked:item.id}):evaluate(w,item.id);assert(!r.correct);assert.equal(r.feedback,w.mode==='pick' ? (item.feedback ?? w.missFeedback) : w.missFeedback);evaluatorAssertions+=2;}if(w.mode==='align'){const offsets=Object.fromEntries(w.items.map(x=>[x.id,x.startOffset]));r=evaluate(w,{offsets,picked:null});assert(!r.correct);assert.equal(r.feedback,w.unalignedFeedback);evaluatorAssertions+=2;}}
 }
}}
const coverage={};let gradeTotal=0,gradeServed=0;
for(const course of plan.courses){let total=0,served=0;for(const file of fs.readdirSync(`content/courses/${course}/lessons`).filter(x=>x.endsWith('.json'))){const d=JSON.parse(fs.readFileSync(`content/courses/${course}/lessons/${file}`,'utf8'));for(const s of d.steps||[])if(['check','challenge'].includes(s.kind)){total++;if(V.variantForStep(s,`${plan.id}:coverage:${course}:${file}:${s.id}`,'core'))served++;}}coverage[course]={total,served,gaps:total-served};assert.equal(served,total,`${course} incomplete`);gradeTotal+=total;gradeServed+=served;}
coverage.grade={total:gradeTotal,served:gradeServed,gaps:gradeTotal-gradeServed};
let overallTotal=0,overallServed=0;for(const course of fs.readdirSync('content/courses')){const dir=`content/courses/${course}/lessons`;if(!fs.existsSync(dir))continue;for(const file of fs.readdirSync(dir).filter(x=>x.endsWith('.json'))){let d;try{d=JSON.parse(fs.readFileSync(`${dir}/${file}`,'utf8'))}catch{continue}for(const s of d.steps||[])if(['check','challenge'].includes(s.kind)){overallTotal++;if(V.variantForStep(s,`${plan.id}:overall:${course}:${file}:${s.id}`,'core'))overallServed++;}}}
coverage.overall={total:overallTotal,served:overallServed,gaps:overallTotal-overallServed,percent:Number((overallServed/overallTotal*100).toFixed(2))};
const metrics={id:plan.id,targets:lock.targets.length,forms:forms.length,generators:new Set(forms.map(x=>x.gen)).size,focusedBuilds,independentChecks,evaluatorBuilds,evaluatorAssertions,coverage,status:'PASS'};
fs.writeFileSync(planPath.replace(/\.plan\.json$/,'.metrics.json'),JSON.stringify(metrics,null,2)+'\n');console.log(JSON.stringify(metrics));
