/**
 * Generates the exact arithmetic/equality claims declared by registered SVG
 * <title> elements. The renderer is the authority: no figure ID is manually
 * admitted to or omitted from this map.
 *
 * Run: npx tsx scripts/audit/generate-figure-numeric-claims.mts [--check]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { FIGURES } from "../../src/components/figures";

/*
 * The application tsconfig intentionally preserves JSX. SSR generation needs
 * the automatic React JSX transform, so the documented plain command relaunches
 * itself exactly once with the checked-in generator tsconfig. This keeps the
 * result independent of ambient/global React state and caller CLI flags.
 */
if (process.env.MAGGIES_FIGURE_SSR_COMPILED !== "1") {
  const require = createRequire(import.meta.url);
  const child = spawnSync(process.execPath, [
    require.resolve("tsx/cli"),
    "--tsconfig",
    "scripts/audit/tsconfig.figure-ssr.json",
    "scripts/audit/generate-figure-numeric-claims.mts",
    ...process.argv.slice(2),
  ], {
    cwd: process.cwd(),
    env: { ...process.env, MAGGIES_FIGURE_SSR_COMPILED: "1" },
    encoding: "utf8",
  });
  if (child.stdout) process.stdout.write(child.stdout);
  if (child.stderr) process.stderr.write(child.stderr);
  if (child.error) throw child.error;
  process.exit(child.status ?? 1);
}

const ROOT = process.cwd();
const OUT = join(ROOT, "src", "lib", "figureNumericClaims.generated.ts");

export function decodeTitle(value: string): string {
  return value
    .replace(/&minus;|&#x2212;|&#8722;/gi, "−")
    .replace(/&times;|&#xd7;|&#215;/gi, "×")
    .replace(/&divide;|&#xf7;|&#247;/gi, "÷")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#x27;|&#39;/gi, "'")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Arithmetic/equality, not mere axis ranges or isolated signed tick labels. */
export function isExactArithmeticTitle(title: string): boolean {
  const value = decodeTitle(title);
  if (!/\d/.test(value)) return false;
  const operand = String.raw`(?:\(?[−-]?\d+(?:\.\d+)?(?:\/\d+(?:\.\d+)?)?\)?|[a-z])`;
  return (
    /=|\bequals?\b/i.test(value) ||
    new RegExp(`${operand}\\s*[+×÷]\\s*${operand}`, "i").test(value) ||
    new RegExp(`${operand}\\s+[−-]\\s+${operand}`, "i").test(value) ||
    /\d\s*(?:\^\s*\d|[⁰¹²³⁴⁵⁶⁷⁸⁹])/.test(value)
  );
}


/**
 * Keep the renderer's worked arithmetic/equality assertion, not incidental
 * scale bounds or tick sequences that happen to share its <title>. Common
 * figure titles introduce the claim after "showing", "equation", "caption",
 * or a colon; taking that final authored clause also makes the generated
 * contract stable when accessible context around the claim is improved.
 */
export function extractExactArithmeticClaim(title: string): string {
  const value = decodeTitle(title);
  const introduced = [
    /\b(?:showing|shows)\s+(.+?)(?:(?:[.!?])(?=\s|$)|$)/gi,
    /\b(?:the\s+)?(?:caption|equation|formula)\s+(?:reads?|shows?)\s+(.+?)(?:(?:[.!?])(?=\s|$)|$)/gi,
    /:\s*(.+?)(?:(?:[.!?])(?=\s|$)|$)/g,
  ];
  for (const pattern of introduced) {
    const matches = [...value.matchAll(pattern)];
    for (let index = matches.length - 1; index >= 0; index -= 1) {
      const candidate = decodeTitle(matches[index][1]);
      if (isExactArithmeticTitle(candidate)) return candidate;
    }
  }

  const sentences = value.split(/(?<=[.!?])\s+/).map(decodeTitle);
  const arithmeticSentences = sentences.filter(isExactArithmeticTitle);
  if (arithmeticSentences.length) return arithmeticSentences.join(" ");
  return "";
}

export function renderFigureNumericClaims(): Record<string, string> {
  const claims: Record<string, string> = {};
  for (const id of Object.keys(FIGURES).sort()) {
    let markup: string;
    try { markup = renderToStaticMarkup(createElement(FIGURES[id])); }
    catch (error) { throw new Error(`${id}: SSR failed: ${error instanceof Error ? error.message : String(error)}`); }
    const title = decodeTitle(markup.match(/<title>([\s\S]*?)<\/title>/i)?.[1] ?? "");
    const claim = extractExactArithmeticClaim(title);
    if (claim) claims[id] = claim;
  }
  return claims;
}

export function generatedSource(claims = renderFigureNumericClaims()): string {
  const rows = Object.entries(claims).map(([id, claim]) => `  ${JSON.stringify(id)}: ${JSON.stringify(claim)},`);
  return [
    "/* AUTO-GENERATED by scripts/audit/generate-figure-numeric-claims.mts. DO NOT EDIT. */",
    "/** Exact arithmetic/equality claims extracted from live registered figure <title> elements. */",
    "export const FIGURE_NUMERIC_CLAIMS = {",
    ...rows,
    "} as const satisfies Record<string, string>;",
    "",
    "export type FigureNumericClaimId = keyof typeof FIGURE_NUMERIC_CLAIMS;",
    "",
  ].join("\n");
}

const expected = generatedSource();
if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== expected) {
    console.error(`STALE ${OUT}`);
    process.exitCode = 1;
  } else console.log(`CURRENT ${Object.keys(renderFigureNumericClaims()).length} exact arithmetic-title claims`);
} else {
  writeFileSync(OUT, expected);
  console.log(`WROTE ${OUT} (${Object.keys(renderFigureNumericClaims()).length} exact arithmetic-title claims)`);
}
