const fs=require('fs'),assert=require('assert'),ts=require('/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript/lib/typescript.js');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,f);
const V=require('../../src/lib/variants.ts');
const targets=[
['ee-01-01','k1','power-product','basicSquare','numeric'],['ee-01-01','k2','power-product','powerMeaning','mcq'],['ee-01-01','k3','power-product','tenPower','numeric'],['ee-01-01','ch1','power-product','missingPowerExponent','numeric'],
['ee-01-02','k1','power-product','basicPower','numeric'],['ee-01-02','k2','power-product','basicPower','numeric'],['ee-01-02','k3','power-product','basicPower','numeric'],['ee-01-02','ch1','power-product','comparePowers','mcq'],
['ee-01-03','k1','power-product','parenPower','numeric'],['ee-01-03','k2','grouping-first','powerMulEval','evalOrder'],['ee-01-03','k3','power-product','sumPowers','numeric'],['ee-01-03','ch1','power-product','mixedPowerOrder','numeric'],
['ee-02-03','k1','variable-meaning','lessThanPhrase','mcq'],['ee-02-03','k2','variable-meaning','twicePlusPhrase','mcq'],['ee-02-03','k3','variable-meaning','halfEval','numeric'],['ee-02-03','ch1','variable-meaning','tripleMinusEval','numeric'],
['ee-03-01','k1','distributive','variableEval','numeric'],['ee-03-01','k2','distributive','variableEquivalent','mcq'],['ee-03-01','k3','distributive','variableBoth','numeric'],['ee-03-01','ch1','distributive','variableError','numeric'],
['ee-03-02','k1','equiv-test','likeSubtract','mcq'],['ee-03-02','k2','equiv-test','claimAtValue','numeric'],['ee-03-02','k3','equiv-test','likeConstant','mcq'],['ee-03-02','ch1','equiv-test','distributeCombine','numeric'],
['ee-04-01','k1','unknown-letter','testAddSolution','mcq'],['ee-04-01','k2','unknown-letter','solveAdd','numeric'],['ee-04-01','k3','unknown-letter','equationVsExpression','mcq'],['ee-04-01','ch1','unknown-letter','chooseMulSolution','mcq'],
['ee-04-02','k1','unknown-letter','checkAddSolution','mcq'],['ee-04-02','k2','unknown-letter','solveSubtract','numeric'],['ee-04-02','k3','unknown-letter','solveSubtract','numeric'],['ee-04-02','k4','unknown-letter','feeSolve','numeric'],['ee-04-02','ch1','unknown-letter','tipSolve','numeric'],
['ee-05-01','k1','g7-tse-inequality-build','strictBoundary','mcq'],['ee-05-01','k2','g7-tse-inequality-build','inclusiveBoundary','mcq'],['ee-05-01','k3','g7-tse-inequality-build','noLargest','mcq'],['ee-05-01','ch1','g7-tse-inequality-build','atLeastBoundary','mcq'],
['ee-05-02','k1','g7-tse-inequality-build','graphDescription','mcq'],['ee-05-02','k2','g7-tse-inequality-build','graphToInequality','buildExpression'],['ee-05-02','k3','g7-tse-inequality-build','testPoint','mcq'],['ee-05-02','ch1','g7-tse-inequality-build','atMostBoundary','mcq'],
['ee-05-03','k1','variable-meaning','independentPay','mcq'],['ee-05-03','k2','variable-meaning','linearRelation','numeric'],['ee-05-03','k3','variable-meaning','independentLaps','mcq'],['ee-05-03','ch1','variable-meaning','shirtsCost','numeric'],
];
assert.equal(targets.length,45);
const NEG=/^(no|not|wrong|incorrect|sorry|try again|nope)\b/i;
function checkFeedback(x,where){assert(typeof x==='string'&&x.length>=25,`${where} short feedback: ${x}`);assert(!NEG.test(x),`${where} negating feedback: ${x}`)}
function check(v,surface,where){const w=v.widget;assert.equal(w.type,surface,`${where} surface`);assert(typeof w.prompt==='string'&&w.prompt.length>=9,`${where} prompt`);
 if(surface==='numeric'){assert.equal(v.answer,w.answer);assert(Number.isFinite(w.answer));assert(Array.isArray(w.commonErrors)&&w.commonErrors.length>=2,`${where} numeric traps`);const vals=w.commonErrors.map(e=>e.value);assert.equal(new Set(vals.map(x=>Number(x).toPrecision(14))).size,vals.length,`${where} duplicate traps`);for(const e of w.commonErrors){assert(Math.abs(e.value-w.answer)>w.tolerance,`${where} trap equals answer`);checkFeedback(e.feedback,where)}checkFeedback(w.fallbackFeedback,where);}
 else if(surface==='mcq'){assert(w.options.length>=3,`${where} options`);assert.equal(w.options.filter(o=>o.correct).length,1);assert.equal(new Set(w.options.map(o=>o.label)).size,w.options.length,`${where} duplicate labels`);assert.equal(new Set(w.options.map(o=>o.id)).size,w.options.length);assert.equal(v.answer,w.options.find(o=>o.correct).id);for(const o of w.options)checkFeedback(o.feedback,where);}
 else if(surface==='evalOrder'){assert.equal(v.answer,w.target);assert(Array.isArray(w.tokens)&&w.tokens.length>=3);assert(w.commonResults.length>=1);const vals=w.commonResults.map(x=>x.value);assert.equal(new Set(vals).size,vals.length);for(const r of w.commonResults){assert.notEqual(r.value,w.target);checkFeedback(r.feedback,where)}checkFeedback(w.fallbackFeedback,where);checkFeedback(w.successFeedback,where);}
 else if(surface==='buildExpression'){assert.deepStrictEqual(v.answer,w.correct);assert(w.tokens.length>w.correct.length,`${where} no distractor token`);const keys=[w.correct,...w.acceptAlso].map(x=>x.join('|'));assert.equal(new Set(keys).size,keys.length);for(const c of w.commonBuilds){assert(!keys.includes(c.sequence.join('|')),`${where} wrong build accepted`);checkFeedback(c.feedback,where)}checkFeedback(w.missFeedback,where);checkFeedback(w.successFeedback,where);}
 else throw new Error(`unsupported ${surface}`);
}
for(const [lesson,id,gen,form,surface] of targets){const f=`content/courses/expressions-equations/lessons/${lesson}.json`;const d=JSON.parse(fs.readFileSync(f,'utf8'));const step=d.steps.find(s=>s.id===id);assert(step,`${lesson}/${id}`);assert.deepStrictEqual(step.variant,{gen,form});assert.equal(step.widget.type,surface);}
const unique=[...new Map(targets.map(t=>[`${t[2]}@${t[3]}`,{gen:t[2],form:t[3],surface:t[4]}])).values()];
let builds=0;
for(const {gen,form,surface} of unique)for(const band of ['support','core','stretch'])for(let i=0;i<240;i++){const seed=`session80:${gen}:${form}:${band}:${i}`;const a=V.variantForGenForm(gen,form,seed,band),b=V.variantForGenForm(gen,form,seed,band);assert(a,`${gen}@${form} null`);assert.deepStrictEqual(a,b,`${gen}@${form} nondeterministic`);check(a,surface,`${gen}@${form}/${band}/${i}`);builds++;}
let total=0,served=0;for(const f of fs.readdirSync('content/courses/expressions-equations/lessons').filter(x=>x.endsWith('.json'))){const d=JSON.parse(fs.readFileSync(`content/courses/expressions-equations/lessons/${f}`,'utf8'));for(const s of d.steps||[])if(['check','challenge'].includes(s.kind)){total++;if(V.variantForStep(s,`coverage:${f}:${s.id}`,'core'))served++;}}
assert.deepStrictEqual({total,served,gaps:total-served},{total:62,served:62,gaps:0});
console.log(JSON.stringify({targets:targets.length,uniqueForms:unique.length,builds,course:{total,served,gaps:0},status:'PASS'}));
