#!/bin/bash
cd /home/claude/work/maggies-trail-session-151
cat > HANDOVER.md << 'EOF'
# HANDOVER — after S184 (151 lineage)

## State
- Tree: /home/claude/work/maggies-trail-session-151; latest tarball maggies-trail-session-184.tar.gz.
- Registry: **86 courses / 1,165 lessons** (manifest 93784f8a2ec4); tiers A 656 / B 311 / C 188 / D 10.
- S184 shipped the **hundredthsGrid engine** (full 11-surface contract, one session) and
  **decimals-intro-g4** — the second K5-expansion course: 18 lessons, ALL Tier A, generated by
  `scripts/session/build-decimals-intro-g4.mjs`, checks variant-backed by the new `g4-decimals`
  family (15 forms, gate 18/18).
- K5 spec at repo root: `k5-expansion.json` (39 courses / 490 lessons) + `K5_EXPANSION_CCSS.md`.
  Remaining to build: **37 courses / 454 lessons**.

## The reusable pattern (now twice-proven)
Course factory (per-lesson packs → 9-step A-tier shape, every number derived + asserted
abort-before-write) + generator family (per-form handlers + independent .cjs routes + band entry)
+ sessionNNN adversarial test re-deriving everything from disk. `build-decimals-intro-g4.mjs`
additionally shows: a NEW engine and its course can land in one session when the engine mirrors a
shipped sibling (hundredthsGrid mirrors probabilityArea's state/grading shape + adds direct
manipulation).

## Amended K5 build order
1. graph-construction ENGINE + data-graphs-g1 (12)   ← next; 2.MD.D.10 verb is "draw"
2. fact-fluency architecture (item-grain scheduling), then the fluency pair (30)
3. remaining K courses (100), then the rest by grade.

## Hard-won contracts (S184 additions)
- The 11-surface engine contract, measured again and unchanged: schema.ts, evaluate.ts (grade +
  canCheck + correctAnswerText), widgets.tsx (component + registry switch + REGISTERED_WIDGETS),
  widgetSamples.ts, stageWidth.ts, describeState.ts, pedagogy.ts, masteryMission.server.ts,
  processEvents.ts, engine-capabilities.json. tsc's exhaustiveness flags five of them; the other
  six are hand-maintained — sweep the newest sibling's name to find them all.
- g4 families auto-register per-form INDEPENDENT routes via the g4- manifest loop, but the
  TAG-level route (used by the 400-seed default sweep) is a SEPARATE manual entry near line 857 of
  variants.test.ts — `"g4-decimals": (p) => solveG4Prompt("dTenthsWriteNumeric", p)` (default form
  = forms[0]).
- Independent-route regexes must not eat sentence periods: `[\d.]+` on "0.35." parses NaN and a
  compare route silently answers `eq`. Anchor decimals as `\d+\.\d+`.
- rationalCompare accepts decimal-string operands `{value:"0.35"}`; the answer's own feedback slot
  must be ABSENT (gate + factory both assert it), and there is deliberately no proportional
  rendering.
- dragOrder gate arg: prompt + "||" + labels.join(",") + "||" + JSON.stringify({items:[{label}]});
  g4Independent.cjs solvePrompt now parses the third segment for *Drag forms.
- flagship-tier's wrongPathCount now counts `commonCounts` and `misorderFeedback` (authored
  misconception arrays the scorer predated). The correction moved exactly one lesson (dg4-03-04
  B→A).
- Remedials derive from k1: k1 must be numeric/mcq/rationalCompare, never dragOrder — for an
  ordering lesson the pairwise comparison IS the remedial skill.

## New-course registration surfaces (now 8, all green for S184)
course.json ↔ lessons/ ↔ PLAN.md ✅ lines (check-registration) · gen-manifest.mjs ·
content-change-proof-s151c.mjs AUTHORIZED map + anchors (now 180 changed / 1165 total) ·
hash-proof snapshot (1165) · S184_AUTHORIZED sets unioned in scripts/audit/
affine-relationship-s147.py + quotient-reasoning-s146.py · flagship-tier.mjs BEFORE
gen-product-state.mjs (the latter reads the checked-in file) · PLAN.md manual session block ·
SESSION_NOTES entry.

## Gate baselines
- validate:content 1261/1261 · lint:pedagogy 1175/1175 · registration clean · tsc clean ·
  resolver 17/17 · session184 27/27.
- Full vitest baseline: 76 tests / 17 files failing, all better-sqlite3 native bindings — prove
  byte-identical via `grep "❯ src/" | sort -u` diff.
- Audits: s146 37/37 · s147 35/35 · s148 48/48 + 60/60 mutations · s150 13/13 ·
  failure-first 28/38/50/74. Audits live in scripts/audit/ (NOT scripts/session/).
- Playwright pinned 1.56.1; pre-occupy port 3100 with production `npx next start` + curl 200
  before invoking (config webServer is `npm run dev` with reuseExistingServer).
- gen-product-state spawns a full vitest internally — allow ~5 minutes, run in background.
EOF
echo "HANDOVER rewritten: $(wc -l < HANDOVER.md) lines"
